### PR TITLE
Use Knuth–Morris–Pratt algorithm for delimiter search in TextIO

### LINKED ISSUE #32249: [Bug]: IndexOutOfBoundsException in TextIO.Read with non-default delimiter
### What happened?

The pipeline reading a text file with a non-default delimit [1] fails by `IndexOutOfBoundsException` at `TextBasedReader.readCustomLine` [2].  

The delimiter is "ABCDE" (5 bytes).

The input file is [sample.csv](https://github.com/user-attachments/files/16669008/sample.csv). It is 16400 bytes and has  'A' at index 8190, 'B' at index 8191 (index is 0-based), and 'C' at index 8192. So, the pipeline doesn't split the file content and the whole content should be a single element. 

I have a theory about the root cause as below.

The code [TextBasedReader.readCustomLine](https://github.com/apache/beam/blob/v2.58.1/sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java#L466) writes `buffer` (8192 bytes) into a `ByteArrayOutputStream`, but the range is [0, 8194) when the exception is thrown. This is because the `appendLength`  is 8194, where `readLength` is 8192 (= the length of `buffer`), `delPosn` is 0, `prevDelPosn` is 2. 

For the first buffer read of [0, 8192), the `delPosn` is 2 as the buffer finishes with "AB". For the second buffer read of [8192, 16384), the `delPosn` is reset to 0 (no delimit character matched) while `prevDelPosn` is 2 (= [`delPosn` in prev buffer read](https://github.com/apache/beam/blob/v2.58.1/sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java#L423)). I guess this is a bug not to reset `prevDelPosn` to 0 [when delimiter match fails](https://github.com/apache/beam/blob/v2.58.1/sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java#L456).

[1]
```
public class TextReadJob {
  private static final String INPUT_PATH = "sample.csv";
  private static final byte[] DELIMITER = "ABCDE".getBytes(StandardCharsets.UTF_8);

  public static void main(String[] args) {
    PipelineOptions options = PipelineOptionsFactory.fromArgs(args).create();

    Pipeline pipeline = Pipeline.create(options);

    pipeline.apply(TextIO.read().from(INPUT_PATH).withDelimiter(DELIMITER));

    pipeline.run();
  }
}
```

[2]
```
Aug 19, 2024 9:24:32 PM org.apache.beam.sdk.io.FileBasedSource getEstimatedSizeBytes
INFO: Filepattern sample.csv matched 1 files with total size 16400
Aug 19, 2024 9:24:32 PM org.apache.beam.sdk.io.FileBasedSource split
INFO: Splitting filepattern sample.csv into bundles of size 1025 took 1 ms and produced 1 files and 16 bundles
Exception in thread "main" java.lang.IndexOutOfBoundsException: Range [0, 0 + 8194) out of bounds for length 8192
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:343)
	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:426)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:155)
	at org.apache.beam.sdk.io.TextSource$TextBasedReader.readCustomLine(TextSource.java:466)
	at org.apache.beam.sdk.io.TextSource$TextBasedReader.readNextRecord(TextSource.java:268)
	at org.apache.beam.sdk.io.FileBasedSource$FileBasedReader.advanceImpl(FileBasedSource.java:507)
	at org.apache.beam.sdk.io.FileBasedSource$FileBasedReader.startImpl(FileBasedSource.java:502)
	at org.apache.beam.sdk.io.OffsetBasedSource$OffsetBasedReader.start(OffsetBasedSource.java:252)
	at org.apache.beam.runners.direct.BoundedReadEvaluatorFactory$BoundedReadEvaluator.processElement(BoundedReadEvaluatorFactory.java:150)
	at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:165)
	at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:129)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### LINKED ISSUE #32251: [Bug]: TextIO.read() with non-default delimiter doesn't split at the right position
### What happened?

The pipeline [1] splits a text file with the delimiter "ABC". For the input text "ABABCD", the expected result is ["AB", "D"]. But, the actual pipeline result is ["ABABCD", "D"]. See [2] for the result with DirectRunner.

I guess the delimiter match at [TextSource](https://github.com/apache/beam/blob/v2.58.1/sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java#L448-L458) has the root cause.  It processes the input text "ABABCD" as follows, so fails to match the delimiter "ABC" in the input text.
```
"A": "A" == delimiter[0] (= "A"), set delPosn to 1
"B": "B" == delimiter[1] (= "B"), set delPosn to 2
"A": "A" != delimiter[2] (= "C"), set delPosn to 0 <-- This is wrong. delPosn should be 1 as "A" matches delimiter[0] 
"B": "B" != delimiter[0] (= "A"), set delPosn to 0
"C": "C" != delimiter[0] (= "A"), set delPosn to 0
"D": "D" != delimiter[0] (= "A"), set delPosn to 0
```

I think this is something like a regex match problem (e.g. delimiter "ABCABCABD" and input text "...ABCABCABC...". It may need to have multiple `delPosn`s for partial matches). 

[1]
```
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.io.TextIO;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.ParDo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TextReadJob {
  private static final Logger LOG = LoggerFactory.getLogger(TextReadJob.class);

  private static final String INPUT_PATH = "short.csv"; // content: "ABABCD"

  private static final byte[] DELIMITER = "ABC".getBytes(StandardCharsets.UTF_8);

  public static void main(String[] args) throws IOException {
    PipelineOptions options = PipelineOptionsFactory.fromArgs(args).create();

    Pipeline pipeline = Pipeline.create(options);
    
    pipeline.apply(TextIO.read().from(INPUT_PATH).withDelimiter(DELIMITER)).apply(ParDo.of(new DoFn<String, Void>() {
      @ProcessElement
      public void processElement(@Element String input) {
        LOG.info("input: <{}>", input);
      }
    }));

    pipeline.run();
  }
}
```

[2]
```
ug 19, 2024 11:30:43 PM org.apache.beam.sdk.io.FileBasedSource getEstimatedSizeBytes
INFO: Filepattern short.csv matched 1 files with total size 6
Aug 19, 2024 11:30:43 PM org.apache.beam.sdk.io.FileBasedSource split
INFO: Splitting filepattern short.csv into bundles of size 0 took 1 ms and produced 1 files and 6 bundles
Aug 19, 2024 11:30:43 PM baeminbo.TextReadJob$1 processElement
INFO: input: <ABABCD>
Aug 19, 2024 11:30:43 PM baeminbo.TextReadJob$1 processElement
INFO: input: <D>
```

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by baeminbo**
I believe this PR can fix  #32251 (it's closed but still not fully fixed. see [this case](https://github.com/apache/beam/issues/32251#issuecomment-2323647986)) and #32249.

Fix #32249, #32251.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by baeminbo** [comment]
R: @scwhittle, @Abacn 

Hi @scwhittle, I see you're working on the PR #32258 for fixing the issue #32241. I created this PR to fix the issue #32251 , but I believe it can also fix #32249. 

Hi @Abacn, I see you approved the PR #32298, but it cannot fix  all the cases of #32241. Could you check it again?

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java [hunk 1]
```diff
@@ -487,4 +458,146 @@ private boolean readCustomLine() throws IOException {
...
+      // 0 (0): "A" -> 1
+      // 1 (0): "A" -> 2
+      // 2 (1): "A" -> 2, "B" -> 3
+      // 3 (0): "A" -> 4
+      // 4 (1): "A" -> 5
+      // 5 (2): "A" -> 2, "B" -> 3, "C" -> 6
+      trans[0][byteToIndex(delimiter[0])] = 1;
+
+      for (int i = 1; i < delimiter.length; i++) {
+        for (int b = Byte.MIN_VALUE; b <= Byte.MAX_VALUE; b++) {
```
Comment (scwhittle) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:589]: would https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm be preferrable? Nice to have a documented algorithm and the table is more compact. We can also remove the byteToIndex in that case.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java [hunk 2]
```diff
@@ -377,106 +393,61 @@ private boolean readDefaultLine() throws IOException {
...
             // Optimize for the common case where the string is wholly contained within the buffer
-            currentValue = new String(buffer, startPosn, appendLength, StandardCharsets.UTF_8);
+            currentValue =
+                new String(
+                    buffer, startPosn, readLength - delimiter.length, StandardCharsets.UTF_8);
           } else {
-            str.write(buffer, startPosn, appendLength);
-            currentValue = str.toString(StandardCharsets.UTF_8.name());
+            str.write(buffer, startPosn, readLength);
+            currentValue = str.toString(0, str.size() - delimiter.length, StandardCharsets.UTF_8);
```
Comment (scwhittle) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:450]: Nice, this is simpler to just buffer possible delimiters on buffer boundaries in the string and later ignore them.

**Review by scwhittle — CHANGES_REQUESTED** [review]
Thanks for putting this together, I got bogged down in trying to make startReading correct as well but it is probably best to fix separately.

startReading is incorrect in cases where the offset is smaller than the delimiter length, or smaller than where the headers end, where there is a BOM and headers etc which I uncovered when adding integration test of longer delimiters to sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOReadTest.java

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java (hunk 1 above)
Comment (baeminbo) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java]: Thanks. I changed it to Knuth–Morris–Pratt algorithm.

**Comment by baeminbo** [comment]
@scwhittle Could you continue to review? I added a commit to change the delimiter search algorithm. Thanks.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java [hunk 3]
```diff
@@ -116,8 +118,14 @@ static class TextBasedReader extends FileBasedReader<String> {
 
     private final byte @Nullable [] delimiter;
     private final int skipHeaderLines;
-    private final ByteArrayOutputStream str;
+
+    // The output stream can contain the delimiter at the last. It must exclude the delimiter when
```
Comment (scwhittle) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:122]: How about replacing the first sentence nd maybe add something about how this is used:
"Used to build up results that span buffers. It may contain the delimiter as a suffix."

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java [hunk 4]
```diff
@@ -377,106 +392,61 @@ private boolean readDefaultLine() throws IOException {
...
-                if (buffer[bufferPosn] == delimiter[0]) {
-                  delPosn = 1;
-                } else {
-                  delPosn = 0;
-                }
-                break; // Leave this loop and use the fast-path delimiter matching
-              }
-            }
-          }
+        if (eof) {
```
Comment (scwhittle) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:424]: I think the flow could be simplified by removing the inner while which prevents you from breaking out of the outer while.  The innerwhile is just to retry reading empty length buffers so I think that could be handled separately like:

```
while (true) {
  ..
  if (bufferPos >= bufferLength) {
     startPosn = bufferPosn = 0;
     byteBuffer.clear();
     do {     
        bufferLength = inChannel.read(byteBuffer);
     } while (bufferLength == 0);
     ...

     if (bufferLength < 0) {
     ... // can break directly here 
     }
  }
```

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java [hunk 5]
```diff
@@ -377,106 +392,61 @@ private boolean readDefaultLine() throws IOException {
...
-                bufferPosn++;
-                break;
-              }
-            } else if (buffer[bufferPosn] == delimiter[0]) {
-              delPosn = 1;
-            } else {
-              delPosn = 0;
-            }
+        boolean delimiterFound = false;
+        for (; bufferPosn < bufferLength; ++bufferPosn) {
```
Comment (scwhittle) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:429]: I think you could move startPosn = bufferPosn into loop
`for (int startPosn = bufferPosn; ...) {`

seems nice in that it initializes it as it is being consumed.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java [hunk 6]
```diff
@@ -487,4 +457,110 @@ private boolean readCustomLine() throws IOException {
...
+
+  /**
+   * @see <a
+   *     href="https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm">Knuth–Morris–Pratt
+   *     algorithm</a>
+   */
+  static class KMPDelimiterFinder {
+    private final byte[] delimiter;
+    private final int[] table;
+    int k; // the current position in delimiter
```
Comment (scwhittle) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:507]: can we name the variable currentPos or delimiterOffset or something more descriptive?

File: sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextSourceTest.java [hunk 7]
```diff
@@ -0,0 +1,143 @@
...
+
+    assertEquals(Arrays.asList("A", "B"), split("AABA", "AAABAB"));
+    assertEquals(Arrays.asList("AABBA"), split("AABA", "AABBA"));
+
+    assertEquals(Arrays.asList("", "D"), split("ABABC", "ABABCD"));
+    assertEquals(Arrays.asList("ABABAD"), split("ABABC", "ABABAD"));
+    assertEquals(Arrays.asList("ABABBD"), split("ABABC", "ABABBD"));
+    assertEquals(Arrays.asList("AB"), split("ABABC", "ABABABC"));
+
+    assertEquals(Arrays.asList(""), split("ABCABD", "ABCABD"));
```
Comment (scwhittle) [inline sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextSourceTest.java:98]: I don't see a test where there are several delimiters in a row, do we want multiple empty strings as result in that case?
ie
split("AA", "AAAAAA") ->  ["", "", ""] ?

**Review by scwhittle — APPROVED** [review]
Just some minor cleanup comments. Thanks!

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java (hunk 3 above)
Comment (baeminbo) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java]: Done

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java (hunk 4 above)
Comment (baeminbo) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java]: Done

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java (hunk 6 above)
Comment (baeminbo) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java]: Done

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java [hunk 8]
```diff
@@ -402,11 +401,11 @@ private boolean readCustomLine() throws IOException {
...
-          startPosn = bufferPosn = 0;
+        if (bufferPosn >= bufferLength) {
           byteBuffer.clear();
-          bufferLength = inChannel.read(byteBuffer);
+          do {
+            bufferLength = inChannel.read(byteBuffer);
+          } while (bufferLength == 0);
 
           if (bufferLength < 0) {
             eof = true;
```
Comment (scwhittle) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:411]: need break here now

File: sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextSourceTest.java (hunk 7 above)
Comment (baeminbo) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextSourceTest.java:103]: Done.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java (hunk 5 above)
Comment (baeminbo) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:425]: I changed the location of `startPosn` just before the loop. If it's initialized in the loop, it looks like:
```
        int startPosn;
        for (startPosn = bufferPosn; bufferPosn < bufferLength; ++bufferPosn) { <-- looks a bit weird to me as `startPosn` is initialized only and not changed in the loop. 
          if (delimiterFinder.feed(buffer[bufferPosn])) {
            ++bufferPosn;
            delimiterFound = true;
            break;
          }
        }

        int readLength = bufferPosn - startPosn;  <-- `startPosn` is used here. It cannot be in the scope of the loop above.
        bytesConsumed += readLength;
        ...
```

File: sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java (hunk 8 above)
Comment (baeminbo) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/io/TextSource.java:411]: It does `break` if it's EOF. Then, it quite the big loop and return the current value. When it reads some data, it goes to find a delimiter inside the `buffer`.

```
      while (true) {
        if (bufferPosn >= bufferLength) { <-- changed from `while` to `if`
          byteBuffer.clear();
          do {
            bufferLength = inChannel.read(byteBuffer); <-- looping until read something or EOF.
          } while (bufferLength == 0);

          if (bufferLength < 0) {
            eof = true;

            if (str.size() == 0) {
              return false;
            }

            // Not ending with a delimiter.
            currentValue = str.toString(StandardCharsets.UTF_8.name());
            break;  <-- break here
          }
        }

        ... (continue to find the delimiter in the buffer)...
     
```

**Comment by scwhittle** [comment]
Run Java_IOs_Direct PreCommit

**Comment by baeminbo** [comment]
@scwhittle I fixed a bug at [a commit](https://github.com/apache/beam/compare/79ed964c519d00b63ac36a91d74b2c5432dd2ba7..4ad8e27d3a0d749d201ba49ab182d8ffce192921) which made the test failed. Could you continue to review this? Thanks.
