### PR TITLE
[RRIO] Build RequestResponseIO and related dependency changes

### LINKED ISSUE #28934: [Task]: [RRIO] RequestResponseIO transform
### What needs to happen?

The output of this task brings all the transforms together into the public facing RequestResponseIO.

# Measures of Ready

see [RRIO tasks](https://github.com/apache/beam/issues?q=is%3Aissue+is%3Aopen+%5BRRIO%5D)

# Measures of Done

- [ ] expand composites transform based on user provided parameters
- [ ] end-to-end integration tests validate behavior

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### LINKED ISSUE #29724: [Failing Test]: rrio. CallTest. givenTeardownTimeout_throwsError flaky
### What happened?

A flaky test found in recently added RequestResponseIO. Example run: https://github.com/apache/beam/runs/19532250831

stack trace:

```
java.lang.AssertionError: expected java.lang.IllegalStateException to be thrown, but nothing was thrown
	at org.junit.Assert.assertThrows(Assert.java:1028)
	at org.junit.Assert.assertThrows(Assert.java:981)
	at org.apache.beam.io.requestresponse.CallTest.givenTeardownTimeout_throwsError(CallTest.java:244)
```

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by damondouglas**
This PR closes #28934 with final planned incorporation of various features - Throttle, Cache, and Call. The PR adds additional Call related features such as backoff and repeat. This PR also closes #29724 by removing the unnecessary and flaky test.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Cache.java [hunk 1]
```diff
@@ -27,13 +27,28 @@
...
 
 /** Transforms for reading and writing request/response associations to a cache. */
 final class Cache {
 
+  /**
+   * {@link VisibleForTesting} to test {@link RequestResponseIO} composite transform construction
+   * without exposing {@link UsingRedis.Read}.
+   */
+  @VisibleForTesting
+  static final String CACHE_READ_USING_REDIS = Cache.UsingRedis.Read.class.getName();
```
Comment (johnjcasey) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Cache.java:43]: Were you able to sync with @kennknowles on redis usage?

Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Cache.java:43]: Scheduled meeting with him.

Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Cache.java:43]: Resolving this as we discussed. Please re-open if this remains an issue. Thank you for looking at this PR.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java [hunk 2]
```diff
@@ -169,12 +189,61 @@ private CallFn(
...
+              .setBackOff(backOff)
+              .setSleeper(sleeper)
+              .setThrowableFunction(
+                  ignored -> {
+                    this.setupTeardown.setup();
+                    return null;
+                  })
+              .build();
+
+      repeater.apply(null);
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:223]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java [hunk 3]
```diff
@@ -169,12 +189,61 @@ private CallFn(
...
+              .setBackOff(backOff)
+              .setSleeper(sleeper)
+              .setThrowableFunction(
+                  ignored -> {
+                    setupTeardown.teardown();
+                    return null;
+                  })
+              .build();
+
+      repeater.apply(null);
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:246]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java [hunk 4]
```diff
@@ -183,9 +252,20 @@ public void setup() throws UserCodeExecutionException {
...
+        try {
+          sleeper.sleep(backOff.nextBackOffMillis());
+        } catch (InterruptedException ignored) {
+        } catch (IOException e) {
+          throw new UserCodeExecutionException(e);
+        }
+      }
+
+      performTeardown();
+
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:268]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java [hunk 5]
```diff
@@ -196,9 +276,40 @@ public void teardown() throws UserCodeExecutionException {
...
+        return;
+      }
+
+      Repeater<RequestT, ResponseT> repeater =
+          Repeater.<RequestT, ResponseT>builder()
+              .setSleeper(sleeper)
+              .setBackOff(backOff)
+              .setThrowableFunction(caller::call)
+              .build();
+
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:310]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java [hunk 6]
```diff
@@ -234,25 +345,79 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+    abstract SerializableSupplier<Sleeper> getSleeperSupplier();
+
+    /**
+     * The {@link SerializableSupplier} of a {@link BackOff} that reports to a {@link Sleeper} how
+     * long to pause execution. It reports a {@link BackOff#STOP} to stop repeating invocation
+     * attempts. Supplies with {@link FluentBackoff#DEFAULT} by default. The need for a {@link
+     * SerializableSupplier} instead of setting this directly is that some {@link BackOff}
+     * implementations, such as {@link FluentBackoff} are not {@link Serializable}.
+     */
+    abstract SerializableSupplier<BackOff> getBackOffSupplier();
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:378]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 7]
```diff
@@ -51,35 +77,276 @@
...
+   * {@link Set} of {@link UserCodeExecutionException}s that warrant repeating. Not all errors
+   * should be repeat execution such as bad or unauthenticated requests. However, certain errors
+   * such as timeouts, remote system or quota exceed errors may not be related to the code but due
+   * to the remote system and thus warrant repeating.
+   */
+  public static final Set<Class<? extends UserCodeExecutionException>> REPEATABLE_ERROR_TYPES =
+      ImmutableSet.of(
+          UserCodeRemoteSystemException.class,
+          UserCodeTimeoutException.class,
+          UserCodeQuotaException.class);
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:111]: @bvolpato Thank you

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 8]
```diff
@@ -51,35 +77,276 @@
...
+
+    caller = SerializableUtils.ensureSerializable(caller);
+
+    return new RequestResponseIO<>(
+            Configuration.<RequestT, ResponseT>builder().setResponseTCoder(responseTCoder).build(),
+            Call.Configuration.<RequestT, ResponseT>builder()
+                .setCaller(caller)
+                .setResponseCoder(responseTCoder)
+                .build())
+        .withDefaults();
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:171]: @bvolpato Thank you

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 9]
```diff
@@ -51,35 +77,276 @@
...
+
+    return new RequestResponseIO<>(
+            Configuration.<RequestT, ResponseT>builder().setResponseTCoder(responseTCoder).build(),
+            Call.Configuration.<RequestT, ResponseT>builder()
+                .setCaller(implementsCallerAndSetupTeardown)
+                .setSetupTeardown(implementsCallerAndSetupTeardown)
+                .setResponseCoder(responseTCoder)
+                .build())
+        .withDefaults();
+  }
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:197]: @bvolpato Thank you

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 10]
```diff
@@ -51,35 +77,276 @@
...
+
+  private RequestResponseIO<RequestT, ResponseT> withDefaults() {
+    return withTimeout(DEFAULT_TIMEOUT)
+        .shouldRepeat(true)
+        .withBackOffSupplier(new DefaultSerializableBackoffSupplier())
+        .withSleeperSupplier((SerializableSupplier<Sleeper>) () -> Sleeper.DEFAULT)
+        .withCallShouldBackoff(new CallShouldBackoffBasedOnRejectionProbability<>());
+  }
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:205]: @bvolpato Thank you

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 11]
```diff
@@ -51,35 +77,276 @@
...
+   * to a cache. The transform applies a result of {@link Call} to the {@link PTransform} supplied
+   * by this method. It is intended for this method and {@link #withCacheRead} to be used together.
+   * Default for {@link RequestResponseIO} is to not write to a cache.
+   */
+  public RequestResponseIO<RequestT, ResponseT> withCacheWrite(
+      PTransform<PCollection<KV<RequestT, ResponseT>>, Result<KV<RequestT, ResponseT>>>
+          cacheWrite) {
+    return new RequestResponseIO<>(
+        rrioConfiguration.toBuilder().setCacheWrite(cacheWrite).build(), callConfiguration);
+  }
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:332]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 12]
```diff
@@ -51,35 +77,276 @@
...
+   * Configures {@link RequestResponseIO} with a {@link PTransform} that holds back {@link
+   * RequestT}s to prevent quota errors such as HTTP 429 or gRPC RESOURCE_EXHAUSTION errors.
+   */
+  // TODO(damondouglas): Until https://github.com/apache/beam/issues/28930 there is no provided
+  //  solution for this, however this method allows users to provide their own at this time.
+  public RequestResponseIO<RequestT, ResponseT> withPreventiveThrottle(
+      PTransform<PCollection<RequestT>, Result<RequestT>> throttle) {
     return new RequestResponseIO<>(
-        Configuration.<RequestT, ResponseT>builder().setCaller(caller).build());
+        rrioConfiguration.toBuilder().setThrottle(throttle).build(), callConfiguration);
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:343]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 13]
```diff
@@ -88,73 +355,316 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+    abstract @Nullable PTransform<PCollection<RequestT>, Result<KV<RequestT, @Nullable ResponseT>>>
+        getCacheRead();
+
+    /** Writes {@link RequestT} and {@link ResponseT} associations to a cache. */
+    abstract @Nullable PTransform<
+            PCollection<KV<RequestT, ResponseT>>, Result<KV<RequestT, ResponseT>>>
+        getCacheWrite();
+
+    /** Throttles a {@link RequestT} {@link PCollection}. */
+    abstract @Nullable PTransform<PCollection<RequestT>, Result<RequestT>> getThrottle();
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:376]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 14]
```diff
@@ -88,73 +355,316 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+    failureList = call.getRight();
+
+    // Flatten the responses and failures.
+    PCollection<ResponseT> responses =
+        responseList.apply("FlattenResponses", Flatten.pCollections());
+    PCollection<ApiIOError> failures = failureList.apply("FlattenErrors", Flatten.pCollections());
+
+    // Prepare and return final result.
+    PCollectionTuple pct = PCollectionTuple.of(responseTag, responses).and(failureTag, failures);
+    return Result.of(responses.getCoder(), responseTag, failureTag, pct);
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:436]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 15]
```diff
@@ -88,73 +355,316 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+    responseList =
+        responseList.and(
+            cacheReadList
+                .get(PartitionCacheReadsFn.NON_NULL_PARTITION)
+                .apply("CachedResponses", Values.create()));
+
+    // Append any failures to the final output.
+    failureList = failureList.and(cacheReadResult.getFailures());
+
+    return Triple.of(input, responseList, failureList);
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:487]: @bvolpato Thank you

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 16]
```diff
@@ -88,73 +355,316 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+      PCollection<RequestT> input, PCollectionList<ApiIOError> failureList) {
+
+    if (rrioConfiguration.getThrottle() == null) {
+      return Pair.of(input, failureList);
+    }
+
+    Result<RequestT> throttleResult =
+        input.apply(THROTTLE_NAME, checkStateNotNull(rrioConfiguration.getThrottle()));
+
+    return Pair.of(throttleResult.getResponses(), failureList.and(throttleResult.getFailures()));
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:513]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 17]
```diff
@@ -88,73 +355,316 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+   *   <li>If {@link Configuration#getCacheWrite} not available, instantiates and applies a
+   *   {@link Call} using original {@link Caller} and optionally
+   *   {@link SetupTeardown}. </li>
+   *   <li>Otherwise, wraps the original {@link Caller} using
+   *   {@link WrappedAssociatingRequestResponseCaller} that preserves the association between the
+   *   {@link RequestT} and its {@link ResponseT}.</li>
+   *   <li>Applies the resulting {@link KV} of the {@link RequestT} and its {@link ResponseT}
+   *   to the {@link Configuration#getCacheWrite}, returning appended failures to the failureList
+   *   and appended responses to the responseList.</li>
+   * </ol></pre>
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:530]: @bvolpato Thank you

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 18]
```diff
@@ -88,73 +355,316 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+    failureList = failureList.and(result.getFailures());
+
+    // Write RequestT and ResponseT pairs to the cache; append failures.
+    Result<KV<RequestT, ResponseT>> cacheWriteResult =
+        result
+            .getResponses()
+            .apply(CACHE_WRITE_NAME, checkStateNotNull(rrioConfiguration.getCacheWrite()));
+    failureList = failureList.and(cacheWriteResult.getFailures());
+
+    return Pair.of(responseList, failureList);
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:582]: @bvolpato Thank you

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 19]
```diff
@@ -88,73 +355,316 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+    private static final int NULL_PARTITION = 1;
+
+    @Override
+    public int partitionFor(KV<RequestT, ResponseT> elem, int numPartitions) {
+      if (checkStateNotNull(elem).getValue() != null) {
+        return NON_NULL_PARTITION;
+      }
+      return NULL_PARTITION;
+    }
+  }
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:599]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 20]
```diff
@@ -88,73 +355,316 @@ static <RequestT, ResponseT> Builder<RequestT, ResponseT> builder() {
...
+    private WrappedAssociatingRequestResponseCaller(Caller<RequestT, ResponseT> caller) {
+      this.caller = caller;
+    }
+
+    @Override
+    public KV<RequestT, ResponseT> call(RequestT request) throws UserCodeExecutionException {
+      ResponseT response = caller.call(request);
+      return KV.of(request, response);
     }
+  }
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:615]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/WindowedCallShouldBackoff.java [hunk 21]
```diff
@@ -0,0 +1,76 @@
...
+    resetIfNeeded();
+    checkStateNotNull(basis).update(response);
+  }
+
+  @Override
+  public boolean value() {
+    resetIfNeeded();
+    return checkStateNotNull(basis).value();
+  }
+}
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/WindowedCallShouldBackoff.java:76]: @bvolpato Thank you

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOIT.java [hunk 22]
```diff
@@ -0,0 +1,95 @@
...
+    return pipeline.apply("generate", Create.of(requests));
+  }
+
+  private static @NonNull EchoRequest createShouldNeverExceedQuotaRequest() {
+    return EchoRequest.newBuilder()
+        .setPayload(PAYLOAD)
+        .setId(checkStateNotNull(options).getNeverExceedQuotaId())
+        .build();
+  }
+}
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOIT.java:95]: @bvolpato Thank you

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOTest.java [hunk 23]
```diff
@@ -0,0 +1,443 @@
...
+        configuration.getSleeperSupplier().get().getClass(), equalTo(Sleeper.DEFAULT.getClass()));
+    assertThat(
+        configuration.getCallShouldBackoff().getClass().getName(),
+        equalTo(WRAPPED_CALL_SHOULD_BACKOFF));
+
+    visitor.assertExpandsWithCallOf(
+        CACHE_READ_NAME, CACHE_READ_USING_REDIS, CACHE_READ_USING_REDIS);
+    visitor.assertExpandsWithCallOf(
+        CACHE_WRITE_NAME, CACHE_WRITE_USING_REDIS, CACHE_WRITE_USING_REDIS);
+  }
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOTest.java:257]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/WindowedCallShouldBackoffTest.java [hunk 24]
```diff
@@ -0,0 +1,56 @@
...
+    assertThat(instance.value(), equalTo(true));
+  }
+
+  private static WindowedCallShouldBackoff<Integer> instantiate(Duration window) {
+    return new WindowedCallShouldBackoff<>(
+        window,
+        (SerializableSupplier<CallShouldBackoff<Integer>>)
+            () -> new CallShouldBackoffBasedOnRejectionProbability<Integer>().setThreshold(0.5));
+  }
+}
```
Comment (damondouglas) [inline sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/WindowedCallShouldBackoffTest.java:56]: @johnjcasey or @Abacn Thank you.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java (hunk 2 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:223]: LGTM

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java (hunk 3 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:246]: lgtm

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java [hunk 25]
```diff
@@ -183,9 +252,20 @@ public void setup() throws UserCodeExecutionException {
...
     public void teardown() throws UserCodeExecutionException {
-      // TODO(damondouglas): Incorporate repeater when https://github.com/apache/beam/issues/28926
-      //  resolves.
-      this.setupTeardown.teardown();
+      BackOff backOff = configuration.getBackOffSupplier().get();
+      Sleeper sleeper = configuration.getSleeperSupplier().get();
+
+      if (configuration.getCallShouldBackoff().value()) {
+        try {
+          sleeper.sleep(backOff.nextBackOffMillis());
```
Comment (johnjcasey) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:260]: why do we sleep before performing the first teardown?

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java [hunk 26]
```diff
@@ -196,9 +276,40 @@ public void teardown() throws UserCodeExecutionException {
     @ProcessElement
     public void process(@Element @NonNull RequestT request, MultiOutputReceiver receiver)
         throws JsonProcessingException {
+
+      BackOff backOff = configuration.getBackOffSupplier().get();
+      Sleeper sleeper = configuration.getSleeperSupplier().get();
+
+      if (configuration.getCallShouldBackoff().value()) {
+        try {
+          sleeper.sleep(backOff.nextBackOffMillis());
```
Comment (johnjcasey) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:285]: on the first call, this backoff would be 0, correct? It would only be non-zero if we are getting throttled?

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java (hunk 6 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:378]: lgtm

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java [hunk 27]
```diff
@@ -51,35 +77,276 @@
...
+   *
+   * <ul>
+   *   <li>{@code URI uri} - the {@link URI} of the Redis instance.
+   *   <li>{@code Coder<RequestT> requestTCoder} - the {@link RequestT} {@link Coder} to encode and
+   *       decode {@link RequestT}s during cache read and writes.
+   *   <li>{@code Duration expiry} - the duration to hold {@link RequestT} and {@link ResponseT}
+   *       pairs in the cache.
+   * </ul>
+   */
+  public RequestResponseIO<RequestT, ResponseT> withRedisCache(
```
Comment (johnjcasey) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:285]: This utility method makes a lot of sense to exist, but I'm not sure it should exist on RRIO directly. On the other hand. I'm not sure where else it would be. My general concern is that with additional cache implementations, we could end up with a number of utility methods on RRIO.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java (hunk 12 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:343]: LGTM

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java (hunk 13 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:376]: lgtm

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java (hunk 16 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:513]: LGTM

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java (hunk 15 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:487]: LGTM

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java (hunk 14 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:436]: LGTM

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java (hunk 19 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:599]: could you add some documentation on this? its a bit confusing as to what the purpose of this function is. Also, why do we have a constant NUM_PARTITIONS that doesn't appear to be used?

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java (hunk 20 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:615]: lgtm

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/WindowedCallShouldBackoffTest.java (hunk 24 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/WindowedCallShouldBackoffTest.java:56]: lgtm

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOTest.java (hunk 23 above)
Comment (johnjcasey) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/RequestResponseIOTest.java:257]: I would be careful with this category of tests. Particular expansion checks can be fragile, so I would expect these tests to be flakier than an 'average' test. Also, while these verify configuration is set, they don't actually execute the pipeline. 

I would look to add a few tests with a mock call implemented, so as to verify behavior in both happy path and error scenarios.

**Review by johnjcasey — CHANGES_REQUESTED** [review]

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java (hunk 25 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:260]: `configuration.getCallShouldBackoff().value()` returns a boolean. Therefore, `if (configuration.getCallShouldBackoff().value())` enters conditional block when true and invokes `sleeper.sleep`.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java (hunk 26 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:285]: Not necessarily, it depends on the underlying [getRandomValueFromInterval](https://github.com/googleapis/google-http-java-client/blob/main/google-http-client/src/main/java/com/google/api/client/util/ExponentialBackOff.java#L176) if using the default Backoff.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java (hunk 27 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/RequestResponseIO.java:285]: I'd advocate that explicit stating the type of resource is important here as it requires provisioning beforehand.
One approach is to publicly expose the Cache.usingRedis that returns the needed transform. But then we would need to accept that everything publicly exposed requires a lot of work to deprecate later. There are withCacheRead and withCacheWrite methods where the user could supply their own implementations.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java (hunk 25 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:321]: I will resolve this but please re-open if there are further issues. Thank you for reviewing this.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java (hunk 26 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:359]: I will resolve this. Could you please re-open if there are additional questions/comments?

**Review by johnjcasey — APPROVED** [review]
This LGTM.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Repeater.java [hunk 28]
```diff
@@ -65,28 +60,75 @@ static <InputT, OutputT> Builder<InputT, OutputT> builder() {
...
+   * BackOff#STOP}.
    */
   OutputT apply(InputT input) throws UserCodeExecutionException {
     Optional<UserCodeExecutionException> latestError = Optional.empty();
     long waitFor = 0L;
     while (waitFor != BackOff.STOP) {
       try {
-        getSleeper().sleep(waitFor);
+        if (waitFor > 0L) {
+          if (getSleeperCounter() != null) {
```
Comment (Abacn) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Repeater.java:112]: this is slightly different than previous comment but still checks null twice. It occurs frequently enough so consider a simple helper function
```
void incIfPresent(@Nullable counter) {
  if (counter != null) {
    counter.inc()
  }
}
```
to simplify. This also applied to Call.java

Use Optional counters could be another solution. 

```
if(getCounter().isPresent()){
  getCounter().inc();
}
```

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Result.java [hunk 29]
```diff
@@ -0,0 +1,91 @@
...
+  public PCollection<ResponseT> getResponses() {
+    return responses;
+  }
+
+  public PCollection<ApiIOError> getFailures() {
+    return failures;
+  }
+
+  @Override
+  public @NonNull Pipeline getPipeline() {
```
Comment (Abacn) [inline sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Result.java:77]: cleanup redundant NonNulls.

I do see IDE warnings on IKEA but I believe they are redundant.

**Review by Abacn — COMMENTED** [review]
Thanks, went through the main src once and just had a few comments about clean up

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/DefaultSerializableBackoffSupplier.java [hunk 30]
```diff
@@ -0,0 +1,35 @@
...
+import org.apache.beam.sdk.util.BackOff;
+import org.apache.beam.sdk.util.FluentBackoff;
+import org.apache.beam.sdk.util.SerializableUtils;
+
+/**
+ * A default {@link SerializableSupplier} of a {@link BackOff} that relies on {@link
+ * FluentBackoff#DEFAULT}. Embedding {@link FluentBackoff#DEFAULT} in a lambda failed {@link
+ * SerializableUtils#ensureSerializable}.
+ */
+class DefaultSerializableBackoffSupplier implements SerializableSupplier<BackOff> {
```
[the remark this answers is not in the document]
Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/DefaultSerializableBackoffSupplier.java:29]: Given most of the work of the package occurs in Call, and hence a large java file, I would like to minimize the number of internal classes, advocating for readability in the setting of neurodivergence accessibility.

[the remark this answers is not in the document]
Comment (Abacn) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/DefaultSerializableBackoffSupplier.java:29]: thanks, sounds good

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Repeater.java (hunk 28 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Repeater.java:112]: Thank you so much @Abacn for this suggestion. This really helped clean up the code.

File: sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java [hunk 31]
```diff
@@ -183,9 +313,20 @@ public void setup() throws UserCodeExecutionException {
...
+        } catch (IOException e) {
+          throw new UserCodeExecutionException(e);
+        }
+      }
+
+      performTeardown();
+
       checkStateNotNull(executor).shutdown();
       try {
         boolean ignored = executor.awaitTermination(3L, TimeUnit.SECONDS);
```
[the remark this answers is not in the document]
Comment (damondouglas) [reply sdks/java/io/rrio/src/main/java/org/apache/beam/io/requestresponse/Call.java:299]: I'm going to resolve this as I went ahead and changed the method name from value() to isTrue to improve readability. Please re-open if you have further issues and thank you for bring this up.

**Review by Abacn — APPROVED** [review]
LGTM, thank you!
