### PR TITLE
[24664] Fix ProcessBundleBenchmarkTest.testStateWithCaching

### LINKED ISSUE #24664: [Failing Test]: ProcessBundleBenchmarkTest.testStateWithCaching
### What happened?

https://github.com/apache/beam/actions/runs/3690463659/jobs/6247487642

> Task :sdks:java:harness:jmh:test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.github.jamm.MemoryMeterBase (file:/home/runner/.gradle/caches/modules-2/files-2.1/io.github.stephankoelle/jamm/0.4.1/df04e7daebba29088daaf1a00f103863b9df61c2/jamm-0.4.1.jar) to field java.lang.String.value
WARNING: Please consider reporting this to the maintainers of org.github.jamm.MemoryMeterBase
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

org.apache.beam.fn.harness.jmh.ProcessBundleBenchmarkTest > testStateWithCaching FAILED
    java.util.concurrent.ExecutionException at ProcessBundleBenchmarkTest.java:54
        Caused by: java.lang.RuntimeException at ProcessBundleBenchmark.java:175
            Caused by: java.lang.RuntimeException at UnboundedScheduledExecutorService.java:316
                Caused by: java.lang.InterruptedException at FutureTask.java:418

15 tests completed, 1 failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdks:java:harness:jmh:test'.
> There were failing tests. See the report at: file:///home/runner/work/beam/beam/sdks/java/harness/jmh/build/reports/tests/test/index.html

### Issue Failure

Failure: Test is flaky

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python
- [X] Component: Java
- [ ] Component: Go
- [ ] Component: Typescript
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by damondouglas**
This PR closes #24664 by adding an explicit and ignored InterrptedException catch and moving the shutdownNow of sdkHarnessExecutor and serverExecutor in the finally clause.

https://github.com/apache/beam/actions/runs/3690463659/jobs/6247487642 reports the error stack trace:
```
org.apache.beam.fn.harness.jmh.ProcessBundleBenchmarkTest > testStateWithCaching FAILED
    java.util.concurrent.ExecutionException at ProcessBundleBenchmarkTest.java:54
        Caused by: java.lang.RuntimeException at ProcessBundleBenchmark.java:175
            Caused by: java.lang.RuntimeException at UnboundedScheduledExecutorService.java:316
                Caused by: java.lang.InterruptedException at FutureTask.java:418
```

[ProcessBundleBenchmarkTest.java:54](https://github.com/apache/beam/blob/master/sdks/java/harness/jmh/src/test/java/org/apache/beam/fn/harness/jmh/ProcessBundleBenchmarkTest.java#L54) occurs when the code invokes tearDown:
```
     StatefulTransform transform = new StatefulTransform();
     new ProcessBundleBenchmark().testStateWithCaching(transform);
-->  transform.tearDown();
```

Since `StatefulTransform` extends `SdkHarness`, we find the tearDown method code at [ProcessBundleBenchmark.java#L200-L201](https://github.com/apache/beam/blob/master/sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/ProcessBundleBenchmark.java#L200-L201).  Noteably, an `//expected` code comment suggests that at tearDown, we expect an InterruptedException.  However, when sdkHarnessExecutorFuture.get(); is invoked, we still see `Caused by: java.lang.InterruptedException at FutureTask.java:418`
```
      try {
        sdkHarnessExecutorFuture.get();
      } catch (ExecutionException e) {
        if (e.getCause() instanceof RuntimeException
  ----> && e.getCause().getCause() instanceof InterruptedException) {
  ----> // expected
        } else {
          throw e;
        }
      }
```

By refactoring as follows, we may have prevented the re-throwing of `InterruptedException`.
```
catch (InterruptedException ignored) {
        // expected
      } catch (Exception e) {
        throw new RuntimeException(e);
      } finally {
        sdkHarnessExecutor.shutdownNow();
        serverExecutor.shutdownNow();
}
```
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - ~[ ] Update `CHANGES.md` with noteworthy changes.~
 - ~[ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/ProcessBundleBenchmark.java [hunk 1]
```diff
@@ -185,23 +184,21 @@ public void log(LogEntry entry) {
...
         sdkHarnessExecutorFuture.get();
-      } catch (ExecutionException e) {
-        if (e.getCause() instanceof RuntimeException
-            && e.getCause().getCause() instanceof InterruptedException) {
-          // expected
-        } else {
-          throw e;
-        }
+      } catch (InterruptedException ignored) {
+        // expected
```
Comment (kennknowles) [inline sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/ProcessBundleBenchmark.java:196]: Probably good practice to ` Thread.currentThread().interrupt();` here

Comment (damondouglas) [reply sdks/java/harness/jmh/src/main/java/org/apache/beam/fn/harness/jmh/ProcessBundleBenchmark.java:196]: Fixing... thank you.

**Comment by damondouglas** [comment]
@kennknowles It's so nice to see all green checks

**Review by lostluck — APPROVED** [review]
