### PR TITLE
Fix a split bundle bug when using timers in stateful dofn

### LINKED ISSUE #35771: [Bug]: Prism not handling on_timer callbacks correctly when split happens
### What happened?

```
import logging

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions
from apache_beam.utils.timestamp import Timestamp
from apache_beam.utils.timestamp import MIN_TIMESTAMP, MAX_TIMESTAMP
from apache_beam.transforms.timeutil import TimeDomain
from apache_beam.transforms.userstate import TimerSpec, on_timer


logging.basicConfig(level=logging.INFO)

options = PipelineOptions([
    "--environment_type=LOOPBACK",
    "--runner=PrismRunner",
])


data = [(0, 0), (1, 1), (2, 0)]

class MyDoFn(beam.DoFn):
  WINDOW_TIMER = TimerSpec('window_timer', TimeDomain.WATERMARK)

  def __init__(self):
    pass

  def process(
      self,
      element,
      window=beam.DoFn.WindowParam,
      window_timer=beam.DoFn.TimerParam(WINDOW_TIMER),
      ):
    print("process is called")
    window_timer.set(window.end)


  @on_timer(WINDOW_TIMER)
  def on_timer(self, key=beam.DoFn.KeyParam):
    import time
    time.sleep(1)
    yield "on_timer called on key %s" % str(key)


with beam.Pipeline(options=options) as p:
  _ = (
      p | beam.Create(data)
      | beam.ParDo(MyDoFn())
      | beam.LogElements(
          level=logging.WARNING,
          ))
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by shunping**
Attempt to fixes #35771

### CODE REVIEW

File: sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go [hunk 1]
```diff
@@ -1920,8 +1923,18 @@ func (ss *stageState) splitBundle(rb RunBundle, firstResidual int) {
...
 
 	es.es = prim
-	ss.pending = append(ss.pending, res...)
-	heap.Init(&ss.pending)
+
+	for _, e := range res {
+		delete(ss.inprogressKeysByBundle[rb.BundleID], string(e.keyBytes))
+		delete(ss.inprogressKeys, string(e.keyBytes))
+
+		if e.IsTimer() {
```
Comment (shunping) [inline sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go:1931]: Since we should no longer call splitBundle on a bundle with timers, maybe we can also get rid of the code for handling holds here.

Comment (lostluck) [reply sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go:1931]: My vote is to keep it, but add a warning log that splitting on timers has occurred and is unexpected. Include a link to the issue.

Comment (shunping) [reply sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go:1931]: Sg. I added the warning message.
