### PR TITLE
[Java SDK] Fix propagation of metrics set during onTimer processing.

### LINKED ISSUE #29099: [Bug]: FnAPI Java SDK Harness doesn't not update user counters in OnTimer callback functions
### What happened?

This can be re-produced with simple DoFn with user counters, the updates in counters in processElement are populated properly to MointoringInfos when sending back ProcessBundleInstructionResponse, however the counters in onTimer callback are not recorded.

```
DoFn<KV<String, Long>, KV<Long, Instant>> fn =
          new DoFn<KV<String, Long>, KV<Long, Instant>>() {

            @TimerId(timerId)
            private final TimerSpec spec = TimerSpecs.timer(TimeDomain.EVENT_TIME);

            final Counter startTimers = Metrics.counter("timers", "started_timers_count");
            final Counter firedTimers = Metrics.counter("timers", "fired_timers_count");

            @ProcessElement
            public void processElement(
                @TimerId(timerId) Timer timer,
                @Timestamp Instant timestamp,
                OutputReceiver<KV<Long, Instant>> r) {
              timer
                  .align(Duration.standardMinutes(1))
                  .offset(Duration.standardSeconds(1))
                  .setRelative();
              LOG.info("started timer");
              startTimers.inc();
              r.output(KV.of(3L, timestamp));
            }

            @OnTimer(timerId)
            public void onTimer(@Timestamp Instant timestamp, OutputReceiver<KV<Long, Instant>> r) {
              LOG.info("fired timer");
              firedTimers.inc();
              r.output(KV.of(42L, timestamp));
            }
          };
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by scwhittle**
Fixes #29099.  Added unit test that verifies ProcessBundleHandler plumbing in addition to the existing FnApiRunner test which is at a lower level.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java [hunk 1]
```diff
@@ -92,10 +92,23 @@ public static ConsumerAndMetadata forConsumer(
...
+    public abstract String getPTransformId();
+
+    public abstract String getPTransformUniqueId();
+  }
+
   private final ExecutionStateTracker stateTracker;
   private final ShortIdMap shortIdMap;
-  private final Map<String, List<ConsumerAndMetadata>> pCollectionIdsToConsumers;
-  private final Map<String, FnDataReceiver> pCollectionIdsToWrappedConsumer;
+  private final Map<String, List<ConsumerAndMetadata>> pCollectionIdsToConsumers = new HashMap<>();
```
Comment (kennknowles) [inline sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java:109]: It is starting to look like there should be some sort of object/actor associated with a PCollection to encapsulate the access to these maps, maybe? Just musing.

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java [hunk 2]
```diff
@@ -445,8 +445,20 @@ public <T> void addIncomingTimerEndpoint(
                     String timerFamilyId,
                     org.apache.beam.sdk.coders.Coder<Timer<T>> coder,
                     FnDataReceiver<Timer<T>> receiver) {
+                  ExecutionStateSampler.ExecutionState executionState =
+                      pCollectionConsumerRegistry.getProcessingExecutionState(
+                          pTransformId, pTransform.getUniqueName());
+                  FnDataReceiver<Timer<T>> wrappedReceiver =
+                      (Timer<T> timer) -> {
+                        executionState.activate();
```
Comment (kennknowles) [inline sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java:453]: Possibility for the future: try-with-resources style?

```java
try (SomeThing stateScopeMaybeUnused = executionstate.activate()) {
  receiver.accept(timer);
}
```

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java (hunk 1 above)
Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/data/PCollectionConsumerRegistry.java:109]: Yes I think that some sort of PCollection registry could be better to capture that, but punting for now.

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java (hunk 2 above)
Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/control/ProcessBundleHandler.java:453]: I will put together a separate PR, looks like it would cleanup all the call-sites
