### PR TITLE
Enforce splitting invariants by ensuring split state is reset in the same synchronized block as window index increments. 

### LINKED ISSUE #23881: [Bug]: IllegalArgumentException during bundle split in FnApiDoFnRunner.scaleProgress
### What happened?

Full stack trace (ocr from image so may be slightly off):
"java.lang.IllegalArgumentException: Work completed and work remaining must be greater than or equal to zero but were 3.332476747E9
and -1.666238373E9.
Consumer Registry.java:434)
}
at org.apache.beam.sdk.transforms.splittabledofn. Restriction Tracker $Progress. from (RestrictionTracker.java:189)
at org.apache.beam.fn.harness.FnApiDoFnRunner.scale Progress (FnApiDoFnRunner.java:1183) at org.apache.beam.fn.harness. FnApiDoFnRunner.getProgress (FnApiDoFnRunner.java:1157)
at org.apache.beam.fn.harness.FnApiDoFnRunner.access$1700 (FnApiDoFnRunner.java:145)
at org.apache.beam.fn.harness. FnApiDoFnRunner$SplittableFnDataReceiver.getProgress (FnApiDoFnRunner.java:1143)
at org.apache.beam.fn.harness.data.PCollectionConsumer Registry$SplittingMetricTrackingFnDataReceiver.getProgress (PCollection at org.apache.beam.fn.harness. BeamFnDataReadRunner.trySplit (BeamFnDataReadRunner.java:266)
at org.apache.beam.fn.harness.control. ProcessBundleHandler.trySplit (ProcessBundleHandler.java:728)
at org.apache.beam.fn.harness.control. BeamFnControlClient.delegateOnInstruction RequestType(BeamFnControlClient.java:151) at org.apache.beam.fn.harness.control. BeamFnControlClient$InboundObserver.lambda$onNext$0 (BeamFnControlClient.java:116)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

Since the input progress was constructed successfully and thus has positive fields it seems that windowCurrentIndex >= windowStopIndex must be true, causing the work remaining to be multipled by a negative value.  It seems this may be possible due to a race between windowCurrentIndex being incremented to windowStopIndex and the tracker/window being set to null preventing getProgress from running.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-java-harness

### PR DESCRIPTION
**Pull request by scwhittle**
Fixes #23881.
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by scwhittle** [comment]
R: @lukecwik

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java [hunk 1]
```diff
@@ -999,14 +1022,7 @@ public void onClaimFailed(PositionT position) {}
         }
       }
     } finally {
```
Comment (lukecwik) [inline sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:1024]: I don't think we need this finally block since the only way out is via the break statement.

Any exceptional return will lead to the bundle being failed and these DoFns being discarded.

Ditto for the other finally block.

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java [hunk 2]
```diff
@@ -972,6 +993,8 @@ private void processElementForWindowObservingTruncateRestriction(
         synchronized (splitLock) {
           windowCurrentIndex++;
           if (windowCurrentIndex >= windowStopIndex) {
+            // Careful to reset the split state under the same synchronized block.
+            resetSplitState();
             break;
```
Comment (lukecwik) [inline sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:998]: might as well and make this a return

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java [hunk 3]
```diff
@@ -1175,6 +1183,12 @@ private Progress getProgressFromWindowObservingTruncate(double elementCompleted)
 
   @VisibleForTesting
   static Progress scaleProgress(Progress progress, int currentWindowIndex, int stopWindowIndex) {
```
Comment (lukecwik) [inline sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:1185]: `Progress SplittableFnDataReceiver.getProgress()` should check to see if the current window is null just like `getProgressFromWindowObservingTruncate` does.

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java [hunk 4]
```diff
@@ -961,6 +967,21 @@ public void onClaimFailed(PositionT position) {}
     this.stateAccessor.finalizeState();
   }
 
+  private void resetSplitState() {
+    synchronized (splitLock) {
```
Comment (lukecwik) [inline sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:971]: I wouldn't make this a separate method since we are removing the finally blocks.

This would also prevent it from being called at an inappropriate time.

**Review by lukecwik — CHANGES_REQUESTED** [review]

**Comment by lukecwik** [comment]
Can we add a unit test to cover this?

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java (hunk 1 above)
Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:1024]: Is that guaranteed somewhere? I'm concerned that if things change so that the exception is caught that we've left this object in an invalid state.  We had a recent bug in state where the user was able to catch the exception and the invalid state was then used. I don't think that is possible here but is it possible that we add some generic exception handling (perhaps by configuration) and would rather clean up as we go here? Or is that unlikely in your opinion?

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java (hunk 2 above)
Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:998]: done

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java (hunk 1 above)
Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:1024]: Note that this finally structure is used throughout to reset after processing.  If you do think it should be done, should I update the other places in this file too?

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java (hunk 3 above)
Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:1185]: I thought hte check on tracker existence was sufficient but added window check too.

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java (hunk 4 above)
Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:971]: done

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java (hunk 1 above)
Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:1024]: Went ahead and updated the methods I changed, but left other finally blocks to cut down on timezone delays if that is the path desired.

**Comment by scwhittle** [comment]
I think this it would be difficult to reproduce the failure in a unit test because it depended on interleaving of synchronized blocks within the function with a split attempt.  Otherwise splitting in general already appears tested. Let me know if you have ideas on how to improve coverage.

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java (hunk 1 above)
Comment (lukecwik) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:1024]: I think you missed pushing out your latest version of this code.

In general your right that a DoFn could throw an exception which is caught by another DoFn further up the stack. This wouldn't apply to the SplittablDoFn since it is at the root of the stage for all runners so we are ok. There is also the problem were the SplittableDoFn itself throws an exception during processElement and it hasn't yet escaped the DoFn (whether that exception was caused during usage of the RestrictionTracker or something else). In this scenario we need to assume that the RestrictionTracker/WatermarkEstimatorState/DoFn state that getSize relies on isn't corrupted and a proper split can be returned. The only way I think we could resolve this completely is if we move the splitting logic to actually happen on the bundle processing thread by inserting points where we check if there is an outstanding split and process it but there is no time bound on how long we may have to wait before handling a split.

We can solve the DoFn exception propagation problem by ensuring that uncaught exceptions that escape a DoFn fail the bundle in the PCollectionConsumerRegistry and also plug this logic into places when the DoFn invokes system code that causes a terminal bundle failure (e.g. state gets corrupted). The issue comes down to whether we trust that the user is specifically handling the failure and choosing to continue or are they just blindly catching everything.

Comment (scwhittle) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java]: Oops, yes I didn't push.

If I understand correctly, in this particular case we are guaranteed that if an exception escapes it will fail because it is the root. So leaving the code as is.  Let me know if there is something else you'd like changed in this PR.

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java [hunk 5]
```diff
@@ -964,51 +970,48 @@ public void onClaimFailed(PositionT position) {}
...
+    windowStopIndex = currentElement.getWindows().size();
+    currentWindows = ImmutableList.copyOf(currentElement.getWindows());
+    while (true) {
+      synchronized (splitLock) {
+        windowCurrentIndex++;
+        if (windowCurrentIndex >= windowStopIndex) {
+          // Careful to reset the split state under the same synchronized block.
+          windowCurrentIndex = -1;
+          windowStopIndex = 0;
+          currentWindows = null;
```
Comment (lukecwik) [inline sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:983]:
```suggestion
          currentElement = null;
          currentWindows = null;
```

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java [hunk 6]
```diff
@@ -1058,72 +1061,68 @@ public static SplitResultsWithStopIndex of(
...
```
Comment (lukecwik) [inline sdks/java/harness/src/main/java/org/apache/beam/fn/harness/FnApiDoFnRunner.java:1074]:
```suggestion
          currentElement = null;
          currentWindows = null;
```

**Review by lukecwik — APPROVED** [review]
