### PR TITLE
Fix DoFnInvoker cache collision for generic types

### LINKED ISSUE #37351: [Bug]: ByteBuddyDoFnInvokerFactory cache collision for DoFns with different generic types
**What happened?**

I discovered a bug in ByteBuddyDoFnInvokerFactory where the cache key strategy causes collisions for the same DoFn class used with different generic types.

Currently, the cache is keyed solely on the DoFn class. This causes incorrect invoker reuse when generics are erased. For example, MyDoFn<String> and MyDoFn<Integer> share the same cache key (MyDoFn.class). As a result, the invoker generated for String is returned for Integer.

**Steps to reproduce**

I reproduced this behavior with the following unit test in DoFnInvokersTest.java. The test fails with an AssertionError, proving that the generated invoker classes are identical despite the different generic types.

Image

Image

### PR DESCRIPTION
**Pull request by Eliaaazzz**
This fixes a bug where ByteBuddyDoFnInvokerFactory would return the same cached invoker for different generic instantiations of the same DoFn class.

Changes:
1. Introduced InvokerCacheKey with TypeDescriptors to ensure unique cache entries.
2. Updated generateInvokerClass to append type-based hash suffix.
3. Added regression test (testCacheKeyCollisionProof).

Fixes #37351

## Description

This PR addresses a critical bug in the `ByteBuddyDoFnInvokerFactory` where the caching mechanism for generated `DoFnInvoker` classes failed to distinguish between different generic instantiations of the same `DoFn` class.

### 1. The Problem: Cache Collision on Generic Types
The previous implementation utilized a `ConcurrentHashMap<Class<?>, Constructor<?>>` to cache the generated invoker constructors. The cache key was solely the `DoFn` class itself.

In scenarios involving generic `DoFn` classes (e.g., `class MyGenericFn<T> extends DoFn<T, T>`), the raw class object is identical regardless of the type parameter `T`.

* **Scenario:** If a pipeline instantiates `MyGenericFn<String>` and later `MyGenericFn<Integer>`, the factory would generate an invoker for `String` and cache it.
* **The Bug:** When `MyGenericFn<Integer>` is requested, the factory hits the cache using the same `MyGenericFn.class` key and returns the `String`-specialized invoker.
* **Consequence:** This leads to runtime `ClassCastException` or incorrect `Coder` inference, as the bytecode for the invoker is specialized for the wrong type.

### 2. The Solution: Type-Aware Caching & Naming
This PR introduces a composite cache key and updates the class naming strategy to ensure full isolation between generic types.

#### A. Introduced `InvokerCacheKey`
I replaced the simple `Class<?>` key with a new static inner class `InvokerCacheKey`. This key encapsulates three components:
1.  **`fnClass`**: The raw class of the DoFn.
2.  **`inputType`**: The `TypeDescriptor` for the input element.
3.  **`outputType`**: The `TypeDescriptor` for the output element.

By implementing `equals()` and `hashCode()` based on all three fields, we ensure that `MyGenericFn<String>` and `MyGenericFn<Integer>` map to distinct cache entries.

#### B. Unique Class Naming Strategy
ByteBuddy cannot define two different classes with the exact same name in the same `ClassLoader`. To support multiple generated invokers for the same raw `DoFn` class, I modified `generateInvokerClass`.

* **Old Strategy:** `<DoFnClassName>$DoFnInvoker`
* **New Strategy:** `<DoFnClassName>$DoFnInvoker$<TypeHash>`

The suffix now includes a hexadecimal hash derived from the input and output `TypeDescriptors`. This guarantees that the generated bytecode class names are unique for each generic instantiation.

## Test Plan

I have added a regression test `testCacheKeyCollisionProof` to `DoFnInvokersTest.java`.

* **Methodology:** The test defines a local generic class `DynamicTypeDoFn<T>` and manually forces specific `TypeDescriptor` returns.
* **Verification:** It instantiates the DoFn twice (once for `String`, once for `Integer`) and asserts that the generated Invoker classes are **not** the same (`assertNotSame`).
* **Result:** The test passes with the fix (confirming distinct invokers are generated) and fails without it.

**Existing tests passed:**
* `DoFnInvokersTest`

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java [hunk 1]
```diff
@@ -166,15 +166,67 @@ public <InputT, OutputT> DoFnInvoker<InputT, OutputT> invokerFor(DoFn<InputT, Ou
...
+      }
+      InvokerCacheKey that = (InvokerCacheKey) o;
+      return fnClass.equals(that.fnClass)
+          && inputType.equals(that.inputType)
+          && outputType.equals(that.outputType);
+    }
+
+    @Override
+    public int hashCode() {
+      int result = fnClass.hashCode();
```
Comment (kennknowles) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java]: I suggest using `Objects.hash(fnClass, inputType, outputType)` along with `Objects.equals` which makes it very easy to maintain consistency and clarity.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java [hunk 2]
```diff
@@ -166,15 +166,67 @@ public <InputT, OutputT> DoFnInvoker<InputT, OutputT> invokerFor(DoFn<InputT, Ou
...
+      result = 31 * result + inputType.hashCode();
+      result = 31 * result + outputType.hashCode();
+      return result;
+    }
+
+    @Override
+    public String toString() {
+      return String.format(
```
Comment (kennknowles) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java]: Here using `ToStringHelper` keeps a consistent format across all our classes.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java [hunk 3]
```diff
@@ -265,11 +317,38 @@ public <InputT, OutputT> DoFnInvoker<InputT, OutputT> newByteBuddyInvoker(
...
         fn.getClass());
 
+    // Extract input and output type descriptors from the DoFn instance
+    // Fall back to Object.class if the type descriptors are null or unavailable (e.g., MapElements
+    // after serialization)
+    TypeDescriptor<InputT> inputType;
+    try {
+      inputType = fn.getInputTypeDescriptor();
+    } catch (Exception e) {
+      // Some DoFns (like MapElements) throw IllegalStateException if queried after
```
Comment (kennknowles) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/reflect/ByteBuddyDoFnInvokerFactory.java:329]: I'm interested in digging in to this. Will we still have cache collision problems in this case?

File: sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/DoFnInvokersTest.java [hunk 4]
```diff
@@ -1382,11 +1385,18 @@ public void process() {}
   @Test
   public void testStableName() {
     DoFnInvoker<Void, Void> invoker = DoFnInvokers.invokerFor(new StableNameTestDoFn());
+    // The invoker class name includes a hash of the type descriptors to support
+    // different generic instantiations of the same DoFn class.
+    // Format: <DoFn class name>$<DoFnInvoker>$<type hash>
+    TypeDescriptor<Void> voidType = new StableNameTestDoFn().getInputTypeDescriptor();
+    String expectedTypeSuffix =
```
Comment (kennknowles) [inline sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/DoFnInvokersTest.java]: Rather than repeat the logic of producing this esoteric suffix, go ahead and make it a package-private, or even public method. (the whole module should be `@Internal` so public methods are not frozen APIs)

Comment (Eliaaazzz) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/transforms/reflect/DoFnInvokersTest.java]: @kennknowles Thanks for the review! I have updated the code to use ToStringHelper and Objects.hash as suggested, and extracted the suffix logic to clean up the tests.

Regarding the cache collision in the fallback case:

You are exactly right—if type lookup fails, different generic instantiations like MyDoFn<String> and MyDoFn<Integer> will map to the same CacheKey.

However, it's important to highlight that type lookup failure is often an objective side effect of deserialization in a distributed environment. When a DoFn is serialized and transmitted across workers, specific generic type information can be lost due to Java's type erasure or classloader limitations on the worker side. This is an inherent constraint we must handle.

This collision is safe and intentional for two reasons:

Class Isolation: The cache key still includes fnClass, so different DoFn implementations will never share an invoker.

Erasure Compatibility: When we fall back to Object, we generate a "Raw Invoker". Due to Java type erasure, the underlying method in the bytecode acts as processElement(Object). Thus, a single shared "Raw Invoker" is perfectly compatible with any generic instantiation of that class.

I have added a comment in the catch block to explicitly mention that this fallback is a resilient design for cases where type information is lost during deserialization, ensuring the system remains functional even when reflection is limited.

**Comment by kennknowles** [comment]
R: @kennknowles 
(just to settle the bot down)

**Review by kennknowles — APPROVED** [review]
This seems good to me. Considering your explanation... I wonder if always generated a "raw invoker" is a fine way to go anyhow. Because this is intended as just automatically generated glue code, and it will always execute the same anyhow...

Since this touches every single pipeline, I think we'll want to run a lot of testing. There are bunch of "trigger files" in the `.github/trigger_files` directory where if you touch them it will run additional suites. I'm not sure exactly which are best, but hitting some of the `ValidatesRunner` and `PostCommit` tests will run a number of distributed tests that may be worthwhile.

**Comment by Eliaaazzz** [comment]
> This seems good to me. Considering your explanation... I wonder if always generated a "raw invoker" is a fine way to go anyhow. Because this is intended as just automatically generated glue code, and it will always execute the same anyhow...
> 
> Since this touches every single pipeline, I think we'll want to run a lot of testing. There are bunch of "trigger files" in the `.github/trigger_files` directory where if you touch them it will run additional suites. I'm not sure exactly which are best, but hitting some of the `ValidatesRunner` and `PostCommit` tests will run a number of distributed tests that may be worthwhile.

Thanks Kenn! Since this touches every pipeline, I’ll trigger additional ValidatesRunner/PostCommit suites via .github/trigger_files and report the results here.

**Comment by kennknowles** [comment]
OK looks pretty good to me. That's a lot of tests. I'll merge it and we'll get some test feedback from all the rest of the post-commit testing.

**Comment by Eliaaazzz** [comment]
> OK looks pretty good to me. That's a lot of tests. I'll merge it and we'll get some test feedback from all the rest of the post-commit testing.

Thanks for the review and the merge, Kenn! Glad to hear the tests were helpful. I will keep a close eye on the post-commit test results and jump on any fixes if needed. Really appreciate your guidance on this PR. Fingers crossed for the post-commit tests! 🤞
