### PR TITLE
(fix #34038) Use CivilTimeEncoder to encode Time values in AvroGenericRecordToStorageApiProto

### LINKED ISSUE #34038: [Bug]: Inconsistent written values for LocalTime types using BQ FileLoads vs StorageWrite API
### What happened?

On beam 2.63.0, when writing GenericRecords to BQ using `time-millis` logical types over the Java SDK, a different value is written depending on whether I use `STORAGE_WRITE_API` method or `FILE_LOADS` method.

Repro setup (sorry for Scio code, will work on reproducing in a Beam as well):

```scala
object BqWriteTest {

  val AvroSchema = new Schema.Parser().parse(
    s"""
       |{
       |  "type": "record",
       |  "namespace": "com.spotify.scio.extra.bigquery",
       |  "name": "AvroExampleWithLogicalType",
       |  "fields": [
       |    {"name": "timeMillisField", "type": { "type": "int", "logicalType": "time-millis"}},
       |    {"name": "timeMicrosField", "type": { "type": "long", "logicalType": "time-micros"}}
       |  ]
       |}
       |""".stripMargin
  )

  val TableSchema = new TableSchema().setFields(
    List(
      new TableFieldSchema().setName("timeMillisField").setType("TIME").setMode("REQUIRED"),
      new TableFieldSchema().setName("timeMicrosField").setType("TIME").setMode("REQUIRED")
    ).asJava
  )

  val TestRecord: GenericRecord = new GenericRecordBuilder(AvroSchema)
    .set(
      "timeMillisField",
      new TimeMillisConversion().toInt(java.time.LocalTime.of(6, 30, 10, 0), AvroSchema, LogicalTypes.timeMillis()))
    .set(
      "timeMicrosField",
      new TimeMicrosConversion().toLong(java.time.LocalTime.of(6, 30, 10, 0), AvroSchema, LogicalTypes.timeMicros()))
    .build()

  def main(cmdLineArgs: Array[String]): Unit = {
    val (sc, args) = ContextAndArgs(cmdLineArgs)

    implicit val coder: Coder[GenericRecord] = avroGenericRecordCoder(AvroSchema)

    val records = sc.parallelize(Seq(TestRecord))

    // Save to BQ using Storage Write
    records.saveAsCustomOutput(
        "Write to BQ using Storage Write API",
        org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO
          .write[GenericRecord]()
          .to(s"$project:$dataset.test_bq_file_loads_api")
          .withCreateDisposition(CreateDisposition.CREATE_IF_NEEDED)
          .useAvroLogicalTypes()
          .withSchema(TableSchema)
          .withAvroFormatFunction(Functions.serializableFn(_.getElement))
          .withAvroSchemaFactory(Functions.serializableFn(BigQueryUtils.toGenericAvroSchema(_, true)))
          .withMethod(org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO.Write.Method.FILE_LOADS)
      )

    // Save to BQ using File Loads
    records.saveAsCustomOutput(
        "Write to BQ using Storage Write API",
        org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO
          .write[GenericRecord]()
          .to(s"$project:$dataset.test_bq_storage_write_api")
          .withCreateDisposition(CreateDisposition.CREATE_IF_NEEDED)
          .useAvroLogicalTypes()
          .withSchema(TableSchema)
          .withAvroFormatFunction(Functions.serializableFn(_.getElement))
          .withAvroSchemaFactory(Functions.serializableFn(BigQueryUtils.toGenericAvroSchema(_, true)))
          .withMethod(org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO.Write.Method.STORAGE_WRITE_API)
      )

    sc.run()
  }
} 
``` 

The time-millis value for the table written using FILE_LOADS does not match the value written using STORAGE_WRITE_API:

storage_write_api data:
Image

file_loads data:
Image

Tbh, the only value that looks correct is the file-loads micros value 😬 I'm extremely concerned about this as potentially incorrect data is being written using BQ's Avro interface.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [x] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by clairemcginty**
I noticed that in Beam 2.63, TIME types were being encoded incorrectly when using the Storage Write API. For example, I'd try to write a value of 6:30 and it would get written to BQ as 5:28. See #34038.

I looked at what the other *ToStorageApiProto classes were doing ([TableRowToStorageApiProto](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java), [BeamRowToStorageApiProto](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BeamRowToStorageApiProto.java)) and noticed they were using this `CivilTimeEncoder` class to translate TIME types to Longs, whereas `AvroGenericRecordToStorageApiProto` was trying to compute manually from milliseconds/microseconds of day. It's a small difference but it accounts for the BQ discrepancies.

I've tested this out locally when writing to BQ and the values look correct now, but I would definitely appreciate someone with more domain knowledge checking in! Also, looks should maybe be using this encoder for DATETIME types, too?

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProtoTest.java [hunk 1]
```diff
@@ -456,8 +464,8 @@ enum TestEnum {
               .put("numericvalue", numericBytes)
               .put("bignumericvalue", bigNumericBytes)
               .put("datevalue", 42)
-              .put("timemicrosvalue", 42_000_000L)
-              .put("timemillisvalue", 42_000_000L)
+              .put("timemicrosvalue", CivilTimeEncoder.encodePacked64TimeMicros(localTime))
```
Comment (clairemcginty) [inline sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/AvroGenericRecordToStorageApiProtoTest.java:467]: I was curious so I checked the difference here. CivilTimeEncoder translates this value to `44,040,192` compared to the original `42,000,000`.

**Comment by Abacn** [comment]
Thanks for the fix! Could you please run './gradlew :sdks:java:io:google-cloud-platform:spotlessApply' then push a new commit to format code?

**Comment by clairemcginty** [comment]
ah forgot to mention, the format violations seemed to be in an unrelated file, but it looks like they were just fixed [here](https://github.com/apache/beam/pull/34092/commits/b7a4d72eb555d828a92a993d88647951a148e8be). Just rebased my PR!

**Review by Abacn — APPROVED** [review]
