### PR TITLE
Fix PostCommit Java PVR Spark3 Streaming job

### LINKED ISSUE #34207: The PostCommit Java PVR Spark3 Streaming job is flaky
The PostCommit Java PVR Spark3 Streaming is failing over 50% of the time.
Please visit https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_PVR_Spark3_Streaming.yml?query=is%3Afailure+branch%3Amaster to see all failed workflow runs.
See also Grafana statistics: http://metrics.beam.apache.org/d/CTYdoxP4z/ga-post-commits-status?orgId=1&viewPanel=5&var-Workflow=PostCommit%20Java%20PVR%20Spark3%20Streaming

### PR DESCRIPTION
**Pull request by Amar3tto**
Fixes #34207.
For Spark 3, the behavior that was before #34080 has been reverted.

Successful run: https://github.com/Amar3tto/beam/actions/runs/13794580478

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
R: @Abacn

**Comment by Abacn** [comment]
CC: @twosom

File: runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java [hunk 1]
```diff
@@ -322,13 +342,21 @@ private static <T> void translateFlatten(
...
-                  context.getStreamingContext().ssc(), ((BoundedDataset) dataset).getRDD().rdd());
-          final JavaDStream<WindowedValue<T>> dStream =
-              JavaDStream.fromDStream(
-                  singleEmitInputDStream, JavaSparkContext$.MODULE$.fakeClassTag());
-
+          JavaDStream<WindowedValue<T>> dStream;
+          if (context.getSparkContext().version().startsWith("3")) {
+            Queue<JavaRDD<WindowedValue<T>>> q = new LinkedBlockingQueue<>();
+            q.offer(((BoundedDataset) dataset).getRDD());
+            // TODO (https://github.com/apache/beam/issues/20426): this is not recoverable from
```
Comment (Abacn) [inline runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java:349]: This adds back a previously closed issue #20426 that  #34080 intended to solve. To what extent #34080 still functioning, or shall we revert it as a whole?

Comment (Amar3tto) [reply runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java:349]: #34080 should still work for Spark 2. I guess that PR was made and tested only for Spark 2.
Spark 3 test was failing, so my PR should fix it.

Comment (twosom) [reply runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java:349]: Hello. I am currently reviewing the issue.

At the time of submitting the PR, the following trigger files were used, but it seems that `PortableRunner` was not included, which is likely why the issue was not detected:
- `beam_PostCommit_Java_ValidatesRunner_Spark.json`
- `beam_PostCommit_Java_ValidatesRunner_Spark_Java11.json`
- `beam_PostCommit_Java_ValidatesRunner_SparkStructuredStreaming.json`

I agree with @Amar3tto's suggestion. For now, it seems we need to roll back the changes related to the `PortableRunner` and revisit the task afterward.

Comment (twosom) [reply runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java:349]: I should have been more thorough when working on the PR, and I sincerely apologize for not doing so. I would also like to express my gratitude to @Amar3tto for their support and assistance.

Comment (Amar3tto) [reply runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java:349]: I just saw that Spark 3 actually is a primary version. So I will just rollback changes related to the PortableRunner (without checking Spark version).

Comment (twosom) [reply runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java:349]: Thank you.

I will make it a priority to revisit and proceed with the PortableRunner-related tasks associated with #20426 as soon as possible.

Comment (Abacn) [reply runners/spark/src/main/java/org/apache/beam/runners/spark/translation/SparkStreamingPortablePipelineTranslator.java]: Thanks, let me merge this and reopen #20426

**Review by Abacn — APPROVED** [review]
