### PR TITLE
Fix RowCoderGenerator to use the encodingPositions when encoding and decoding the bit set representing null fields.

### LINKED ISSUE #32388: [Bug]: Java generated RowCoder doesn't use encodingPositions when encoding/decoding the null set
### What happened?

Runners can ensure compatibility across multiple jobs runs of encoded schemas via encoding positions. Dataflow runner in particular sets encoding position overrides to maintain compatibility across pipelines. 

[RowCoderGenerator](https://github.com/apache/beam/blob/64b4aa6fdde6a65b8157578036374623a47c18c2/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java#L139) utilizes these to map encoded index to the current Row representation.  However it neglects to do so for writing the null bit set [here](https://github.com/apache/beam/blob/64b4aa6fdde6a65b8157578036374623a47c18c2/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java#L355) and when reading the null bit set [here](https://github.com/apache/beam/blob/64b4aa6fdde6a65b8157578036374623a47c18c2/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java#L428)

This leads to corruption when reading with encodedPositionOverrides that do not match the field ordering and additionally corrupts state when writing the null bit set based upon field ordering instead of encoding position.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by scwhittle**
Add tests that fail without the change covering encoding and decoding

Also add tests that cover the static position overrides which was not tested previously.

Some other cleanup to help debug other possible encoding positions issues in the future:
- ensure that only a single RowCoder is created for a given UUID by using synchronization when generating coders
- add some logging if encoding position overrides arrive after a RowCoder has already been generated for the UUID

fixes #32388 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by scwhittle** [comment]
R:  @reuvenlax

**Comment by scwhittle** [comment]
Also added internal dataflow tests verifying that this fixes update with reordered schemas with null fields.

**Comment by scwhittle** [comment]
@Abacn @reuvenlax friendly ping

File: sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java [hunk 1]
```diff
@@ -425,7 +538,7 @@ static Row decodeDelegate(
         // in which case we drop the extra fields.
         if (encodingPos < coders.length) {
           int rowIndex = encodingPosToIndex[encodingPos];
-          if (nullFields.get(rowIndex)) {
+          if (nullFields.get(encodingPos)) {
```
Comment (Abacn) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java:541]: was this a bug? rowIndex and encodingPos looks different

**Review by Abacn — COMMENTED** [review]
thanks, left a few questions

File: sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java [hunk 2]
```diff
@@ -109,30 +113,121 @@ public abstract class RowCoderGenerator {
...
+              previousEncodingPositions.getStackTrace(),
+              stackTrace);
+        }
+      }
+    }
+  }
+
+  @VisibleForTesting
+  static void clearRowCoderCache() {
+    synchronized (setOverridesLock) {
```
[the remark this answers is not in the document]
Comment (scwhittle) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java:198]: Coders can be read without the synchronized block but are written with the extra synchronization because concurrenthashmap updateifnotpresent is not reentrant (unlike synchronized) and the get/insert pattern is possibly racy.

That said I since the read coders are cached, I think I will just change to regular maps under synchronization and ditch the concurrenthashmap.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java (hunk 1 above)
Comment (scwhittle) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java:541]: Yes this along with other nullfields fix above is the purpose of this PR to fix #32388 .
The stack trace and synchronization changes were added as the initial belief was that encoded corruption was due to late overrides arriving.  Since that could still be an issue, I think we should keep those changes but I can separate them to a separate PR if you'd prefer.

Comment (scwhittle) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java:541]: Note that unless there are encoding overrides rowIndex and encodingPos are equal. But the improved unit tests catch the issue, previous tests with encoding overrides didn't have null fields and thus missed it.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java [hunk 3]
```diff
@@ -109,30 +113,121 @@ public abstract class RowCoderGenerator {
...
+      @Nullable
+      WithStackTrace<Map<String, Integer>> previousEncodingPositions =
+          ENCODING_POSITION_OVERRIDES.put(
+              uuid, new WithStackTrace<>(encodingPositions, stackTrace));
+      @Nullable WithStackTrace<Coder<Row>> existingCoder = GENERATED_CODERS.get(uuid);
+      if (previousEncodingPositions == null) {
+        if (existingCoder != null) {
+          LOG.error(
+              "Received encoding positions for uuid {} too late after creating RowCoder. Created: {}\n Override: {}",
```
[the remark this answers is not in the document]
Comment (scwhittle) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/coders/RowCoderGenerator.java:162]: Thanks! done

**Review by Abacn — APPROVED** [review]
thank you!
