### PR TITLE
[IcebergIO] Fix conversion logic for arrays of structs and maps of structs; fix output Schema resolution with column pruning

### LINKED ISSUE #34887: [Bug]: Iceberg record conversion utils do not handle collections of structs correctly
### What happened?

Our conversion logic needs to be more nuanced for collection types (i.e. Arrays, Iterables, Maps)

Beam to Iceberg:
https://github.com/apache/beam/blob/5b862dd510b36ed807414461432749b37eb269b8/sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java#L430-L434

Iceberg to Beam: 
https://github.com/apache/beam/blob/5b862dd510b36ed807414461432749b37eb269b8/sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java#L348-L353

We need to inspect the collection type and recurse if it's a struct.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [x] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### LINKED ISSUE #35199: [Bug]: IcebergIO fails to convert an array of structs
### What happened?

Error:
```
Exception in thread "main" java.lang.ClassCastException: class
org.apache.iceberg.data.GenericRecord cannot be cast to class
org.apache.beam.sdk.values.Row (org.apache.iceberg.data.GenericRecord and
org.apache.beam.sdk.values.Row are in unnamed module of loader 'app')
```

Patch attached.

[iceberg_array_struct.patch](https://github.com/user-attachments/files/20639565/iceberg_array_struct.patch)

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by ahmedabu98**
This includes two separate fixes, outlined below. For the sake of time, I just put them in the same PR, but I can split them into separate PRs if necessary.

1. Fix conversion logic for lists of structs and maps of structs
2. Fix output schema resolution when using column pruning

Fixes #34887
Fixes #35199

### CODE REVIEW

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java [hunk 1]
```diff
@@ -72,6 +74,56 @@ class FilterUtils {
...
+    if (filter == null || filter.trim().isEmpty()) {
+      return new HashSet<>();
+    }
+
+    SqlParser parser = SqlParser.create(filter);
+    try {
+      SqlNode expression = parser.parseExpression();
+      Set<String> fieldNames = new HashSet<>();
+      extractFieldNames(expression, fieldNames);
+      System.out.println("xxx fields in filter: " + fieldNames);
```
Comment (chamikaramj) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java]: Pls delete debug line.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java [hunk 2]
```diff
@@ -72,6 +74,56 @@ class FilterUtils {
...
+    } else if (node instanceof SqlNodeList) {
+      // For IN clauses, the right-hand side is a SqlNodeList, so iterate through its elements
+      SqlNodeList nodeList = (SqlNodeList) node;
+      for (SqlNode element : nodeList.getList()) {
+        if (element != null) {
+          extractFieldNames(element, fieldNames);
+        }
+      }
+    }
+    // SqlLiteral nodes do not contain field names, so we can ignore them.
```
Comment (chamikaramj) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java:116]: Pass through for other types is intentional ?

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java [hunk 3]
```diff
@@ -426,10 +454,49 @@ public static Row icebergRecordToBeamRow(Schema schema, Record record) {
         case DOUBLE: // Iceberg and Beam both use double
         case STRING: // Iceberg and Beam both use String
         case BOOLEAN: // Iceberg and Beam both use boolean
+          rowBuilder.addValue(icebergValue);
+          break;
         case ARRAY:
         case ITERABLE:
+          checkState(
+              icebergValue instanceof List,
```
Comment (chamikaramj) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:462]: Does ITERABLE type always imply List here ?

**Review by chamikaramj — COMMENTED** [review]
Thanks. LGTM.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java (hunk 1 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java]: Done

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java (hunk 2 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/FilterUtils.java:116]: Yep, not all SqlNodes will contain a field name

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java (hunk 3 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:462]: Good catch, made a separate logic block for Iterable.

Going the other way around, Iceberg only has a single "List" type. I widened the logic so that it can work with Iterables as well though.

**Comment by ahmedabu98** [comment]
Merging when tests go green

**Comment by ahmedabu98** [comment]
Failing Java Precommit test is unrelated (#35233)
