### PR TITLE
[RRIO] [Test] Create test Caller and SetupTeardown

### LINKED ISSUE #28710: [Task]: [RRIO] [Test] Create test Caller and SetupTeardown interface implementations
### What needs to happen?

The output of this task are definitions and implementations of the Caller and SetupTeardown interfaces:

```java
interface Caller<RequestT, ResponseT, ApiErrorT extends ApiException> extends Serializable {
    ResponseT call(RequestT request) throws ApiErrorT;
}

interface SetupTeardown<ErrorT extends Exception> extends Serializable {
	void setup() extends ErrorT;
	void teardown() extends ErrorT;
}
```

Test implementations of `Caller` and `SetupTeardown` call the quota aware endpoint built and deployed from #28708 and #28709. Additionally, configurable mock implementations mimic response and error scenarios to supporting unit testing.

# Measures of Ready

Work on this task depends on:
- #28708
- #28709

# Measures of Done

This task is considered done when:

- [x] Caller and SetupTeardown interfaces exist in the RRIO project
- [x] Test implementations successfully call the deployed mock quota aware endpoint

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### PR DESCRIPTION
**Pull request by damondouglas**
This PR closes #28710 by implementing a test implementation of Caller and SetupTeardown for the [mock-api](https://github.com/apache/beam/tree/master/.test-infra/mock-apis) endpoint.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by damondouglas** [comment]
assign set of reviewers

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java [hunk 1]
```diff
@@ -0,0 +1,113 @@
...
+
+    // Quota allocation needs at least 1 so we invoke a few times to guarantee exceeding quota.
+    // We only throw exceptions that are not UserCodeQuotaException.
+    try {
+      EchoResponse ignored = client.call(request);
+      client.call(request);
+      client.call(request);
+      client.call(request);
+    } catch (UserCodeExecutionException ignored) {
+    }
```
Comment (bvolpato) [inline sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java:69]: It feels like it's part of some initialization, but feels like we're testing some behavior here. Let's make sure that this is covered (with assertions) somewhere else

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+        assertThrows(
+            UserCodeExecutionException.class,
+            () ->
+                client.call(
+                    EchoRequest.newBuilder()
+                        .setId("i-dont-exist-quota-id")
+                        .setPayload(PAYLOAD)
+                        .build()));
+
+    assertTrue(error.getMessage().contains("404 Not Found"));
```
Comment (bvolpato) [inline sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java:97]: Just curious if we have/can use something like Mockito?

We could use more idiomatic tests, for example 
```
assertThat(error.getMessage(), containsString("404 Not Found"));
```

It looks like the test is the same, but failure reports would be (just an example):

> String is 429 Too Many Requests, expected to contain 404 Not Found

Instead of:

> Expected true is false

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoITOptions.java [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+ * <pre>
+ *   ./gradlew :sdks:java:io:rrio:integrationTest -DintegrationTestPipelineOptions='[
+ *      "--grpcEndpointAddress=",
+ *      "--httpEndpointAddress="
+ *   ]'
+ * </pre>
+ */
+public interface EchoITOptions extends PipelineOptions {
+  @Description("The gRPC address of the Echo API endpoint, typically of the form <host>:<port>.")
+  String getgRPCEndpointAddress();
```
Comment (bvolpato) [inline sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoITOptions.java:41]: Can you test this explicitly to make sure this works as intended?

It feels to me that it should be `getGRPCEndpointAddress` to follow Java conventions, but I am not sure if the PipelineOptions is case sensitive.

**Review by bvolpato — APPROVED** [review]
Thanks! Good work Damon. I left a few nit comments, but in general it LGTM

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java (hunk 1 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java:69]: @bvolpato Thank you for catching this. The challenge with building and deploying a real quota aware endpoint, the integration with which these tests validate, is that we need a value of at least 1. The allocated quota where we expect to exceed will be shared among many tests and across languages. This setup insures that the API is in the state where we can expect a quota exceeded error. There are tests in this file that detect errors in expected responses. I will update the comments with this prior explanation and resolve this comment. However, please re-open if you feel strongly that some further change is warranted.

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java (hunk 2 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java:97]: > Just curious if we have/can use something like Mockito?
There are mocking tests in a separate PR that are validating catching specific errors and mock the Caller and SetupTeardown interfaces for this purpose. Tests in this PR validate the integration of the Caller and SetupTeardown implementation and a real API built and deployed in a cloud environment.

Comment (damondouglas) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java:97]: > We could use more idiomatic tests

I agree. I will change the PR to follow this.

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoITOptions.java (hunk 3 above)
Comment (damondouglas) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoITOptions.java:41]: I experimented with `getGRPCEndpointAddress` and it is case sensitive.  Setting as `getgRPCEndpointAddress` allows the flag to look like this: `--gRPCEndpointAddress`. Using `getGRPCEndpointAddress` looks like this: `--GRPCEndpointAddress`. Given the canonical name is with the little 'g', I opted for `getgRPCEndpointAddress`.

Comment (damondouglas) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoITOptions.java:41]: I will go ahead and resolve this but please re-open if you feel more discussion is warranted. Thank you, again for reviewing!

**Comment by damondouglas** [comment]
Run Java PreCommit

File: sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java (hunk 2 above)
Comment (bvolpato) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java:104]: Sorry, I meant Hamcrest instead of Mockito.

Comment (damondouglas) [reply sdks/java/io/rrio/src/test/java/org/apache/beam/io/requestresponse/EchoHTTPCallerTestIT.java:104]: I agree. Hamcrest seems much more readable. I will change over to using that. Thank you, Bruno.

**Review by bvolpato — APPROVED** [review]
