### PR TITLE
Retry transient NOT_FOUND on Storage API default stream

### LINKED ISSUE #33909: The PreCommit Java GCP IO Direct job is flaky
The PreCommit Java GCP IO Direct is failing over 50% of the time.
Please visit https://github.com/apache/beam/actions/workflows/beam_PreCommit_Java_GCP_IO_Direct.yml?query=is%3Afailure+branch%3Amaster to see all failed workflow runs.
See also Grafana statistics: http://metrics.beam.apache.org/d/CTYdoxP4z/ga-post-commits-status?orgId=1&viewPanel=3&var-Workflow=PreCommit%20Java%20GCP%20IO%20Direct

### PR DESCRIPTION
**Pull request by aIbrahiim**
Fixes: #33909 
Successful run: https://github.com/aIbrahiim/beam/actions/runs/24193545140
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by aIbrahiim** [comment]
assign set of reviewers

**Comment by Abacn** [comment]
iirc BigQuery tables always have a default string. If it's returning NOT_FOUND means this table hasn't been created. @ahmedabu98 is this the case?

```
testSchemaMismatchCaughtByBeam[1] (org.apache.beam.sdk.io.gcp.bigquery.StorageApiSinkFailedRowsIT) failed

sdks/java/io/google-cloud-platform/build/test-results/integrationTest/TEST-org.apache.beam.sdk.io.gcp.bigquery.StorageApiSinkFailedRowsIT.xml [took 1s]

org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.RuntimeException: Append to stream projects/apache-beam-testing/datasets/storage_api_sink_failed_rows35832459530128/tables/table35868362116490/streams/_default failed with Status Code NOT_FOUND. The stream may not exist.
	at app//org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:382)
	at app//org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:350)
```

Example failure:

https://github.com/apache/beam/runs/70458732203

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java [hunk 1]
```diff
@@ -850,7 +850,7 @@ long flush(
               boolean hasPersistentErrors =
                   failedContext.getError() instanceof Exceptions.StreamFinalizedException
                       || statusCode.equals(Status.Code.INVALID_ARGUMENT)
-                      || statusCode.equals(Status.Code.NOT_FOUND)
+                      || (!this.useDefaultStream && statusCode.equals(Status.Code.NOT_FOUND))
```
Comment (damccorm) [inline sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java:853]: Why is it not a persistent error if the default stream is not found? Where are you seeing this issue?

Comment (aIbrahiim) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java:853]: yeah I'm seeing it in StorageApiSinkFailedRowsIT.testSchemaMismatchCaughtByBeam[1] (AT_LEAST_ONCE/default stream path). In the failing logs, createNewTable succeeds, then append to .../streams/_default immediately returns NOT_FOUND for that same table, which lookd like a transient storage API visibility race rather than a permanently missing stream so the intent here is to retry NOT_FOUND for default stream only and keep it persistent for non default streams and also I noticed the current snippet has duplicated NOT_FOUND checks, and the unconditional one should be removed

**Review by Abacn — APPROVED** [review]
Thanks, we can merge this and see if it fixes https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_DataflowV1.yml?query=event%3Aschedule
