### PR TITLE
[#29760] Only respond to sampling request while data sampling is enabled

### LINKED ISSUE #29760: [Bug]: Go SDK Dataflow jobs fail on DataSampling disabled
### What happened?

Dataflow is making DataSampling FnAPI requests even when DataSampling is disabled. But since the feature wasn't enabled, the Go SDK isn't initialzing the datasampler, leading to nil pointer panic.

```
2023-12-08 16:28:11.597 PST
panic({0x1264220?, 0x2786ff0?}) 
2023-12-08 16:28:11.597 PST
	runtime/panic.go:914 +0x21f 
2023-12-08 16:28:11.597 PST
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/exec.(*DataSampler).getAllSamples(0x0) 
2023-12-08 16:28:11.597 PST
	github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/exec/datasampler.go:79 +0x4b 
2023-12-08 16:28:11.597 PST
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/exec.(*DataSampler).GetSamples(0x1312c00?, {0x0?, 0xc000234480?, 0xc00053b508?}) 
2023-12-08 16:28:11.597 PST
	github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/exec/datasampler.go:62 +0x1d 
2023-12-08 16:28:11.597 PST
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/harness.(*control).handleInstruction(0xc000318000, {0x180beb0?, 0xc000091c80?}, 0xc000147ef0) 
2023-12-08 16:28:11.597 PST
	github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/harness/harness.go:668 +0x116f 
2023-12-08 16:28:11.597 PST
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/harness.MainWithOptions.func4({0x180beb0?, 0xc000091c80?}, 0xc000091c80?) 
2023-12-08 16:28:11.597 PST
	github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/harness/harness.go:202 +0x74 
2023-12-08 16:28:11.597 PST
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/harness.MainWithOptions({0x180beb0, 0xc000091c20}, {0x7fffd16304e4, 0xf}, {0x7fffd1630507, 0xf}, {{0xc000225e70, 0x1, 0x1}, {0xc000046010, ...}}) 
2023-12-08 16:28:11.597 PST
	github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/harness/harness.go:222 +0x1022 
2023-12-08 16:28:11.597 PST
github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/harness/init.hook() 
2023-12-08 16:28:11.597 PST
	github.com/apache/beam/sdks/v2/go/pkg/beam/core/runtime/harness/init/init.go:144 +0x50c 
```

Easy enough fix, not caught sooner because we didn't run the Dataflow Go Postcommits. 

First: Fix the issue, and cherry pick it into 2.53.0
Second: While this is very unlikely, this would have been caught by a simple Dataflow Go Wordcount test as a pre-commit. I'll add that.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by zechenj18**
Fix to panic caused by handling data sampling request when it's not enabled.

Fixes #29760

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by lostluck** [comment]
Run Go PostCommit

File: sdks/go/pkg/beam/core/runtime/harness/harness.go [hunk 1]
```diff
@@ -662,7 +662,7 @@ func (c *control) handleInstruction(ctx context.Context, req *fnpb.InstructionRe
 				},
 			},
 		}
-	case req.GetSampleData() != nil:
+	case req.GetSampleData() != nil && c.dataSampler != nil:
```
Comment (lostluck) [inline sdks/go/pkg/beam/core/runtime/harness/harness.go:665]: This isn't an ideal fix. 

As much as the Runner shouldn't be sending sample requests, this sends "fail" response back to the Runner, which may abort job processing depending on the runner.

It would be better to send "empty" responses with no sampleData in this case instead. 
```
if c.dataSampler != nil {
	return &fnpb.InstructionResponse{
			InstructionId: string(instID),
			Response: &fnpb.InstructionResponse_SampleData{},
		}
}
```

Comment (lostluck) [reply sdks/go/pkg/beam/core/runtime/harness/harness.go:665]: Basically, yes, Dataflow is incorrect to be sending these requests, however, the SDK shouldn't send responses that might cause the job to fail.

**Comment by lostluck** [comment]
"Run Go PostCommit"

File: sdks/go/pkg/beam/core/runtime/harness/harness.go (hunk 1 above)
Comment (zechenj18) [reply sdks/go/pkg/beam/core/runtime/harness/harness.go]: Updated with empty response when data sampling is not enabled.

**Comment by lostluck** [comment]
Run Go PostCommit

**Review by lostluck — APPROVED** [review]
LGTM. I'll merge in once I validate the postcommit.

**Comment by lostluck** [comment]
Apparently PostCommit trigger phrases are currently too expensive (fair), so a work around is to add a file to the PR. (The one listed here: https://github.com/apache/beam/blob/master/.github%2Fworkflows%2Fbeam_PostCommit_Go.yml#L22C1-L22C1) 

I'll skip that for now since the fix is straightforward. Merging once the precommits are done.

**Comment by lostluck** [comment]
PostCommit run with this change: https://github.com/apache/beam/actions/runs/7201639105
