### PR TITLE
BEAM-13468 allow non-lts jvm version 

### LINKED ISSUE #20953: Direct Runner cannot be run on non Java LTS versions
Users of Direct Runner on non LTS Java versions e.g. Java 9, 10, 12, 13, ... cannot run Beam pipelines on Java's Direct runner because It fails with "UnsupportedOperationException unsupported Java version: X".

This is probably a requirement for the portability case because there won't be available a SDK Harness for non LTS versions of Java, however it is a too strict requirement for Direct Runner where users provide the Java environment locally.

[https://github.com/apache/beam/blob/3f1432d1c23790a1522d90ba3c2f2ed787eee383/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java#L121](https://github.com/apache/beam/blob/3f1432d1c23790a1522d90ba3c2f2ed787eee383/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java#L121)

Imported from Jira [BEAM-12408](https://issues.apache.org/jira/browse/BEAM-12408). Original Jira may contain additional context.
Reported by: iemejia.

### LINKED ISSUE #21402: Dataflow runner - be more lenient with agent java version
DataflowRunner currently uses `Environments.getJavaVersion` to detect java version and build the Dataflow user agent string.

`Environments.getJavaVersion` only accept a small subset of java version (8, 11 and 17)

It would be nice the user agent string to accept more exotic java versions to allow running the agent on more exotic jvm (still keeping the beam model itself in java 11).

Imported from Jira [BEAM-13468](https://issues.apache.org/jira/browse/BEAM-13468). Original Jira may contain additional context.
Reported by: cguillaume.

### PR DESCRIPTION
**Pull request by guillaumecle**
It possible to run beam on a non-lts jvm: either using the direct runner or uploading java code compiled in a supported version to the remote runner.

This pull request, stop throwing Exception when the current jvm is a non-lts, instead it's falling back to java 11 for the runner version.
I was able to successfully run a java 11 dataflow job from a java 15 jvm.

I think this will also fix BEAM-12408 (Direct Runner cannot be run on non Java LTS versions)

Fixes #21402
FIxes #20953

R: @kileys

### CODE REVIEW

File: runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java [hunk 1]
```diff
@@ -117,8 +121,9 @@ public static JavaVersion forSpecification(String specification) {
           return ver;
         }
       }
-      throw new UnsupportedOperationException(
-          String.format("unsupported Java version: %s", specification));
+      JavaVersion fallback = java11;
+      LOG.warn("unsupported Java version: {}, falling back to: {}", specification, fallback.specification);
```
Comment (guillaumecle) [inline runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java:125]: This logger might be a bit too chatty, I can reduce the log level if needed.

**Comment by guillaumecle** [comment]
R: @kileys

File: runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java [hunk 2]
```diff
@@ -117,8 +121,12 @@ public static JavaVersion forSpecification(String specification) {
           return ver;
         }
       }
-      throw new UnsupportedOperationException(
-          String.format("unsupported Java version: %s", specification));
+      JavaVersion fallback = java11;
```
Comment (emilymye) [inline runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java:124]: Could we have two methods here, where one is "getJavaVersionOrDefault" or similar? There are some cases where we probably want to have a strict check (i.e. expecting translatation from one of the existing enums, looking for a specific supported Docker container version where defaulting can lead to confusing behavior)

Comment (guillaumecle) [reply runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java:124]: Sure, I will add that.
Do you happen to already know some places where we would use the stricter version ?

**Comment by aaltay** [comment]
What is the next step on this PR?

File: runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java (hunk 2 above)
Comment (guillaumecle) [reply runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java:124]: I added a strict method `forSpecificationStrict`.

the java version ends up being used in
* `JAVA_SDK_HARNESS_CONTAINER_URL` for which I wan to use the lenient version for now
* `DataflowRunner.fromOptions` for which I wan to use the lenient version
* `DataflowRunner.getDefaultContainerImageNameForJob` for which I wan to use the lenient version

**Comment by guillaumecle** [comment]
This PR is ready for any additional reviews/comments.

File: runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java [hunk 3]
```diff
@@ -112,6 +116,20 @@ public String specification() {
     }
 
     public static JavaVersion forSpecification(String specification) {
+      for (JavaVersion ver : JavaVersion.values()) {
+        if (ver.specification.equals(specification)) {
+          return ver;
+        }
+      }
+      JavaVersion fallback = java11;
```
Comment (kileys) [inline runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java:124]: Instead of always falling back to 11, could we find the nearest LTS version to fall back to?

**Comment by kileys** [comment]
Thanks for the PR. Were you able to test the direct runner on a non-LTS version as well?

**Comment by guillaumecle** [comment]
Yes I have successfully tested the direct runner on java 15

File: runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java (hunk 3 above)
Comment (guillaumecle) [reply runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java:124]: Sure, working on this right now

Comment (guillaumecle) [reply runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java:124]: I can see 2 strategies:

1. find the absolute nearest. lower or higher
2. find the nearest higher. if you have code compile in java 13 you can hope to have it working on java 17 but certainly not on java 11

It's still possible to have compiled your code with 11 but run it on java 13 jvm. this is why solution 1 can work and I'm going with it for now.

Comment (guillaumecle) [reply runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/Environments.java:124]: one last question is what to do for the middle point, for now I using the higher version (e.g.: use 17 when invoked from 14)

**Comment by guillaumecle** [comment]
This PR is ready for review and approval.

**Comment by guillaumecle** [comment]
@kileys Could you take another look at this pr?

**Comment by kileys** [comment]
Sorry for the delay

**Review by kileys — APPROVED** [review]
