### PR TITLE
Set SchemaCoder for key in WithKeys transform

### LINKED ISSUE #29577: [Bug]: Coder cannot be resolved after `WithKeys.of().withKeyType()` for @DefaultSchema(JavaBeanSchema.class) types
### What happened?

When using `WithKeys.of(<lambda>).withKeyType(TypeDescriptor.of(TypeWithSchema.class)` for types annotated with `@DefaultSchema(JavaBeanSchema.class)`, Beam is not able to resolve the coder for the type, despite the schema being available.

See also https://stackoverflow.com/questions/77575574/unable-to-return-a-default-coder-for-withkeys-when-using-defaultschemajavabean

In particular, the docs say:

> A PCollection with a schema does not need to have a Coder specified, as Beam knows how to encode and decode Schema rows;
> Beam uses a special coder to encode schema types.

However, when using such a type with `WithKeys`, I consistently get this exception:
```
java.lang.IllegalStateException: Unable to return a default Coder for WithKeys/AddKeys/Map/ParMultiDo(Anonymous).output [PCollection@621486957]. Correct one of the following root causes:
  No Coder has been manually specified;  you may do so using .setCoder().
  Inferring a Coder from the CoderRegistry failed: Cannot provide coder for parameterized type org.apache.beam.sdk.values.KV<K, V>: Unable to provide a Coder for K.
  Building a Coder using a registered CoderProvider failed.
  See suppressed exceptions for detailed failures.
  Using the default output Coder from the producing PTransform failed: PTransform.getOutputCoder called.
```

Example POJO:
```
@DefaultSchema(JavaBeanSchema.class)
public class Pojo {
  private final long num;
  private final String str;

  @SchemaCreate
  public Pojo(long num, String str) {
    this.num = num;
    this.str = str;
  }

  public long getNum() {
    return this.num;
  }

  public String getStr() {
    return this.str;
  }

  @Override
  public boolean equals(final Object o) {
     ...
  }

  @Override
  public int hashCode() {
    ...
  }
}
```

Example pipeline which generates this error:
```
 public static void main(String[] args) {
    PipelineOptions options = PipelineOptionsFactory.fromArgs(args).create();
    Pipeline p = Pipeline.create(options);

    PCollection<String> a =
        p.apply(Create.of(List.of("1", "2", "3")).withType(TypeDescriptors.strings()));
    PCollection<String> b =
        p.apply(Create.of(List.of("2", "3", "4")).withType(TypeDescriptors.strings()));

    PCollection<KV<Pojo, String>> a1 =
        a.apply(
            WithKeys.<Pojo, String>of(v -> new Pojo(1, v))
                .withKeyType(TypeDescriptor.of(Pojo.class)));

    PCollection<KV<Pojo, String>> b1 =
        b.apply(
            WithKeys.<Pojo, String>of(v -> new Pojo(1, v))
                .withKeyType(TypeDescriptor.of(Pojo.class)));

    var aTag = new TupleTag<String>();
    var bTag = new TupleTag<String>();
    KeyedPCollectionTuple.of(aTag, a1)  // <== Exception here (complaining about a1)
        .and(bTag, b1)
        .apply(CoGroupByKey.create())
        .apply(
            ParDo.of(
                new DoFn<KV<Pojo, CoGbkResult>, Integer>() {
                  @ProcessElement
                  public void processElement(ProcessContext context) {
                    var element = context.element();
                    String a = element.getValue().getOnly(aTag, null);
                    String b = element.getValue().getOnly(bTag, null);
                    context.output(a != null && b != null ? 1 : 0);
                  }
                }));
  }
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Amar3tto**
Fixes  #29577

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Amar3tto** [comment]
Run Java_Amazon-Web-Services2_IO_Direct PreCommit

**Comment by Amar3tto** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Amar3tto** [comment]
R: @aromanenko-dev

File: sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/WithKeys.java [hunk 1]
```diff
@@ -129,6 +132,20 @@ public KV<K, V> apply(V element) {
...
+          SchemaRegistry schemaRegistry = SchemaRegistry.createDefault();
+          SchemaCoder<K> schemaCoder =
+              SchemaCoder.of(
+                  schemaRegistry.getSchema(keyType),
+                  keyType,
+                  schemaRegistry.getToRowFunction(keyType),
+                  schemaRegistry.getFromRowFunction(keyType));
+          result.setCoder(KvCoder.of(schemaCoder, in.getCoder()));
+        } catch (NoSuchSchemaException exception) {
+          // No Schema.
```
Comment (aromanenko-dev) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/WithKeys.java:146]: Shouldn't we fail in this case?

**Review by aromanenko-dev — APPROVED** [review]
Thanks!
LGTM, just a minor question

File: sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/WithKeys.java (hunk 1 above)
Comment (Amar3tto) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/WithKeys.java:146]: I think no, because the coder still could be set manually. There is a comment below: "let lazy coder inference have a try"
