### PR TITLE
Enforce a size limit on StringSetData

### LINKED ISSUE #32649: [Bug]: Slowness and/or broken metrics visualization when Lineage metrics is large
### What happened?

Beam Java 2.59.0 introduced Lineage metrics support for file-based IO (FileIO, TextIO, etc).

- When a pipeline read from lots of files (e.g. using a file pattern and match lots of file), one observes Dataflow UI metrics based components are broken. For example, live throughput no longer shown, progress bar stale, user counters increment incompletely.

This is due to some internal limit of total job status response size of Dataflow runner (grpc limit ~20 MB). When the size is exceeded such limit, all metrics update (counter, stringset, etc) gets dropped 

- Writes to lots of files (e.g. set a large shard number), one observe the following slowness:

```
Operation ongoing in step Write content to files/WriteFiles/FinalizeTempFileBundles/Finalize for at least 15m00s without outputting or completing in state process in thread pool-3-thread-2 with id 27
  at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.collect.ImmutableSet$RegularSetBuilderImpl.insertInHashTable(ImmutableSet.java:780)
  at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.collect.ImmutableSet$RegularSetBuilderImpl.add(ImmutableSet.java:763)
  at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.collect.ImmutableSet$Builder.add(ImmutableSet.java:527)
  at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.collect.ImmutableSet$Builder.add(ImmutableSet.java:478)
  at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:475)
  at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:549)
  at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.metrics.StringSetData.combine(StringSetData.java:58)
  at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.metrics.StringSetCell.update(StringSetCell.java:62)
  at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.metrics.StringSetCell.add(StringSetCell.java:104)
  at org.apache.beam.sdk.metrics.Metrics$DelegatingStringSet.add(Metrics.java:179)
  at org.apache.beam.sdk.metrics.Lineage.add(Lineage.java:133)
```

This was because the stringset metrics is added in the finalize write step (after moving temp file to final destination), done on single worker. Unfortunately current implementation of stringSetData.addAll is of O(N^2) complexity -- each time it copies to a new ImmutableSet, and done this for N elements.

### Issue Priority

Priority: 1 (data loss / total loss of function)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fix #32649

* Make StringSetData set mutable. This avoids copy and create new ImutableSet every time

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
Tested TextIOIT: write then read 100,000 files

- user counter elements_read 3,754,869, should be 100,000,000, counter still dropped after overall stringset grows

- "Elements added 100,000" and job progress both works when job running

- It has 
```
WARNING 2024-10-04T03:25:05.938Z StringSetData reaches capacity. Current size: 100023, last element size: 77. Further incoming elements will be dropped.
```
warning log.

Dataflow job id: 2024-10-03_20_11_47-11842727745111768860

**Comment by Abacn** [comment]
After more testing changed the cap to be 1 MB. This should be good for ~10k number of elements.

also tested on a simple pipeline GenerateSequence->Report LIneage on every element

HEAD (jobid: 2024-10-04_06_15_24-8505055598897377194)

throughput, several hundreds elements / s, cloud profiler shows stringset add takes most of time:

image


This PR (job id: 2024-10-04_06_23_39-4373466717598467131)

pipeline finishes immediately:

image

Saw log: 

```
StringSetData reaches capacity. Current size: 1000004, last element size: 58. Further incoming elements will be dropped.
```

confirm the cap is effective.

user counter work: `elements_read	1,000,000`

File: runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java [hunk 1]
```diff
@@ -54,30 +95,54 @@ public StringSetData combine(StringSetData other) {
...
+      return currentSize;
+    }
+    for (String string : others) {
+      if (combined.add(string)) {
+        currentSize += string.length();
+
+        // check capacity both before insert and after insert one, so the warning only emit once.
+        if (currentSize > STRING_SET_SIZE_LIMIT) {
+          LOG.warn(
+              "StringSetData reaches capacity. Current size: {}, last element size: {}. Further "
```
Comment (tvalentyn) [inline runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java:135]: this sounds a bit cryptic for the user, and dropping elements sounds scary - could we have a message that would be informative and actionable from the user's perspective?

Comment (Abacn) [reply runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java]: changed the language. This is not quite actionable from end user. This happens when there are lots of source/sink in the pipeline and Beam metrics system cannot record all of them. For the current occurance (file-based-io) it should be largely mitigated by #32662. The remaining case -- read lots of file from match that does not have a common directory -- will need this guard to avoid mess up the metrics system.

**Review by rohitsinha54 — APPROVED** [review]
Beside the ongoing discussion about limiting stringset size other changes LGTM. 

Thanks for prompt fix. Appreciate a ton!

File: runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java (hunk 1 above)
Comment (rohitsinha54) [reply runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java]: Also, 
If we just want to enforce a stop-gap size check for lineage rather than doing at StringSet metric level we can do at Lineage class to enforce that number of sources/sink  and/or their data size is under x.
https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/metrics/Lineage.java#L33

Comment (Abacn) [reply runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java]: Thanks for the comments. The trigger of the issue was large Lineage but the cause is Beam metrics implementation cannot handle large metrics (in total size), so the change is proposed in StringSetCell (the actual place worker store the metrics before reporting them). We can of course revisit the change when the limitation is fixed in implementations. For now the goal is make sure the whole metrics system does not break due when large stringset happens.

Comment (rohitsinha54) [reply runners/core-java/src/main/java/org/apache/beam/runners/core/metrics/StringSetData.java]: Can we move the size enforcement to Lineage class rather than forcing it for a particular metric type only which makes it inconsistent with others?

**Review by rohitsinha54 — CHANGES_REQUESTED** [review]
Can we move the size enforcement to Lineage class rather than forcing it for a particular metric type only which makes it inconsistent with others?

**Comment by Abacn** [comment]
> Can we move the size enforcement to Lineage class rather than forcing it for a particular metric type only which makes it inconsistent with others?

Found actually this is impossible. Lineage is a wrapper of StringSet, whose actual implementation is DelegateStringSet, backed by runner's StringSetData. In Lineage class there is no visibility of the current stringset size, and even if we add track (e.g. a static int) of how many strings we put into Lineage, we do not know the current set size as we do not know if the newly added element already exist in the set

**Comment by rohitsinha54** [comment]
> > Can we move the size enforcement to Lineage class rather than forcing it for a particular metric type only which makes it inconsistent with others?
> 
> Found actually this is impossible. Lineage is a wrapper of StringSet, whose actual implementation is DelegateStringSet, backed by runner's StringSetData. In Lineage class there is no visibility of the current stringset size, and even if we add track (e.g. a static int) of how many strings we put into Lineage, we do not know the current set size as we do not know if the newly added element already exist in the set

Thank you for considering and exploring this.  This seem like correct description of current implementation. We can incrementally add more to support the above need.

Here is what I am thinking, 
StringSet can expose a an API size() which gives the current size of StringSet metric. This will of course be backed by DelegateStringSet and runner's StringSetData. This will allow Lineage class to get visibility into the current size. Based on the current size Lineage class enforce a limit. Generically other consumer/user who uses StringSet metric might want to know the current size of the Set. 

At large beside the two points mentioned in (https://github.com/apache/beam/pull/32650#discussion_r1788181568) I believe a better design will be to have StringSet metric expose APIs and feature enabling consumers such as Lineage to use the metric for their use cases (in this case size limit) (bottom up) rather than top down wherein the use case of consumer is built in the metric itself. We want the beam's core metric to be generic. 

Also the size limit of metric is a Dataflow specific limitation based of limit of ReportWorkItem/GFE. Other runner might or might not have it. We should avoid coupling it with Beam's core metric.

**Comment by Abacn** [comment]
> Other runner might or might not have it. We should avoid coupling it with Beam's core metric

Though didn't get into it, I suspect there is a limit not limited to Dataflow. Under portable framework where runner API backed by grpc messages, then when client query for job status, the response size should have certain limit

**Comment by rohitsinha54** [comment]
> > Other runner might or might not have it. We should avoid coupling it with Beam's core metric
> 
> Though didn't get into it, I suspect there is a limit not limited to Dataflow. Under portable framework where runner API backed by grpc messages, then when client query for job status, the response size should have certain limit

That makes sense.

**Comment by rohitsinha54** [comment]
WDYT of breaking this PR in two parts: 
1. Making StringSetData set mutable 
2. Size limit enforcement (This can go in later separately)

**Comment by Abacn** [comment]
> WDYT of breaking this PR in two parts:
> 
> 1. Making StringSetData set mutable
> 2. Size limit enforcement (This can go in later separately)

Yeah this PR essentially contains two fix, corresponding to two related issues in #32649. Mutable set will fix slowness.
 However we still need limit enforcement to fix metrics breakage. Even with #32662 in the metrics system will still break for FileIO read patterns like `gs://bucket/folder/**/some_data.txt` so I think both fix is needed for the current release

**Comment by rohitsinha54** [comment]
> > WDYT of breaking this PR in two parts:
> > 
> > 1. Making StringSetData set mutable
> > 2. Size limit enforcement (This can go in later separately)
> 
> Yeah this PR essentially contains two fix, corresponding to two related issues in #32649. Mutable set will fix slowness. However we still need limit enforcement to fix metrics breakage. Even with #32662 in the metrics system will still break for FileIO read patterns like `gs://bucket/folder/**/some_data.txt` so I think both fix is needed for the current release

Yes correct, I was thinking we can submit Making StringSetData set mutable today but it is upto you if you want to keep them together.

**Comment by liferoad** [comment]
Can we do the minimal here to unblock Beam 2.60.0? Later, we can keep improving.

**Comment by liferoad** [comment]
Please update CHANGES.md to mention the impacted Beam versions by this issue. @Abacn

**Comment by Abacn** [comment]
> Please update CHANGES.md to mention the impacted Beam versions by this issue. @Abacn

Did in #32664. The issue was introduced in Beam 2.59.0

**Comment by rohitsinha54** [comment]
> > > Can we move the size enforcement to Lineage class rather than forcing it for a particular metric type only which makes it inconsistent with others?
> > 
> > 
> > Found actually this is impossible. Lineage is a wrapper of StringSet, whose actual implementation is DelegateStringSet, backed by runner's StringSetData. In Lineage class there is no visibility of the current stringset size, and even if we add track (e.g. a static int) of how many strings we put into Lineage, we do not know the current set size as we do not know if the newly added element already exist in the set
> 
> Thank you for considering and exploring this. This seem like correct description of current implementation. We can incrementally add more to support the above need.
> 
> Here is what I am thinking, StringSet can expose a an API size() which gives the current size of StringSet metric. This will of course be backed by DelegateStringSet and runner's StringSetData. This will allow Lineage class to get visibility into the current size. Based on the current size Lineage class enforce a limit. Generically other consumer/user who uses StringSet metric might want to know the current size of the Set.
> 
> At large beside the two points mentioned in ([#32650 (comment)](https://github.com/apache/beam/pull/32650#discussion_r1788181568)) I believe a better design will be to have StringSet metric expose APIs and feature enabling consumers such as Lineage to use the metric for their use cases (in this case size limit) (bottom up) rather than top down wherein the use case of consumer is built in the metric itself. We want the beam's core metric to be generic.
> 
> Also the size limit of metric is a Dataflow specific limitation based of limit of ReportWorkItem/GFE. Other runner might or might not have it. We should avoid coupling it with Beam's core metric.

We discussed this offline. 

Here is the summary of the discussion for future. 
If size is exposed based on the StringSetData then the size will be for that specific bundle since  one metric may have multiple metrics containers (backed by different stringsetdata). This can confuse user if exposed a api level and also breaks the abstraction which Beam as a programming model strives to provide.

The current size enforcement also has this issue but since it is not exposed to user to consume. the stringsetdata limit happens to work with FileIO because currently FileIO report source and sink metrics in a loop, so it happens to write to single metrics container on a single worker. Hence the size enforcement is tied to FileIO implementation. So this is not an ideal fix but we need to solve the FileIO large file issue somehow. 

I will propose to drop the limit enforcement on string set completely in anyway. We will limit the number of reported files in FileIO itself to ensure we do not hit it. This will avoid FileIO implication and implementation being tied to a metric type. 

See comment. https://github.com/apache/beam/pull/32662#issuecomment-2400436239
