### PR TITLE
24802 fix missing test resources

### LINKED ISSUE #24802: [Failing Test]: org.apache.beam.sdk.io.gcp.pubsub.PubsubSchemaIT.classMethod in beam_PostCommit_Java_DataflowV1 and V2
### What happened?

error message:
```
org.apache.beam.sdk.io.gcp.pubsub.PubsubSchemaIT.classMethod

Error Message
java.nio.file.NoSuchFileException: file:/home/jenkins/jenkins-slave/workspace/beam_PostCommit_Java_DataflowV2/src/sdks/java/io/google-cloud-platform/build/libs/beam-sdks-java-io-google-cloud-platform-2.45.0-SNAPSHOT-tests.jar!/org/apache/beam/sdk/io/gcp/pubsub/avro_all_data_types_flat_schema.json
```

caused by #24443

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by damondouglas**
This PR closes #24802 by removing the test dependency on resource files.  It refactors the Pub/Sub schema creation method by receiving the full content of the definition instead of a resource path.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - ~Update `CHANGES.md` with noteworthy changes.~
 - ~If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
Run PostCommit_Java_Dataflow

**Comment by Abacn** [comment]
Run PostCommit_Java_DataflowV2

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java [hunk 1]
```diff
@@ -506,9 +506,9 @@ public abstract List<SubscriptionPath> listSubscriptions(ProjectPath project, To
    */
   public abstract boolean isEOF();
 
-  /** Create {@link com.google.api.services.pubsub.model.Schema} from resource path. */
+  /** Create {@link com.google.api.services.pubsub.model.Schema} from Schema definition content. */
   public abstract void createSchema(
```
Comment (Abacn) [inline sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java:510]: I understand this method is just introduced last week (#24443) and should not introduce breaking change to released versions. However I would like to understand how "public" the PubSubClient abstract class is? Suppose users have their own pubsub client implementation adding a new abstract method would break them. Or, users are not supposed to implement their own client but the "public" here is for the usage of other modules within Beam SDK. In the latter case, we should add some javadoc to the class warning that "internal use only, no backward compatibility guaranteed."

**Review by lukecwik — APPROVED** [review]
LGTM

Lets merge as this fixes the jenkins breakage to restore a green signal.

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java (hunk 1 above)
Comment (lukecwik) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/pubsub/PubsubClient.java:510]: Unfortunately PubsubClient has been around for several years.

Marking with `@Internal` makes sense and can be done in a follow-up. There are likely several classes in here that should be updated and we could add a note in `CHANGES.md` that we annotated classes with `@Internal`.
