### PR TITLE
[CdapIO] Integration CdapIO with SparkReceiverIO

### LINKED ISSUE #23449: [Bug]: Flaky test: org.apache.beam.sdk.io.sparkreceiver.SparkReceiverIOTest.testReadFromCustomReceiverWithOffsetFailsAndReread
### What happened?

See on https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5588/

```
Error Message
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.RuntimeException: Received unexpected element: 18
Stacktrace
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.RuntimeException: Received unexpected element: 18
	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:374)
	at org.apache.beam.sdk.io.sparkreceiver.SparkReceiverIOTest.testReadFromCustomReceiverWithOffsetFailsAndReread(SparkReceiverIOTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.apache.beam.sdk.testing.TestPipeline$1.evaluate(TestPipeline.java:323)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.lang.RuntimeException: Received unexpected element: 18
	at org.apache.beam.sdk.io.sparkreceiver.SparkReceiverIOTest$TestOutputDoFn.processElement(SparkReceiverIOTest.java:149)
```

### Issue Priority

Priority: 1

### Issue Component

Component: test-failures

### PR DESCRIPTION
**Pull request by Amar3tto**
- Integration CdapIO with SparkReceiverIO
- Also resolves #23449

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java [hunk 1]
```diff
@@ -83,46 +86,50 @@ public Plugin withConfig(PluginConfig pluginConfig) {
...
-        throw new IllegalStateException("Can not call prepareRun");
-      }
-    }
-    try {
-      cdapPluginObj.prepareRun(getContext());
-      if (getPluginType().equals(PluginConstants.PluginType.SOURCE)) {
-        for (Map.Entry<String, String> entry :
-            getContext().getInputFormatProvider().getInputFormatConfiguration().entrySet()) {
-          getHadoopConfiguration().set(entry.getKey(), entry.getValue());
+    if (!isUnbounded()) {
```
Comment (sorokin-andrey) [inline sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java:89]: I would recommend inverting this conditional operator. 
This will allow us to reduce the nesting of the code by 1 tab.

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java [hunk 2]
```diff
@@ -83,46 +86,50 @@ public Plugin withConfig(PluginConfig pluginConfig) {
...
+          LOG.error("Can not instantiate CDAP plugin class", e);
+          throw new IllegalStateException("Can not call prepareRun");
         }
-      } else {
-        for (Map.Entry<String, String> entry :
-            getContext().getOutputFormatProvider().getOutputFormatConfiguration().entrySet()) {
-          getHadoopConfiguration().set(entry.getKey(), entry.getValue());
+      }
+      try {
+        cdapPluginObj.prepareRun(getContext());
```
Comment (sorokin-andrey) [inline sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java:104]: Basically, we need this try-catch only to deal with this line of code. If you move it to a separate private method, it will increase the readability of the code dramatically.

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java [hunk 3]
```diff
@@ -83,46 +86,50 @@ public Plugin withConfig(PluginConfig pluginConfig) {
...
-    try {
-      cdapPluginObj.prepareRun(getContext());
-      if (getPluginType().equals(PluginConstants.PluginType.SOURCE)) {
-        for (Map.Entry<String, String> entry :
-            getContext().getInputFormatProvider().getInputFormatConfiguration().entrySet()) {
-          getHadoopConfiguration().set(entry.getKey(), entry.getValue());
+    if (!isUnbounded()) {
+      PluginConfig pluginConfig = getPluginConfig();
+      checkStateNotNull(pluginConfig, "PluginConfig should be not null!");
+      if (cdapPluginObj == null) {
```
Comment (sorokin-andrey) [inline sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java:92]: Why didn't you move this conditional block to the separate method?

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java [hunk 4]
```diff
@@ -83,46 +86,50 @@ public Plugin withConfig(PluginConfig pluginConfig) {
...
         }
-      } else {
-        for (Map.Entry<String, String> entry :
-            getContext().getOutputFormatProvider().getOutputFormatConfiguration().entrySet()) {
-          getHadoopConfiguration().set(entry.getKey(), entry.getValue());
+      }
+      try {
+        cdapPluginObj.prepareRun(getContext());
+        if (getPluginType().equals(PluginConstants.PluginType.SOURCE)) {
+          for (Map.Entry<String, String> entry :
```
Comment (sorokin-andrey) [inline sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java:106]: Personally, I think this is unclear what you are doing here and why. Plus these for loops look almost identical, except for the collection part.

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java (hunk 1 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java]: Done

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java (hunk 2 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java]: Fixed try-catch block.
Don't think that we need a separate method for this, since our method already called `prepareRun()`.

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java (hunk 3 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java]: Done

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java (hunk 4 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/Plugin.java]: For `Source` plugins we are copying configuration from `InputFormatProvider`, for `Sink` plugins from `OutputFormatProvider`. 
Do you suggest moving it to a separate method?

**Comment by Amar3tto** [comment]
Run Java PreCommit

**Comment by Lizzfox** [comment]
@chamikaramj @aromanenko-dev 
[CdapIO] Integration CdapIO with SparkReceiverIO PR is ready for review 
Thank you!

File: sdks/java/io/cdap/build.gradle [hunk 5]
```diff
@@ -52,14 +52,17 @@ dependencies {
     implementation library.java.cdap_plugin_zendesk
     implementation library.java.commons_lang3
     implementation library.java.guava
+    implementation library.java.google_code_gson
     implementation library.java.hadoop_common
     implementation library.java.hadoop_mapreduce_client_core
     implementation library.java.jackson_core
     implementation library.java.jackson_databind
     implementation library.java.slf4j_api
+    implementation library.java.spark_streaming
```
Comment (mosche) [inline sdks/java/io/cdap/build.gradle:61]: Just noticing this is based on Spark 2.4 and wondering.... considering Spark 2 is close to reaching it's end of life, wouldn't it make more sense to kick this of with Spark 3?

Comment (aromanenko-dev) [reply sdks/java/io/cdap/build.gradle:61]: Good question, I missed that

Comment (Amar3tto) [reply sdks/java/io/cdap/build.gradle:61]: Yes, it would be good to clarify that.
We don't use Spark environment in CdapIO. Our goal is only to mimic all Spark classes related to Cdap Plugins in order to use the business logic.
At the moment, all the Cdap plugins we want to support use Spark 2, so we use Spark 2 here.

Comment (Amar3tto) [reply sdks/java/io/cdap/build.gradle:61]: @mosche What do you mean by naming scheme?
Do you suggest to add something like this?
```
def shouldProvideSpark2 = true
def shouldProvideSpark3 = false
```
...
```
if (shouldProvideSpark2) {
    implementation library.java.spark_streaming
    implementation library.java.spark_core
}
if (shouldProvideSpark3) {
    implementation library.java.spark3_streaming
    implementation library.java.spark3_core
}
```

Comment (mosche) [reply sdks/java/io/cdap/build.gradle:61]: @Amar3tto Unfortunately this can't be dynamically resolved. If we (eventually) want to support Spark 2 and 3, there has to be 2 maven artifacts. I was talking about a naming scheme for these.
So something like:
- org.apache.beam/beam-sdks-java-io-cdap-spark2
- org.apache.beam/beam-sdks-java-io-cdap-spark3

Comment (Lizzfox) [reply sdks/java/io/cdap/build.gradle:61]: I want to clarify: within the current project, support for Spark version 3 is a "[non-goal](https://docs.google.com/document/d/1T-bhd0Qk7DBePIfgHEPagYiA1oLP4z5kYEd0S1SOGxQ/edit#heading=h.cf98cc3ttmdn)".

Comment (mosche) [reply sdks/java/io/cdap/build.gradle:61]: > I want to clarify: within the current project, support for Spark version 3 is a "[non-goal](https://docs.google.com/document/d/1T-bhd0Qk7DBePIfgHEPagYiA1oLP4z5kYEd0S1SOGxQ/edit#heading=h.cf98cc3ttmdn)".

👍 my primary concern was the appropriate naming of artifacts to make the Spark dependency obvious and allow adding support for Spark 3 later

**Comment by Lizzfox** [comment]
@chamikaramj @aromanenko-dev 
kindly remind you that PR is ready for the review :)

File: sdks/java/io/cdap/build.gradle (hunk 5 above)
Comment (aromanenko-dev) [reply sdks/java/io/cdap/build.gradle:61]: Shouldn't we apply the same naming strategy as we do for Spark dependencies of versions 2 and 3 for Spark runner? I know it's not perfect but, at least, it won't be more confusing.

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/CdapIO.java [hunk 6]
```diff
@@ -17,29 +17,165 @@
...
+ * p.apply("ReadStreaming",
+ * CdapIO.<String, String>read()
+ *             .withCdapPlugin(Plugin.createStreaming(EmployeeStreamingSource.class))
+ *             .withPluginConfig(pluginConfig)
+ *             .withKeyClass(String.class)
+ *             .withValueClass(String.class));
+ * }</pre>
  */
 @Experimental(Kind.SOURCE_SINK)
+@SuppressWarnings("nullness")
```
Comment (chamikaramj) [inline sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/CdapIO.java:178]: Please fix null errors instead of supressing.

Comment (chamikaramj) [reply sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/CdapIO.java:178]: You can reproduce checkerframework errors locally by temporarily setting following to false.
https://github.com/apache/beam/blob/b7b71361590b4fa8bac32a4541058bafdf0d1df1/buildSrc/src/main/groovy/org/apache/beam/gradle/BeamModulePlugin.groovy#L959

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/MappingUtils.java [hunk 7]
```diff
@@ -33,23 +38,118 @@
...
+      return Plugin.createBatch(
+          pluginClass, HubspotOutputFormat.class, SourceInputFormatProvider.class);
     } else if (pluginClass.equals(ServiceNowSource.class)) {
-      return Plugin.create(
+      return Plugin.createBatch(
           pluginClass, ServiceNowInputFormat.class, SourceInputFormatProvider.class);
+    } else if (pluginClass.equals(HubspotStreamingSource.class)) {
+      return Plugin.createStreaming(pluginClass);
+    }
+    throw new UnsupportedOperationException(
```
Comment (chamikaramj) [inline sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/MappingUtils.java:88]: It should be possible to add support for more plugins without updating Beam code (may be in a future PR, so not a blocker).

File: sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java [hunk 8]
```diff
@@ -154,11 +171,45 @@ public void testReadingData() {
...
       expected.add(KV.of(String.valueOf(i), EmployeeInputFormat.EMPLOYEE_NAME_PREFIX + i));
     }
-    PCollection<KV<String, String>> actual = p.apply("ReadTest", read);
+    PCollection<KV<String, String>> actual = p.apply("ReadBatchTest", read);
     PAssert.that(actual).containsInAnyOrder(expected);
     p.run();
   }
 
+  @Test
+  public void testReadingDataStreaming() {
```
Comment (chamikaramj) [inline sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java:180]: To clarify, this is just using a streaming plugin (not running a streaming ppipeline) ? We should name the test appropriately.

File: sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java [hunk 9]
```diff
@@ -154,11 +171,45 @@ public void testReadingData() {
...
+    List<String> outputRecords = TestOutputDoFn.getRecords();
+    outputRecords.clear();
+
+    p.apply("ReadStreamingTest", read)
+        .setCoder(KvCoder.of(NullableCoder.of(StringUtf8Coder.of()), StringUtf8Coder.of()))
+        .apply(Values.create())
+        .apply(ParDo.of(new TestOutputDoFn()));
+
+    p.run().waitUntilFinish(Duration.standardSeconds(15));
+    assertEquals(storedRecords, outputRecords);
```
Comment (chamikaramj) [inline sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java:210]: Instead of comparing with a local assert, we should update the pipeline to use PAssert. (otherwise, this test will not work for other runners).

https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/testing/PAssert.java

File: sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/TestOutputDoFn.java [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+import java.util.ArrayList;
+import java.util.List;
+import org.apache.beam.sdk.transforms.DoFn;
+
+public class TestOutputDoFn extends DoFn<String, String> {
+  private static final List<String> RECORDS = new ArrayList<>();
+
+  @ProcessElement
+  public void processElement(@Element String input, DoFn.OutputReceiver<String> output) {
+    RECORDS.add(input);
```
Comment (chamikaramj) [inline sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/TestOutputDoFn.java:29]: Note that this pattern will not work in general since runners might choose to split bundles and/or may serialize the DoFn class before execution. Please use PAssert for verification instead.

File: sdks/java/io/sparkreceiver/src/main/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFn.java [hunk 11]
```diff
@@ -141,15 +145,42 @@ public boolean hasRecords() {
...
+
+      final SerializableFunction<Object[], Void> storeFn =
+          (input) -> {
+            if (input == null) {
               return null;
-            });
+            }
+
+            if (input[0] instanceof ByteBuffer) {
+              final ByteBuffer byteBuffer = ((ByteBuffer) input[0]).asReadOnlyBuffer();
```
Comment (chamikaramj) [inline sdks/java/io/sparkreceiver/src/main/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFn.java:156]: Why are we just using input[0] ?

File: sdks/java/io/sparkreceiver/src/main/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFn.java [hunk 12]
```diff
@@ -141,15 +145,42 @@ public boolean hasRecords() {
...
+            } else if (input[0] instanceof Iterator) {
+              final Iterator<V> iterator = (Iterator<V>) input[0];
+              while (iterator.hasNext()) {
+                V record = (V) iterator.next();
+                recordsQueue.offer(record);
+              }
+            } else if (input[0] instanceof ArrayBuffer) {
+              final ArrayBuffer<V> arrayBuffer = (ArrayBuffer<V>) input[0];
+              final Iterator<V> iterator = arrayBuffer.iterator();
+              while (iterator.hasNext()) {
```
Comment (chamikaramj) [inline sdks/java/io/sparkreceiver/src/main/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFn.java:170]: Please add unit tests to fully cover this logic.

**Review by chamikaramj — CHANGES_REQUESTED** [review]
Thanks!

File: sdks/java/io/cdap/build.gradle (hunk 5 above)
Comment (chamikaramj) [reply sdks/java/io/cdap/build.gradle:61]: @mosche do you mean ":sdks:java:io:sparkreceiver" should be renamed to may be ":sdks:java:io:spark2receiver" ?

If so, +1 for that.

Comment (mosche) [reply sdks/java/io/cdap/build.gradle:61]: yes, modules that depends on spark should contain the spark version in their name. spark2receiver sounds good 👍 
It looks like the cdap module also depends on spark, so the same applies there:
```
    implementation library.java.spark_streaming
```

Comment (aromanenko-dev) [reply sdks/java/io/cdap/build.gradle:61]: Unfortunately, I'm disagree with that, at least, for Spark v2 entities. We don't have this naming strategy for Spark runner (why? it's another question), so it will be confusing to have `spark2*` and `spark*` names in the same time. 

Though, for Spark v3 we used to have `spark3` prefix, so we can continue that strategy for `spark4` and etc if it will be needed. 

Actually, it looks as more wide question that can be applied for similar cases in other Beam components.

Comment (mosche) [reply sdks/java/io/cdap/build.gradle:61]: Hmm, I personally don't see why it's necessary to repeat the same mistake just because it was made once? 
Also IOs and runners are very different in nature. Replacing the runner is trivial, but with the Cdap IO you're better aware right from the start that it depends on Spark 2 (and Spark 3 is not (yet) supported). 
In any case, I don't wanna block this PR ... just a long hanging fruit and missed opportunity in my eyes.

Comment (aromanenko-dev) [reply sdks/java/io/cdap/build.gradle:61]: Well, then it should be `:sdks:java:io:sparkreceiver:2` (like `:runners:spark:2` and `:runners:spark:3`) but not `:sdks:java:io:spark2receiver`

Comment (chamikaramj) [reply sdks/java/io/cdap/build.gradle:61]: Yeah, ":sdks:java:io:sparkreceiver:2" seems to be more consistent with the current convention.

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/CdapIO.java (hunk 6 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/CdapIO.java]: Fixed

File: sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java (hunk 8 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java]: Renamed

File: sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java (hunk 9 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/CdapIOTest.java]: Changed to PAssert

File: sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/TestOutputDoFn.java (hunk 10 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/test/java/org/apache/beam/sdk/io/cdap/TestOutputDoFn.java]: Removed

File: sdks/java/io/sparkreceiver/src/main/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFn.java (hunk 11 above)
Comment (Amar3tto) [reply sdks/java/io/sparkreceiver/src/main/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFn.java]: Added a comment:
`Use only [0] element - data.
 The other elements are not needed because they are related to Spark environment options.`

File: sdks/java/io/sparkreceiver/src/main/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFn.java (hunk 12 above)
Comment (Amar3tto) [reply sdks/java/io/sparkreceiver/src/main/java/org/apache/beam/sdk/io/sparkreceiver/ReadFromSparkReceiverWithOffsetDoFn.java:175]: Added three new tests that cover this logic.

**Comment by Amar3tto** [comment]
Run RAT PreCommit

**Comment by Amar3tto** [comment]
Run RAT PreCommit

**Comment by Amar3tto** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by Amar3tto** [comment]
Run Java_Examples_Dataflow PreCommit

File: sdks/java/io/cdap/build.gradle (hunk 5 above)
Comment (Lizzfox) [reply sdks/java/io/cdap/build.gradle:61]: Thank you all for the review and comments on the PR. Can we do this renaming you're talking about in the next PR (after this one is completed) without running into multiple conflicts?

Comment (mosche) [reply sdks/java/io/cdap/build.gradle:61]: 👍

Comment (aromanenko-dev) [reply sdks/java/io/cdap/build.gradle:61]: @Lizzfox If would be great to make these changes (I'm fine for a separate PR for this) till the next release branch cut.

Comment (Lizzfox) [reply sdks/java/io/cdap/build.gradle:61]: @aromanenko-dev got it, thanks! We'll make changes as soon as this PR is merged and I'll tag you in the comments.

File: sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/MappingUtils.java (hunk 7 above)
Comment (Amar3tto) [reply sdks/java/io/cdap/src/main/java/org/apache/beam/sdk/io/cdap/MappingUtils.java:88]: Yes, we already add such ability. There are two methods in `CdapIO`: 

- `withCdapPluginClass()` - it will try to get `Plugin` by class from predefined list in `MappingUtils`, as we can see here.
- `withCdapPlugin()` - we can pass manually `Plugin.create(...)` with all needed parameters, it is used for example in tests. (without using `MappingUtils` class)

**Comment by aromanenko-dev** [comment]
@chamikaramj @mosche 
Do you have additional comments on this PR?

**Comment by mosche** [comment]
LGTM @aromanenko-dev 
Though - unrelated - one more question @Lizzfox, what's the purpose / importance of Spark in the picture here? We're actually preparing the removal of the deprecated Spark2 runner (asap). The runner is badly broken and not usable anymore due to a Jackson dependency conflict (see #23568). Unfortunately this wasn't caught in local tests, but only if submitting a job to a Spark 2.4 cluster. Does this impact you?

**Comment by Lizzfox** [comment]
@mosche we don't use Spark runner, we only support Dataflow runner in our implementation. Thanks

**Review by aromanenko-dev — APPROVED** [review]
