### PR TITLE
Fix deleteTimer in InMemoryTimerInternals and enable VR tests for GroupIntoBatches.

### LINKED ISSUE #21378: Canceling a timer by ID is not yet supported in InMemoryTimerInternals
Got the following exception with spark runner and GroupIntoBatches transform:

Caused by: java.lang.UnsupportedOperationException: Canceling a timer by ID is not yet supported.
    at org.apache.beam.runners.core.InMemoryTimerInternals.deleteTimer(InMemoryTimerInternals.java:158)
    at org.apache.beam.runners.core.SimpleDoFnRunner$TimerInternalsTimer.clear(SimpleDoFnRunner.java:1198)
    at org.apache.beam.sdk.transforms.GroupIntoBatches$GroupIntoBatchesDoFn.processElement(GroupIntoBatches.java:474)

 

The InMemoryTimerInternals.deleteTimer with a timeDomain is not supported:

public void deleteTimer(
StateNamespace namespace, String timerId, String timerFamilyId, TimeDomain timeDomain) {
throw new UnsupportedOperationException("Canceling a timer by ID is not yet supported.");
}

However, this function is called by SimpleDoFnRunner$TimerInternalsTimer.clear:

public void clear() {
this.timerInternals.deleteTimer(this.namespace, this.timerId, this.timerFamilyId, this.spec.getTimeDomain());
}

Which is called by GroupIntoBatches$GroupIntoBatchesDoFn.processElement.

 

Imported from Jira [BEAM-14018](https://issues.apache.org/jira/browse/BEAM-14018). Original Jira may contain additional context.
Reported by: wenqing.yang.

### PR DESCRIPTION
**Pull request by mosche**
Fixes #21378

Fix deleteTimer in InMemoryTimerInternals and enable VR tests for GroupIntoBatches.

Make sure GroupIntoBatches / onWindowExpiration isn't used in Spark runner to prevent data loss, see #22524.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by mosche** [comment]
Run Flink ValidatesRunner

**Comment by mosche** [comment]
Run Spark ValidatesRunner

**Comment by mosche** [comment]
Run Dataflow ValidatesRunner

**Comment by mosche** [comment]
Run Flink ValidatesRunner

**Comment by mosche** [comment]
Run Spark ValidatesRunner

**Comment by mosche** [comment]
Run Dataflow ValidatesRunner

**Comment by mosche** [comment]
Run Flink ValidatesRunner

**Comment by mosche** [comment]
R: @TheNeuralBit 
R: @reuvenlax

File: runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java [hunk 1]
```diff
@@ -155,10 +156,18 @@ public void setTimer(TimerData timerData) {
...
   public void deleteTimer(
       StateNamespace namespace, String timerId, String timerFamilyId, TimeDomain timeDomain) {
-    throw new UnsupportedOperationException("Canceling a timer by ID is not yet supported.");
+    TimerData removedTimer = existingTimers.remove(namespace, timerId + '+' + timerFamilyId);
+    if (removedTimer != null) {
+      Preconditions.checkState(
+          removedTimer.getDomain().equals(timeDomain),
+          "%s doesn't match time domain %s of timer",
+          timeDomain,
+          removedTimer.getDomain());
```
Comment (TheNeuralBit) [inline runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java:165]: I don't really have context here, but I wonder if we should do this check first, and unconditionally, so that we don't end up with a partially removed timer?

File: runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java [hunk 2]
```diff
@@ -155,10 +156,18 @@ public void setTimer(TimerData timerData) {
...
+      timersForDomain(timeDomain).remove(removedTimer);
+    }
   }
 
-  /** @deprecated use {@link #deleteTimer(StateNamespace, String, TimeDomain)}. */
+  /** @deprecated use {@link #deleteTimer(StateNamespace, String, String, TimeDomain)}. */
```
Comment (TheNeuralBit) [inline runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java:170]: Maybe this should defer to the `deleteTimer(StateNamespace, String, String, TimeDomain)` implementation?

**Review by TheNeuralBit — APPROVED** [review]
I confirmed that the new VR tests in GroupIntoBatchesTest are running for [Flink](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Flink_PR/464/testReport/org.apache.beam.sdk.transforms/GroupIntoBatchesTest/) and [Dataflow](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Dataflow_PR/493/testReport/org.apache.beam.sdk.transforms/GroupIntoBatchesTest/). Is it expected that they're not running for [Spark](https://ci-beam.apache.org/job/beam_PostCommit_Java_ValidatesRunner_Spark_PR/479/testReport/org.apache.beam.sdk.transforms/)?

File: runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java (hunk 2 above)
Comment (mosche) [reply runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java:170]: I considered doing that, though it would mean an additional lookup the get the `TimeDomain` first. That didn't seem worth it ... But no real preference from my side.

File: runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java (hunk 1 above)
Comment (mosche) [reply runners/core-java/src/main/java/org/apache/beam/runners/core/InMemoryTimerInternals.java:165]: I did that initially, but removed the additional lookup again again as a timer is uniquely identified by `namespace` + `timerId`. I added this as sanity check here to detect any broken state, but as far as I understand this should never be the case.

**Comment by mosche** [comment]
Thanks for the jumping on this so quickly @TheNeuralBit 🙇‍♂️ I hope you had a great time off :)

**Comment by TheNeuralBit** [comment]
Thanks for the responses!
