### PR TITLE
[Managed Iceberg] custom equals method for SerializedDataFile

### LINKED ISSUE #33776: [Bug]: Iceberg integration test warning log spam possibly reveals real issue
### What happened?

https://github.com/apache/beam/actions/workflows/IO_Iceberg_Integration_Tests.yml

there are lots of warning logs:

```
025-01-27T10:28:15.6939911Z     Jan 27, 2025 10:28:15 AM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
2025-01-27T10:28:15.6948028Z     WARNING: Coder of type class org.apache.beam.sdk.schemas.SchemaCoder has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element FileWriteResult{tableIdentifierString=test_db_testStreamToDynamicDestinationsAndKeepFields.test_table_4_e, serializableDataFile=SerializableDataFile{path=gs://managed-iceberg-integration-tests/HiveCatalogIT/390697b2-b28d-4553-87b1-da546d84fb88/test_db_testStreamToDynamicDestinationsAndKeepFields.db/test_table_4_e/data/4ecc656e-c85d-4939-b3e5-5066234c398b_2ac1dfa6-cb8e-461e-a657-6031a62b9575_1.parquet, fileFormat=PARQUET, recordCount=2, fileSizeInBytes=2705, partitionPath=, partitionSpecId=0, keyMetadata=null,
splitOffsets=[4], columnSizes={1=60, 2=56, 4=49, 5=72, 7=49, 8=51, 9=79, 10=50}, valueCounts={1=2, 2=2, 4=2, 5=2, 7=2, 8=2, 9=2, 10=2}, nullValueCounts={1=0, 2=0, 4=0, 5=0, 7=0, 8=0, 9=0, 10=0}, nanValueCounts={8=0}, lowerBounds={1=[B@57bb32b4, 2=[B@5f645f56, 4=[B@6e2a132, 5=[B@4cc2022d, 7=[B@4262b793, 8=[B@3f81de66, 9=[B@2c791395, 10=[B@70f6bf5d}, upperBounds={1=[B@27ff50ff, 2=[B@163cc888, 4=[B@72bd8461, 5=[B@37f4c13c, 7=[B@6a510795, 8=[B@1a59fadf, 9=[B@4d9eb79, 10=[B@153537ff}}}
2025-01-27T10:28:15.6955780Z     Jan 27, 2025 10:28:15 AM org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector verifyUnmodifiedThrowingCheckedExceptions
2025-01-27T10:28:15.6962562Z     WARNING: Coder of type class org.apache.beam.sdk.schemas.SchemaCoder has a #structuralValue method which does not return true when the encoding of the elements is equal.
Element FileWriteResult{tableIdentifierString=test_db_testStreamToDynamicDestinationsAndKeepFields.test_table_0_a, serializableDataFile=SerializableDataFile{path=gs://managed-iceberg-integration-tests/HiveCatalogIT/390697b2-b28d-4553-87b1-da546d84fb88/test_db_testStreamToDynamicDestinationsAndKeepFields.db/test_table_0_a/data/4ecc656e-c85d-4939-b3e5-5066234c398b_148e0654-c6a2-4a3f-a640-bc5e331cafeb_1.parquet,
fileFormat=PARQUET, recordCount=20, fileSizeInBytes=3139, partitionPath=, partitionSpecId=0, keyMetadata=null, splitOffsets=[4], columnSizes={1=104, 2=104, 4=97, 5=124, 7=97, 8=128, 9=128, 10=100}, valueCounts={1=20, 2=20, 4=20, 5=20, 7=20, 8=20, 9=20, 10=20}, nullValueCounts={1=0, 2=0, 4=0, 5=0, 7=0, 8=0, 9=0, 10=0}, nanValueCounts={8=0}, lowerBounds={1=[B@4dbe0ba2, 2=[B@392a4276, 4=[B@61a5970e, 5=[B@646372cd, 7=[B@593d86f8, 8=[B@326f565b, 9=[B@7fbfbaff, 10=[B@355adf}, upperBounds={1=[B@350a1667, 2=[B@7d1f4313, 4=[B@7ff5760d, 5=[B@55bc388e, 7=[B@3060b570, 8=[B@37607fb4, 9=[B@63f1324b, 10=[B@57bd0ef3}}}

```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by ahmedabu98**
Adding a more accurate equals method for SerializedDataFile because the default equals method does not account for objects of type `Map<Integer, byte[]>`.

This helps clean up logs like these, which are actually extremely noisy:
`WARNING: Coder of type class org.apache.beam.sdk.schemas.SchemaCoder has a #structuralValue method which does not return true when the encoding of the elements is equal. Element FileWriteResult{tableIdentifierString={"namespace":["managed_iceberg_bqms_tests_no_delete"],"name":"testWriteToPartitionedTable_667244372263427"}, serializableDataFile=SerializableDataFile{path=gs://managed-iceberg-integration-tests/BigQueryMetastoreCatalogIT/408aefd5-2598-4fc3-b2e1-451500fff0c8/managed_iceberg_bqms_tests_no_delete.db/testWriteToPartitionedTable_667244372263427/data/bool=true/datetime_hour=1970-01-01-00/str_trunc=value_1/23583901-d389-4eca-a748-f7194ce06fbc_dae547f4-509e-4fd6-a805-b23cb94e2b55_1.parquet, fileFormat=PARQUET, recordCount=16, fileSizeInBytes=7052, partitionPath=bool=true/datetime_hour=0/str_trunc=value_1, partitionSpecId=0, keyMetadata=null, splitOffsets=[4], columnSizes={1=99, 2=106, 3=102, 4=45, 5=80, 9=91, 10=107, 11=83, 12=80, 13=83, 14=115, 16=80, 17=110, 18=121, 19=83, 20=151, 21=49, 23=49, 24=49, 25=49, 26=49}, valueCounts={1=16, 2=16, 3=16, 4=16, 5=16, 9=16, 10=16, 11=16, 12=16, 13=16, 14=16, 16=16, 17=16, 18=16, 19=16, 20=67, 21=16, 23=16, 24=16, 25=16, 26=16}, nullValueCounts={1=0, 2=0, 3=0, 4=0, 5=0, 9=0, 10=0, 11=0, 12=0, 13=0, 14=0, 16=0, 17=0, 18=0, 19=0, 20=3, 21=16, 23=16, 24=16, 25=16, 26=16}, nanValueCounts={17=0, 24=0}, lowerBounds={1=[B@1b0b6e85, 2=[B@76cb6b52, 3=[B@14752039, 4=[B@5b22e2ef, 5=[B@1b1dd048, 9=[B@36a1b982, 10=[B@be82387, 11=[B@47918d8f, 12=[B@32fb8aa5, 13=[B@9ad58d1, 14=[B@4313a678, 16=[B@825b660, 17=[B@66e5bb63, 18=[B@56d0cbe, 19=[B@5b135a0d}, upperBounds={1=[B@7ea061b9, 2=[B@35d5e3ad, 3=[B@58300155, 4=[B@19b2fb6c, 5=[B@64e2fc4a, 9=[B@7e30a3f0, 10=[B@26d22fca, 11=[B@2835d9e7, 12=[B@5bc66007, 13=[B@209267ac, 14=[B@1789b00b, 16=[B@1175b9fc, 17=[B@79db358d, 18=[B@4ac7821d, 19=[B@10146aa6}}}`

Fixes #33776

### CODE REVIEW

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java [hunk 1]
```diff
@@ -199,4 +203,53 @@ DataFile createDataFile(Map<Integer, PartitionSpec> partitionSpecs) {
...
+        && Objects.equals(getColumnSizes(), that.getColumnSizes())
+        && Objects.equals(getValueCounts(), that.getValueCounts())
+        && Objects.equals(getNullValueCounts(), that.getNullValueCounts())
+        && Objects.equals(getNanValueCounts(), that.getNanValueCounts())
+        && mapEquals(getLowerBounds(), that.getLowerBounds())
+        && mapEquals(getUpperBounds(), that.getUpperBounds());
+  }
+
+  private static boolean mapEquals(
+      @Nullable Map<Integer, byte[]> map1, @Nullable Map<Integer, byte[]> map2) {
```
Comment (kennknowles) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java:234]: The map isn't the issue, it is the byte[]. There may be an alternative byte buffer data structure that would have a structural equals.

Otherwise, what you need to do for `structuralValue` is wrap any mutable array. It is quite a pain.

**Review by kennknowles — CHANGES_REQUESTED** [review]

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java [hunk 2]
```diff
@@ -199,4 +203,53 @@ DataFile createDataFile(Map<Integer, PartitionSpec> partitionSpecs) {
     }
     return output;
   }
+
+  @Override
+  @SuppressWarnings("EqualsHashCode")
```
[the remark this answers is not in the document]
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java]: Thanks, I checked and saw that indeed the AutoValue hashcode is also implemented naively.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java (hunk 1 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java:233]: Right, ideally we'd be using ByteBuffer, but that currentl raises other issues. I saw your comment on the other PR and replied [here](https://github.com/apache/beam/pull/32821#issuecomment-2587384084).

**Comment by damccorm** [comment]
@kennknowles could you take another look at this one?

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java [hunk 3]
```diff
@@ -199,4 +203,105 @@ DataFile createDataFile(Map<Integer, PartitionSpec> partitionSpecs) {
...
+            return Arrays.hashCode(bytes);
+          }
+        };
+
+    return Maps.difference(map1, map2, byteArrayEquivalence).areEqual();
+  }
+
+  @Override
+  public final int hashCode() {
+    int hashCode = 1;
```
Comment (kennknowles) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java:257]: use `Objects.hashCode` I'd say

**Review by kennknowles — COMMENTED** [review]
Stepping back, can you provide context on this? We hit kind of the same issue with ByteArrayCoder and implement it with StructuralByteArray (and this is what the structuralValue method is for).

**Comment by kennknowles** [comment]
I'm OK to go ahead with this approach but it should be temporary. We shouldn't be implementing equals and hashcode manually for things like this. It is simply too error prone and is guaranteed to bite us.

Lets be sure this is done in a compatible way so we can migrate to types that "just work" with our various automations, and upgrade the automation to work with ByteBuffer. Basically Java arrays are to be avoided except in low-level cases.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java (hunk 3 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java:257]: Do you mean use `Objects.hashCode()` for each field?

FWIW I copied this over from the generated AutoValue hashcode logic

Comment (kennknowles) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java:257]: Hmmm maybe it was `Objects.hash`. Weird that Autovalue doesn't use it.

Basically, don't calculate a hash yourself but just say `Objects.hash(field1, field2, field3, ...)` to avoid coming up with your own, and making the logic very obvious.

Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/SerializableDataFile.java:257]: Done

File: sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/SerializableDataFileTest.java [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+          .add("columnSizes")
+          .add("valueCounts")
+          .add("nullValueCounts")
+          .add("nanValueCounts")
+          .add("lowerBounds")
+          .add("upperBounds")
+          .build();
+
+  @Test
+  public void testFieldsInEqualsMethodInSyncWithGetterFields() {
```
Comment (ahmedabu98) [inline sdks/java/io/iceberg/src/test/java/org/apache/beam/sdk/io/iceberg/SerializableDataFileTest.java:53]: @kennknowles added a check here with a helpful error message

**Review by kennknowles — COMMENTED** [review]
At this point we've spent more time on this than it deserves. Might as well merge it. I think at the code level the right approach is switching to the data type and fixing our codegen. This adds tech debt that is almost certain to bite us eventually, but for now we need to make some temporary progress.

**Review by kennknowles — APPROVED** [review]
