### PR TITLE
Remove constraint introduced in #30059

### LINKED ISSUE #30159: [Failing Test]: PostCommit Python Xlang Gcp Direct and Dataflow failing due to #30059
### What happened?

#30059 introduces a constraint that failing pipeline on numShards=0 for xlang BigQueryIO storage write API. However, there are tests covering this and working until this constraint is set. Likely the constraint is to broad and breaking known use case.

We should either limit the scope of the constraint or just add warning

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [X] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #30159

Unless we fully understand the limitation this kind of proactive restriction has chance to breaking existing use case.

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @lostluck @ahmedabu98 

This would need a cherry pick because it breaks Python BigQueryIO storage write.

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java [hunk 1]
```diff
@@ -383,13 +383,6 @@ public PCollectionRowTuple expand(PCollectionRowTuple input) {
         Boolean autoSharding = configuration.getAutoSharding();
         int numStreams = configuration.getNumStreams() == null ? 0 : configuration.getNumStreams();
 
-        // TODO(https://github.com/apache/beam/issues/30058): remove once Dataflow supports multiple
-        // DoFn's per fused step.
-        if (numStreams < 1) {
-          throw new IllegalStateException(
-              "numStreams must be set to a positive integer when input data is unbounded.");
-        }
```
Comment (Polber) [inline sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java:391]: This check was added because any Python SDK (or Beam Yaml) user who uses the ReadFromBigQuery with Storage API and unbounded data on Dataflow (at least) will not have data written if `numStreams` is not set to a positive integer. Digging through the logs will show there are warnings about crash loopback due to 2 stateful DoFn's not being able to be fused, but this is not a clear indicator to the issue. This check prevents the job from launching in the first place to avoid user frustration.

Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java:391]: Runner-specific checks should be done by the runner itself (in this case, this should be stopped on the Dataflow side). We'd rather not restrict all runners.

Comment (Abacn) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java:391]: This check is too broad and breaking exisiting tests has been working on direct runner and dataflow:  https://github.com/apache/beam/runs/20839188440 https://github.com/apache/beam/runs/20815247023

On the other hand, there was a similar restriction added to Dataflow side also breaks users and have been rolled back: b/322741233

We were yet to fully understand the cause of "crash loopback ". Using GroupIntoBatches with autosharding alone won't cause issue

Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java:391]: P.S. when DataflowRunner V2 gets fixed, users will be able to set autosharding. If we restrict it on this Beam version, we unnecessarily mark the version as unusable for autosharding even with a fixed Runner V2.

**Review by ahmedabu98 — APPROVED** [review]

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java (hunk 1 above)
Comment (Polber) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/providers/BigQueryStorageWriteApiSchemaTransformProvider.java:391]: Both really good points. I just wanted there to be a way to fail earlier (unfortunately xlang doesn't pick up runner implementation from what I could see to check dataflow specifically, but sounds like that isn't feasible. LGTM
