### PR TITLE
make Coder.getEncodedElementByteSize public to allow performance improvements in higher level coders

### LINKED ISSUE #33620: [Bug]: StateBackedIterable serializes elements size for every element when ComposedCombine is used
### What happened?

StateBackedIterable which is part of FnHarness is reporting size for every element without looking at cost of encoding. Other parts of SDK take into account isRegisterByteSizeObserverCheap and depending on response they sample. 

To reproduce:
1. Implement ComposedCombine with 1k of accumulators
2. Create input of millions of elements
3. Combine globally. 
4. Run on Dataflow v2

Straggler - "Operation ongoing" with following stacktrace fragment:

```

[..]
 at app//org.apache.beam.sdk.transforms.CombineFns$ComposedAccumulatorCoder.encode(CombineFns.java:649)
  at app//org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:297)
  at app//org.apache.beam.sdk.coders.LengthPrefixCoder.getEncodedElementByteSize(LengthPrefixCoder.java:109)
  at app//org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
  at app//org.apache.beam.fn.harness.state.StateBackedIterable$WrappedObservingIterator.next(StateBackedIterable.java:141)
  at app//org.apache.beam.sdk.transforms.CombineFns$ProjectionIterable$1.next(CombineFns.java:638)
  at app//com.google.common.collect.Iterators$5.computeNext(Iterators.java:672)
  at app//com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
  at app//com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
  at app//foo.bar.MyAccumulator.mergeAccumulators(MyAccumulator.java:418)
[..]

```

Expected outcome - no straggler. 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [x] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by stankiewicz**
Fixes #33620

Half of the sdk coders have getEncodedElementByteSize  public because they are invoked outside of beam.sdk.coders package. 
Some accumulators like ComposedAccumulatorCoder should have access to optimized methods for calculating size but due to it can be any Coder.
Optimized way of calculating size shouldn't be limited to Coders implemented in beam.sdk.coders only.
This change changes it to public and fixes all the coders in beam sdk.

This will break coders implemented in customer codebase requiring small patch to change visibility.

### CODE REVIEW

**Comment by stankiewicz** [comment]
Run Java PreCommit

**Comment by stankiewicz** [comment]
Run Java PreCommit

**Comment by stankiewicz** [comment]
Alternative to breaking change would be keeping things as is and moving problematic accumulator to sdk but it won't help if someone else writes problematic coder outside of beam.

File: sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/CombineFns.java [hunk 1]
```diff
@@ -674,6 +674,26 @@ public void encode(Object[] value, OutputStream outStream, Coder.Context context
...
 
+    @Override
+    public long getEncodedElementByteSize(Object[] value) throws Exception {
+      if (value.length == 0) {
+        return 0;
+      }
+      long size = 0;
+      for (int i = 0; i < value.length; ++i) {
+        Coder<Object> objectCoder = coders.get(i);
+        if (objectCoder instanceof StructuredCoder) {
```
Comment (stankiewicz) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/CombineFns.java:685]: I've seen this type of condition[here](https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/coders/LengthPrefixCoder.java#L106). StructuredCoder doesn't enforce overriding getEncodedElementByteSize so I'm not sure if this is best practice. Ideally I would like to loop and invoke this method for every coder on the list. If underlying coder has default implementation, it will just serialize as is.

Comment (robertwb) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/CombineFns.java:685]: I would remove the typecheck on StructuredCoder, just loop and add for every coder. The only downside is that there may be overhead constructing multiple CountingOutputStreams rather than creating one, but as you say there's no contract between StructuredCoder and implementing getEncodedElementByteSize. 

Go ahead and remove the check in LengthPrefixCoder too, there's no benefit for ever skipping this attempt.

**Review by robertwb — COMMENTED** [review]
I am a bit concerned about the backwards incompatibility implications of changing the visibility here. If we do need to call it from outside a Coder (which seems OK to me), what if we instead make a public static method on Coder that calls this?

File: sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/CombineFns.java (hunk 1 above)
Comment (stankiewicz) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/CombineFns.java]: @robertwb thanks, changed.

**Comment by stankiewicz** [comment]
> I am a bit concerned about the backwards incompatibility implications of changing the visibility here. If we do need to call it from outside a Coder (which seems OK to me), what if we instead make a public static method on Coder that calls this?

added static method, thanks for suggestions!

**Comment by stankiewicz** [comment]
Run Java_IOs_Direct PreCommit

**Comment by stankiewicz** [comment]
Run Java PreCommit

**Comment by stankiewicz** [comment]
Run Java PreCommit

**Comment by stankiewicz** [comment]
Run Java PreCommit

File: sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java [hunk 2]
```diff
@@ -198,6 +198,9 @@ public static void verifyDeterministic(Coder<?> target, String message, Iterable
     }
   }
 
+  public static <T> long getEncodedElementByteSizeUsingCoder(Coder<T> target, T value) throws Exception {
```
Comment (robertwb) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java:201]: We probably don't need the UsingCoder suffix, the signature is different so the overload will be unambiguous.

**Review by robertwb — APPROVED** [review]

File: sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java (hunk 2 above)
Comment (robertwb) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/coders/Coder.java:201]: Looks like Java doesn't allow this.
