### PR TITLE
[Managed Iceberg] Add support for TIMESTAMP, TIME, and DATE types

### LINKED ISSUE #32680: [Bug]: IcebergIO cannot write Timestamp columns
### What happened?

When Trying to write timestamp data into an Iceberg Table I get the following exception:
```
Caused by: java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.time.OffsetDateTime (java.lang.Long and java.time.OffsetDateTime are in module java.base of loader 'bootstrap')
        at org.apache.iceberg.data.parquet.BaseParquetWriter$TimestamptzWriter.write(BaseParquetWriter.java:281)
        at org.apache.iceberg.parquet.ParquetValueWriters$OptionWriter.write(ParquetValueWriters.java:356)
        at org.apache.iceberg.parquet.ParquetValueWriters$StructWriter.write(ParquetValueWriters.java:589)
        at org.apache.iceberg.parquet.ParquetWriter.add(ParquetWriter.java:135)
        at org.apache.iceberg.io.DataWriter.write(DataWriter.java:71)
        at org.apache.beam.sdk.io.iceberg.RecordWriter.write(RecordWriter.java:105)
        at org.apache.beam.sdk.io.iceberg.RecordWriterManager$DestinationState.write(RecordWriterManager.java:144)
        at org.apache.beam.sdk.io.iceberg.RecordWriterManager.write(RecordWriterManager.java:234)
        at org.apache.beam.sdk.io.iceberg.WriteUngroupedRowsToFiles$WriteUngroupedRowsToFilesDoFn.processElement(WriteUngroupedRowsToFiles.java:224)
        Suppressed: java.lang.IllegalArgumentException: Expected all data writers to be closed, but found 1 data writer(s) still open
```

Source code: 
```
import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.managed.Managed;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.apache.beam.sdk.schemas.Schema;
import org.apache.beam.sdk.transforms.Create;
import org.apache.beam.sdk.values.Row;
import org.joda.time.Instant;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

public class HardcodedDataToIcebergPipeline {

    public static void main(String[] args) {
        // Define Beam pipeline options
        PipelineOptions options =
                PipelineOptionsFactory.fromArgs(args).withValidation().as(PipelineOptions.class);
        Pipeline pipeline = Pipeline.create(options);

        // Define Beam schema with a timestamp field
        Schema beamSchema = Schema.builder()
                .addStringField("id")
                .addDateTimeField("event_timestamp")
                .build();
        
        Map<String, Object> catalogConfig = new HashMap<String, Object>() {{
            put("warehouse", "<warehouse-dir>");
            put("uri", "<thrift-uri>");
            put("type", "iceberg");
            put("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem");
            put("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS");
        }};

        Map<String, Object> icebergConfig = new HashMap<String, Object>() {{
            put("catalog_name", appConfig.get("catalog"));
            put("catalog_properties", catalogConfig);
        }};
        String table = String.format("%s.%s", "myschema", "test");
        icebergConfig.put("table", table);

        // Create hardcoded data with timestamp
        List<Row> hardcodedData = Arrays.asList(
                Row.withSchema(beamSchema)
                        .addValues("record-1", Instant.now()) // Use Joda-Time Instant
                        .build(),
                Row.withSchema(beamSchema)
                        .addValues("record-2", Instant.now().minus(3600 * 1000)) // 1 hour ago
                        .build(),
                Row.withSchema(beamSchema)
                        .addValues("record-3", Instant.now().minus(24 * 3600 * 1000)) // 1 day ago
                        .build()
        );

        // Build the pipeline using the hardcoded data
        pipeline
                .apply("CreateHardcodedData", Create.of(hardcodedData).withRowSchema(beamSchema)) // Hardcoded 
                .apply("WriteToIceberg", Managed.write(Managed.ICEBERG).withConfig(icebergConfig));

        // Run the pipeline
        pipeline.run().waitUntilFinish();
    }
}
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixes #32680

### CODE REVIEW

**Comment by ahmedabu98** [comment]
assign set of reviewers

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java [hunk 1]
```diff
@@ -282,12 +306,24 @@ private static void copyFieldIntoRecord(Record rec, Types.NestedField field, Row
...
-        throw new UnsupportedOperationException("Time fields not yet supported");
+        Optional.ofNullable(value.getLogicalTypeValue(name, LocalTime.class))
+            .ifPresent(v -> rec.setField(name, v));
+        break;
       case TIMESTAMP:
-        Optional.ofNullable(value.getDateTime(name))
-            .ifPresent(v -> rec.setField(name, v.getMillis()));
+        Object val = value.getValue(name);
+        if (val instanceof Instant) { // case Schema.FieldType.DATETIME
+          rec.setField(name, DateTimeUtil.timestampFromMicros(((Instant) val).getMillis()));
```
Comment (DanielMorales9) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:319]: `DateTimeUtil.timestampFromMicros` expect microseconds, but you're passing milliseconds. If it expects microseconds, you may need to convert milliseconds to microseconds.

Counter-example:

```
import org.apache.iceberg.util.DateTimeUtil;
import org.joda.time.Instant;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import java.time.LocalDateTime;
import java.time.ZoneId;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;

@RunWith(JUnit4.class)
public class DateTimeUtilsTest {

    @Test
    public void when_DatetimeUtils_TimestampFromMicros_Receives_A_Millis() {
        String timestampStr = "2024-10-07T12:34:56Z";
        Instant instant = Instant.parse(timestampStr);
        LocalDateTime actual = DateTimeUtil.timestampFromMicros(instant.getMillis());

        java.time.Instant javaInstant = java.time.Instant.parse(timestampStr);
        LocalDateTime expected = LocalDateTime.ofInstant(javaInstant, ZoneId.of("UTC"));

        assertThat(actual, equalTo(expected));
    }
}

```

Outcome:
```
java.lang.AssertionError: 
Expected: <2024-10-07T12:34:56>
     but: was <1970-01-21T00:05:04.496>

Comment (DanielMorales9) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:319]: I’ve noticed that the current implementation consistently converts Beam timestamps into java.time.LocalDateTime. However, this approach could lead to issues depending on whether the corresponding Iceberg table column is defined with or without a time zone. Specifically, it may lead to the similar ClassCastException we are currently encountering.

Are you considering adding additional integration tests to address these scenarios?

For your reference, here are a couple of links to the relevant Apache Iceberg / Parquet source code that illustrate the handling of timestamps:

[Iceberg BaseParquetWriter Line 212](https://github.com/apache/iceberg/blob/229d8f6fcd109e6c8943ea7cbb41dab746c6d0ed/parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetWriter.java#L212)

[Iceberg BaseParquetWriter Line 288](https://github.com/apache/iceberg/blob/229d8f6fcd109e6c8943ea7cbb41dab746c6d0ed/parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetWriter.java#L288)

Comment (DanielMorales9) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:319]: You may want to take a look at how Iceberg implemented it for the Spark Runtime. 

[Iceberg Spark Timestamp conversions](https://github.com/apache/iceberg/blob/208ab20dc9ab8bcab3ee525d0ddaba80eeae7609/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java#L138)

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java [hunk 2]
```diff
@@ -54,6 +58,14 @@ private IcebergUtils() {}
...
           .put(Schema.TypeName.STRING, Types.StringType.get())
           .put(Schema.TypeName.BYTES, Types.BinaryType.get())
+          .put(Schema.TypeName.DATETIME, Types.TimestampType.withoutZone())
+          .build();
+
+  private static final Map<String, Type> BEAM_LOGICAL_TYPES_TO_ICEBERG_TYPES =
+      ImmutableMap.<String, Type>builder()
+          .put(SqlTypes.DATE.getIdentifier(), Types.DateType.get())
+          .put(SqlTypes.TIME.getIdentifier(), Types.TimeType.get())
+          .put(SqlTypes.DATETIME.getIdentifier(), Types.TimestampType.withoutZone())
```
Comment (DanielMorales9) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:68]: Does that mean that beam doesn't support Timezone timestamps?

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java (hunk 1 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:319]: Great catch! and thanks for all the info and references.

I've been digging for some time and found that Beam has two field types that represent timestamps:
`SqlTypes.DATETIME` -- uses java.time.LocalDateTime 
`FieldType.DATETIME` -- uses org.joda.time.DateTime 

DateTime supports timezone information, but Beam itself doesn't. When this object gets processed in a Beam Row, the timezone information is dropped. Fetching the object will always return a timestamp from UTC.

Because of this, I don't think the connect can support timestamp with TZ yet

Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:319]: Actually we might be able to support it by letting the user provide String timestamp representations. We can parse these strings into date time objects then write to Iceberg. Will look into this route soon

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java (hunk 2 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:69]: Added support for timezone timestamps with strings

Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:69]: Btw I noticed that when reading `timestamptz` types from Iceberg, the timestamp is always returned in UTC.

I wonder if it's something I'm doing on my side, or if this is expected Iceberg behavior

Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:69]: Ah looks like this is standard Iceberg behavior. From [docs](https://iceberg.apache.org/spec/#primitive-types):

`Timestamp values with time zone represent a point in time: values are stored as UTC and do not retain a source time zone (2017-11-16 17:10:34 PST is stored/retrieved as 2017-11-17 01:10:34 UTC and these values are considered identical)`

**Comment by ahmedabu98** [comment]
Thanks for taking an initial look @DanielMorales9. This PR is ready for another review

**Comment by ahmedabu98** [comment]
@robertwb @Abacn @shunping this could also use some eyes from Beam devs

**Comment by ahmedabu98** [comment]
Beam (`FieldType.DATETIME`) and Iceberg (`timestamptz`) handle timestamps with timezone in a similar way -- they resolve to UTC and drop the timezone information.

I added support for String timestamps to be parsed to OffsetDateTime. But I wonder if it makes sense to allow other types as well (LocalDateTime, joda DateTime, long) and resolve all these types to OffsetDateTime at UTC. This will allow us to have a more unified approach to timestamps - and Iceberg will resolve to UTC anyways

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java (hunk 2 above)
Comment (DanielMorales9) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:68]: Yes, it's expected behaviour. 

Iceberg stores both TS and NTZ as UTC and it's up to the engine to do the required conversions from their internal TS representation. So, it is actually okay if it's NTZ.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java [hunk 3]
```diff
@@ -282,12 +306,50 @@ private static void copyFieldIntoRecord(Record rec, Types.NestedField field, Row
...
+        // timestamp with timezone
+        if (ts.shouldAdjustToUTC()) {
+          // currently only string is supported because other types
+          // do not maintain timezone information
+          if (val instanceof String) {
+            // e.g. 2007-12-03T10:15:30+01:00
+            rec.setField(name, OffsetDateTime.parse((String) val));
+            break;
+          } else {
+            throw new UnsupportedOperationException(
```
Comment (DanielMorales9) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:331]: As you mentioned already [here](https://github.com/apache/beam/pull/32688#issuecomment-2402624470), I'd also like to have the option to convert `Instant` and `LocalDateTime` into `OffsetDateTime` at UTC. It will be a lossless conversion and users won't be forced to use Strings.

Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java]: I refactored the conversion logic so that now, any of these types can write to both `timestamp` and `timestamptz`:
- Schema.FieldType.INT64         --> long
- Schema.FieldType.INT64.        --> String
- Schema.FieldType.DATETIME  --> org.joda.time.DateTime
- SqlTypes.DATETIME                  --> java.time.LocalDateTime 

When writing to `timestamptz`, we will resolve to UTC first before writing. Lmk how things look now. I updated the java doc as well with more details

Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java]: And when reading, these are the mappings:
- `timestamp` --> SqlTypes.DATETIME
- `timestamptz` --> Schema.FieldType.DATETIME

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java [hunk 4]
```diff
@@ -345,16 +426,31 @@ public static Row icebergRecordToBeamRow(Schema schema, Record record) {
...
         case ARRAY:
         case ITERABLE:
         case MAP:
           rowBuilder.addValue(icebergValue);
           break;
         case DATETIME:
-          // Iceberg uses a long for millis; Beam uses joda time DateTime
-          long millis = (long) icebergValue;
-          rowBuilder.addValue(new DateTime(millis, DateTimeZone.UTC));
+          long micros;
```
Comment (DanielMorales9) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:436]: nit: this logic could be wrapped into a private method: `getBeamDatetimeValue`

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java (hunk 3 above)
Comment (DanielMorales9) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java]: Yes, thank you. It makes a lot of sense to me 👍

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java [hunk 5]
```diff
@@ -322,6 +354,55 @@ private static void copyFieldIntoRecord(Record rec, Types.NestedField field, Row
...
+   * <p>Valid types are:
+   *
+   * <ul>
+   *   <li>{@link SqlTypes.DATETIME} --> {@link LocalDateTime}
+   *   <li>{@link Schema.FieldType.DATETIME} --> {@link Instant}
+   *   <li>{@link Schema.FieldType.INT64} --> {@link Long}
+   *   <li>{@link Schema.FieldType.STRING} --> {@link String}
+   * </ul>
+   */
+  private static Object getIcebergTimestampValue(Object beamValue, boolean shouldAdjustToUtc) {
```
Comment (DanielMorales9) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:374]: Imho, method overloading makes the code cleaner and easier to follow and it avoids type-checking blocks (e.g., instanceof), reducing complexity. 

 ```
private static Object getIcebergTimestampValue(Object beamValue, boolean shouldAdjustToUtc) {
    if (shouldAdjustToUtc) {
        return convertBeamTimestampToUTC(beamValue);
    } else {
        return convertBeamTimestampWithoutUTC(beamValue);
    }
}

// Overloaded methods for different types for UTC conversion
private static Object convertBeamTimestampToUTC(LocalDateTime beamValue) {
    return OffsetDateTime.of(beamValue, ZoneOffset.UTC);
}

private static Object convertBeamTimestampToUTC(Instant beamValue) {
    return DateTimeUtil.timestamptzFromMicros(beamValue.toEpochMilli() * 1000L);
}

private static Object convertBeamTimestampToUTC(Long beamValue) {
    return DateTimeUtil.timestamptzFromMicros(beamValue);
}

private static Object convertBeamTimestampToUTC(String beamValue) {
    return OffsetDateTime.parse(beamValue).withOffsetSameInstant(ZoneOffset.UTC);
}

// Overloaded methods for different types for non-UTC conversion
private static Object convertBeamTimestampWithoutUTC(LocalDateTime beamValue) {
    return beamValue;
}

private static Object convertBeamTimestampWithoutUTC(Instant beamValue) {
    return DateTimeUtil.timestampFromMicros(beamValue.toEpochMilli() * 1000L);
}

private static Object convertBeamTimestampWithoutUTC(Long beamValue) {
    return DateTimeUtil.timestampFromMicros(beamValue);
}

private static Object convertBeamTimestampWithoutUTC(String beamValue) {
    return LocalDateTime.parse(beamValue);
}

// Fallback method for unsupported types
private static Object convertBeamTimestampToUTC(Object beamValue) {
    throw unsupportedBeamTimestamp(beamValue);
}

private static Object convertBeamTimestampWithoutUTC(Object beamValue) {
    throw unsupportedBeamTimestamp(beamValue);
}

private static UnsupportedOperationException unsupportedBeamTimestampException(Object beamValue) {
    return new UnsupportedOperationException(
        "Unsupported Beam type for Iceberg timestamp: " + beamValue.getClass().getName());
}
```

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java (hunk 3 above)
Comment (DanielMorales9) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java]: LGTM, I left few minor comments, Thank you

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java (hunk 5 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:374]: Thanks, I tried this but it seems to always pick `convertBeamTimestampToUTC(Object beamValue)`. Java's method overloading is static polymorphism, meaning the method is determined at compile time, not runtime. Unfortunately we don't know the type of `beamValue` at compile time so it's always treated as an `Object`.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java (hunk 4 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/IcebergUtils.java:436]: good call, done

**Comment by ahmedabu98** [comment]
Thanks for the LGTM -- will merge when tests pass
