### PR TITLE
[Playground] Guard router methods from being executed on runners

### LINKED ISSUE #25929: [Bug]: Backend crash when GetPrecompiledObjects() is called on a runner instance
### What happened?

Runner instance segfaults when we invoke `GetPrecompiledObjects()` endpoint on it. This endpoint is not supported by runner instances and should be ignored instead of crashing the instance fully.

### Issue Priority

Priority: 2

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by TSultanov**
Exit immediately from controller methods which should not be executed when the backend is running in a runner mode

resolves #25929

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by olehborysevych — APPROVED** [review]

**Comment by olehborysevych** [comment]
LGTM

File: playground/backend/cmd/server/controller_test.go [hunk 1]
```diff
@@ -64,18 +64,19 @@ const (
...
 var ctx context.Context
 
 func TestMain(m *testing.M) {
-	server := setup()
-	opt = goleak.IgnoreCurrent()
+	//server := setup()
+	//opt = goleak.IgnoreCurrent()
 	exitValue := m.Run()
-	teardown(server)
+	//teardown(server)
```
Comment (damccorm) [inline playground/backend/cmd/server/controller_test.go:75]: Instead of making these comments, can we just remove them?

**Review by damccorm — COMMENTED** [review]
Just one nit, otherwise LGTM
