### PR TITLE
Calculate byte size via sampling in StateBackedIterable if size is not cheap to calculate

### LINKED ISSUE #33620: [Bug]: StateBackedIterable serializes elements size for every element when ComposedCombine is used
### What happened?

StateBackedIterable which is part of FnHarness is reporting size for every element without looking at cost of encoding. Other parts of SDK take into account isRegisterByteSizeObserverCheap and depending on response they sample. 

To reproduce:
1. Implement ComposedCombine with 1k of accumulators
2. Create input of millions of elements
3. Combine globally. 
4. Run on Dataflow v2

Straggler - "Operation ongoing" with following stacktrace fragment:

```

[..]
 at app//org.apache.beam.sdk.transforms.CombineFns$ComposedAccumulatorCoder.encode(CombineFns.java:649)
  at app//org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:297)
  at app//org.apache.beam.sdk.coders.LengthPrefixCoder.getEncodedElementByteSize(LengthPrefixCoder.java:109)
  at app//org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
  at app//org.apache.beam.fn.harness.state.StateBackedIterable$WrappedObservingIterator.next(StateBackedIterable.java:141)
  at app//org.apache.beam.sdk.transforms.CombineFns$ProjectionIterable$1.next(CombineFns.java:638)
  at app//com.google.common.collect.Iterators$5.computeNext(Iterators.java:672)
  at app//com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:145)
  at app//com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:140)
  at app//foo.bar.MyAccumulator.mergeAccumulators(MyAccumulator.java:418)
[..]

```

Expected outcome - no straggler. 

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [x] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by stankiewicz**
For Dataflow V2, StateBackedIterable is iterated by readers after gbk shuffle. Examples are ParDo after GBK or merging combiners after GBK. 

[metrics.proto](https://github.com/apache/beam/blob/master/model/pipeline/src/main/proto/org/apache/beam/model/pipeline/v1/metrics.proto#L244) specifies that Sampling is used  because calculating the byte count involves serializing the elements which is CPU intensive. 

In case of StateBackedIterable sampling is not occurring which impacts performance of some of the pipelines that have expensive coders.

This change introduces sampling. 

Fully fixes #33620 as previous fix was improvement.

### CODE REVIEW

**Comment by stankiewicz** [comment]
Run Java PreCommit

File: sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java [hunk 1]
```diff
@@ -269,7 +269,8 @@ public void testByteObservingStateBackedIterable() throws Exception {
               .sum();
       observer.advance();
       // 5 comes from size and hasNext (see IterableLikeCoder)
-      assertEquals(iterateBytes + 5, observer.total);
+      // observer receives scaled
+      assertTrue(iterateBytes + 5 >= observer.total);
```
Comment (scwhittle) [inline sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java:273]: is it less than 10 elements? shoudln't it be exact in that case?

If it's off by some double-math errors you could use some fuzzy equals (https://guava.dev/releases/23.0/api/docs/com/google/common/math/DoubleMath.html#fuzzyEquals-double-double-double- for example but perhaps some testing assert variant exists)

**Review by scwhittle — CHANGES_REQUESTED** [review]

File: sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java (hunk 1 above)
Comment (stankiewicz) [reply sdks/java/harness/src/test/java/org/apache/beam/fn/harness/state/StateBackedIterableTest.java]: it's more than 10 elements, added assert with tolerance.

**Comment by stankiewicz** [comment]
Run Java_PVR_Flink_Docker PreCommit

File: sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java [hunk 2]
```diff
@@ -138,15 +157,19 @@ public boolean hasNext() {
...
-        elementCoder.registerByteSizeObserver(value, observerProxy);
-        if (observerProxy.getIsLazy()) {
-          // The observer will only be notified of bytes as the result
-          // is used. We defer advancing the observer until hasNext in an
-          // attempt to capture those bytes.
-          observerNeedsAdvance = true;
-        } else {
-          observerNeedsAdvance = false;
-          observerProxy.advance();
+        if (sampleElement() || elementCoder.isRegisterByteSizeObserverCheap(value)) {
```
[the remark this answers is not in the document]
Comment (stankiewicz) [reply sdks/java/harness/src/main/java/org/apache/beam/fn/harness/state/StateBackedIterable.java]: done. I will fix OutputObjectAndByteCounter in next pr.

**Review by scwhittle — CHANGES_REQUESTED** [review]

**Comment by stankiewicz** [comment]
Run Java PreCommit

**Comment by stankiewicz** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by stankiewicz** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by stankiewicz** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by stankiewicz** [comment]
Run Java PreCommit

**Comment by stankiewicz** [comment]
Run Java_PVR_Flink_Docker PreCommit

**Comment by stankiewicz** [comment]
Run Java PreCommit

**Comment by stankiewicz** [comment]
Run Java PreCommit

**Comment by stankiewicz** [comment]
flaky tests: https://develocity.apache.org/scans/tests?search.timeZoneId=Europe%2FWarsaw&tests.container=org.apache.beam.runners.dataflow.worker.windmill.client.grpc.GrpcDirectGetWorkStreamTest&tests.test=testConsumedWorkItems_itemsSplitAcrossResponses&tests.unstableOnly=false

**Review by scwhittle — APPROVED** [review]
