### PR TITLE
[BEAM-14525] / #21626 Fix for Protobuf getter/setter method name discovery issue

### LINKED ISSUE #21626: Unable to find Proto getters in certain cases
Proto property name: *item2partner_id* 

Generated java library method names:
 * *hasItem2PartnerId*
 * *getItem2PartnerId*
 * *setItem2PartnerId*
 * *clearItem2PartnerId*

org.apache.beam.sdk.extensions.protobuf.ProtoByteBuddyUtils generated getter name:
 * *getItem2partnerId*

 

Notice the case difference of 'p'. The getter method name creation isn't aligned with protobuf standards.

See:
 - [https://github.com/protocolbuffers/protobuf/blob/ec79d0d328c7e6cea15cc27fbeb9b018ca289590/src/google/protobuf/compiler/java/helpers.cc#L246-L248](https://github.com/protocolbuffers/protobuf/blob/ec79d0d328c7e6cea15cc27fbeb9b018ca289590/src/google/protobuf/compiler/java/helpers.cc#L246-L248)

 - [https://github.com/protocolbuffers/protobuf/blob/ec79d0d328c7e6cea15cc27fbeb9b018ca289590/src/google/protobuf/compiler/java/helpers.cc#L173-L208](https://github.com/protocolbuffers/protobuf/blob/ec79d0d328c7e6cea15cc27fbeb9b018ca289590/src/google/protobuf/compiler/java/helpers.cc#L173-L208)

 

According this logic anything that isn't A-Za-z makes the next character uppercase.

Imported from Jira [BEAM-14525](https://issues.apache.org/jira/browse/BEAM-14525). Original Jira may contain additional context.
Reported by: bnemeth.

### PR DESCRIPTION
**Pull request by nbali**
https://issues.apache.org/jira/browse/BEAM-14525

Closes #21626.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Format the pull request title like `[BEAM-XXX] Fixes bug in ApproximateQuantiles`, where you replace `BEAM-XXX` with the appropriate JIRA issue, if applicable. This will automatically link the pull request to the issue.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - ~[ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by nbali** [comment]
R: @aaltay

**Comment by aaltay** [comment]
R: @reuvenlax - and in case he does not have time, R: @kileys

File: sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java [hunk 1]
```diff
@@ -190,15 +191,59 @@ class ProtoByteBuddyUtils {
...
   private static final String DEFAULT_PROTO_SETTER_PREFIX = "set";
 
+  // BEAM-14525: there is a slight difference between 'protoc' and Guava CaseFormat regarding the
+  // camel case conversion
+  // - guava keeps the first character after a number lower case
+  // - protoc makes it upper case
+  // based on
+  // https://github.com/protocolbuffers/protobuf/blob/ec79d0d328c7e6cea15cc27fbeb9b018ca289590/src/google/protobuf/compiler/java/helpers.cc#L173-L208
+  @VisibleForTesting
+  static String convertProtoPropertyNameToJavaPropertyName(String input) {
```
Comment (kileys) [inline sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java:201]:
```suggestion
  static String underscoreToUpperCamel(String input) {
```

File: sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java [hunk 2]
```diff
@@ -190,15 +191,59 @@ class ProtoByteBuddyUtils {
   private static final String DEFAULT_PROTO_GETTER_PREFIX = "get";
   private static final String DEFAULT_PROTO_SETTER_PREFIX = "set";
 
+  // BEAM-14525: there is a slight difference between 'protoc' and Guava CaseFormat regarding the
+  // camel case conversion
+  // - guava keeps the first character after a number lower case
+  // - protoc makes it upper case
+  // based on
+  // https://github.com/protocolbuffers/protobuf/blob/ec79d0d328c7e6cea15cc27fbeb9b018ca289590/src/google/protobuf/compiler/java/helpers.cc#L173-L208
```
Comment (kileys) [inline sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java:199]:
```suggestion
  // Convert properties from lower case underscore to upper case camel case.
  // [BEAM-14525] Needed because protoc capitalizes the first letter after a digit
  // whereas Guava CaseFormat keeps it lower case.
  // Based on:
  // https://github.com/protocolbuffers/protobuf/blob/ec79d0d328c7e6cea15cc27fbeb9b018ca289590/src/google/protobuf/compiler/java/helpers.cc#L173-L208
```

**Comment by aaltay** [comment]
Thank you for reviewing @kileys !

File: sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java (hunk 1 above)
Comment (nbali) [reply sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java:201]: I originally went a name similar to this, but decided in favor of another for multiple reasons:
- there seems to be no standard regarding conversion between various case formats - therefore this name isn't necessarily accurate -
- it's not even guaranteed that the proto property is in lower underscore (foo2bar should be foo_2_bar IMO)
- it's also not determined if foo2bar should be Foo2Bar or Foo2bar, there are converters for both cases

I prefer to name methods as accurately as possible according to their behaviour and not regarding an implementation detail. The method name I proposed is accurate. The fact that the conversion (almost looks like or) is a lower underscore to upper camel case is an implementation detail and irrelevant. Also as it's not a standard can't be 100% accurate. Especially that ignores any special (non-alphanumeric) characters I really doubt thats how that conversion should work - so IMO it would be a bad idea for anyone to call it who needs a lower underscore to upper camel conversion.

Comment (nbali) [reply sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java:201]: @kileys

Comment (nbali) [reply sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java:201]: @aaltay @kileys I'm kinda lost now. If this is going to be a discussion, then turns taking weeks is going make it quite a long one for a bugfix.

Comment (nbali) [reply sdks/java/extensions/protobuf/src/main/java/org/apache/beam/sdk/extensions/protobuf/ProtoByteBuddyUtils.java:201]: @aaltay @kileys I'm kinda lost now. If this is going to be a discussion, then turns taking weeks is going make it quite a long one for a bugfix.

**Comment by kileys** [comment]
LGTM. Could you resolve conflict and update the Jira to Github issue? Thanks

**Comment by nbali** [comment]
Run Java PreCommit

**Comment by nbali** [comment]
@kileys  I'm done, and haven't checked the code that throws the failure. -.-

**Comment by nbali** [comment]
Run Java PreCommit

**Comment by nbali** [comment]
Run Java PreCommit

**Comment by nbali** [comment]
Run Java PreCommit
