### PR TITLE
Use vendored calcite 1.40

### LINKED ISSUE #26403: Update vendored calcite to eliminate vulnerability from shaded log4j:1.2.17 and protobuf-java:3.19.2
### What would you like to happen?

Hi team,

The beam-vendor-calcite-1_28_0 contains a bunch of shaded dependencies with major security vulnerabilities. For example, 
[log4j:1.2.17](https://mvnrepository.com/artifact/log4j/log4j/1.2.17) and [protobuf-java:3.19.2](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/3.19.2). 

Are there any plans to upgrade the vendored calcite? 

We are using [beam-sdks-java-extensions-sql:2.46.0](https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-extensions-sql/2.46.0)  and [beam-sdks-java-extensions-sql—zetasql:2.46.0](https://mvnrepository.com/artifact/org.apache.beam/beam-sdks-java-extensions-sql-zetasql/2.46.0) dependencies in our code. We use [SqlTransform](https://github.com/apache/beam/blob/db8db0b6ed0fe1e4891f207f0f7f811798e54db1/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/SqlTransform.java) class which internally references classes from beam-vendor-calcite-1_28_0. 

Looks like beam-vendor-calcite is created as fat-jar, and the log4j:1.2.17 is shaded into this beam-vendor-calcite-1_28_0:0.2. So, we cannot exclude log4j:1.2.17 from this vendor jar and we cannot even override it with the latest versions either.
We cannot use any other beam-vendor-calcite version as beam-vendor-calcite-1_28_0:0.2 is the latest version.
We cannot exclude beam-vendor-calcite because internally SqlTransform class references classes from beam-vendor-calcite-1_28_0 such as [org.apache.beam.vendor.calcite.v1_28_0.com.google.common.collect.ImmutableList](https://github.com/apache/beam/blob/db8db0b6ed0fe1e4891f207f0f7f811798e54db1/sdks/java/extensions/sql/src/main/java/org/apache/beam/sdk/extensions/sql/SqlTransform.java#L48).

And, if we include this vendor jar, it gets flagged vulnerable by our security scan due to shaded log4j:1.2.17.
Hence, it would be really helpful if the log4j:1.2.17 was excluded or replaced with its latest version in beam-vendor-calcite-1_28_0.

Please note that there are more vulnerable dependencies shaded in beam-vendor-calcite-1_28_0, but log4j:1.2.17 is currently the most critical one:

- [com.google.protobuf:protobuf-java:3.19.2](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java/3.19.2)
- [com.google.protobuf:protobuf-java-util:3.19.2](https://mvnrepository.com/artifact/com.google.protobuf/protobuf-java-util/3.19.2)
- [net.minidev:json-smart:2.3](https://mvnrepository.com/artifact/net.minidev/json-smart/2.3)
- [org.yaml:snakeyaml:1.24](https://mvnrepository.com/artifact/org.yaml/snakeyaml/1.24)
- [commons-io:commons-io:2.4](https://mvnrepository.com/artifact/commons-io/commons-io/2.4)
- [com.fasterxml.jackson.core:jackson-databind:2.10.0](https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind/2.10.0)
- [com.google.code.gson:gson:2.8.6](https://mvnrepository.com/artifact/com.google.code.gson/gson/2.8.6)

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### LINKED ISSUE #35483: [Task]: Upgrade calcite to a more recent version
Hello, 

The current project is using Calcite version **1.28.0,** which was released over 4 years ago. This version is outdated and lacks support for several important features, particularly for BigQuery and other SQL dialects.

There is also an opportunity to improve consistency in the current approach: while ZetaSQL is being deprecated due to the lack of updates and new releases, Calcite has also not been updated for quite some time, despite its aging version.

Proposed Solution:
Upgrade the Calcite dependency to the latest stable version to take advantage of the following:

- Enhanced support for BigQuery and other SQL dialects.

- Access to a broader range of SQL functions and operators.

- Improved performance, bug fixes, and compatibility with modern technologies.

**Impact**:
Updating Calcite will improve the project's compatibility with BigQuery and provide access to more advanced SQL functionality. However, the upgrade may require testing to ensure that the changes do not introduce regressions or compatibility issues.

This issue is related to the ongoing work in [apache/beam#35472](https://github.com/apache/beam/pull/35472)

Thank you to the community for the great work so far—this suggestion aims to build on your solid foundation.

### Issue Priority

Priority: 2 (default / most normal work should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fix #35483, fix #26403

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlDslSqlStdOperatorsTest.java [hunk 1]
```diff
@@ -311,7 +312,7 @@ public void testArithmeticOperator() {
             .addExpr("c_double + c_bigint", 2.0)
             .addExpr("1 - 1", 0)
             .addExpr("1.0 - 1", ZERO_1)
-            .addExpr("1 - 0.0", ONE_0)
+            .addExpr("1 - 0.0", ONE_1)
```
Comment (damccorm) [inline sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlDslSqlStdOperatorsTest.java:315]: Why do we end up needing these test changes? Is there a small behavior difference here?

**Review by damccorm — APPROVED** [review]
Thanks! Had a non-blocking question (feel free to merge)

File: sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlDslSqlStdOperatorsTest.java (hunk 1 above)
Comment (Abacn) [reply sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlDslSqlStdOperatorsTest.java:315]: Yeah there are multiple behavior change like this (see the second commit, need to adjust assertions). I understand this specific test checks fixed precision numeric 1 (int) - 0.0 (fixed numeric with 1 decimal point) used to return 1 (int), now it becomes 1.0 (fixed numeric with 1 decimal point)

Comment (Abacn) [reply sdks/java/extensions/sql/src/test/java/org/apache/beam/sdk/extensions/sql/BeamSqlDslSqlStdOperatorsTest.java:315]: updated CHANGES.md to mention these kind of changes

**Review by damccorm — APPROVED** [review]
Thanks!
