### PR TITLE
Fix interface{} in iter& emit type of DoFn in Go

### LINKED ISSUE #23278: [Bug][Go SDK]: Gap in DoFn pre-processing, interface{} in iterator type of DoFn.
### What happened?

The contributed parquetio write function has a signature of: `parquetWriteFn) ProcessElement(ctx context.Context, _ int, iter func(*interface{}) bool)` which is incorrect, as "interface{}" isn't a supported PCollection type.

https://github.com/apache/beam/blob/10de67effd46d24fc4f2500012be743b3abc0f6c/sdks/go/pkg/beam/io/parquetio/parquetio.go#L150

This should have been caught at pipeline construction time regardless of whether it was registered or not, regardless of the runner used.

The resolution is two fold: Ensure that this kind of signature gets caught at pipeline construction and then also fixing the Parquetio write DoFn to not have this error.

### Issue Priority

Priority: 2

### Issue Component

Component: sdk-go

### PR DESCRIPTION
**Pull request by yyy1000**
Fix #23278
I added type checks in the core/funcx package, and now the interface{} type in iter and emit function will not work.
I tested it with function 'New' in core/funcx/fn.go and found it could work well, but I'm not pretty sure that it finished all the work.
@lostluck Could you please help me review it and find out what else should I do? I'm glad to work on it. :)

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: sdks/go/pkg/beam/core/funcx/output.go [hunk 1]
```diff
@@ -84,6 +84,9 @@ func unfoldEmit(t reflect.Type) ([]reflect.Type, bool, error) {
 		if ok, err := isInParam(t.In(i)); !ok {
 			return nil, false, errors.Wrap(err, errIllegalParametersInEmit)
 		}
+		if t.In(i).Kind() == reflect.Interface || (t.In(i).Kind() == reflect.Pointer && t.In(i).Elem().Kind() == reflect.Interface) {
+			panic("Type interface{} isn't a supported PCollection type")
```
Comment (lostluck) [inline sdks/go/pkg/beam/core/funcx/output.go:88]: If there's an error return, one should return an error instead of panicking. Panicking is generally a last resort thing, and rarely when one can return an error instead.

File: sdks/go/pkg/beam/core/funcx/output.go [hunk 2]
```diff
@@ -84,6 +84,9 @@ func unfoldEmit(t reflect.Type) ([]reflect.Type, bool, error) {
 		if ok, err := isInParam(t.In(i)); !ok {
 			return nil, false, errors.Wrap(err, errIllegalParametersInEmit)
 		}
+		if t.In(i).Kind() == reflect.Interface || (t.In(i).Kind() == reflect.Pointer && t.In(i).Elem().Kind() == reflect.Interface) {
```
Comment (lostluck) [inline sdks/go/pkg/beam/core/funcx/output.go:87]: Checking the Kind() against reflect.Interface is a good first approximation, but this prevents *all* interfaces from appearing in types in beam. 

The problem the issue needs to address isn't "no interfaces are allowed ever" but "the vanilla empty interface{}" isn't allowed.

But care needs to be taken: Not all "empty interfaces" are created equally. Since BeamGo was developed before Go Generics, we needed some way of simulating that kind of behavior. We called these "Universal Types".

Universal types are lightly described in the design RFC here:
https://s.apache.org/beam-go-sdk-design-rfc#heading=h.1vovlxln20bf

You can detect universal types with the function `typex.IsUniversal()`: https://github.com/apache/beam/blob/master/sdks/go/pkg/beam/core/typex/class.go#L224

Look at how "IsUniversal" is defined, and how the different universal types are defined.

----
Further, we do allow arbitary interface types in these various function type signatures, but we require them to have a coder registered with Beam. That validation necessarily happens at a later stage, to avoid unnecessary coupling and complications at early parts of validation.

Since the empty interface can't have a coder defined for it (everything satisfies the empty interface), it's simpler to not allow it.
----

Then you can see that what we want to do for this bug is compare the type against the type of the empty interface.

```
var anyType = reflect.TypeOf((*any)(nil)).Elem()
```
(`any` is an alias for `interface{}`).

Let me know if you have questions about this.

File: sdks/go/pkg/beam/core/funcx/output.go (hunk 1 above)
Comment (lostluck) [inline sdks/go/pkg/beam/core/funcx/output.go:88]: If there's an error return, one should return an error instead of panicking. Panicking is generally a last resort thing, and rarely when one can return an error instead.

File: sdks/go/pkg/beam/core/funcx/sideinput.go [hunk 3]
```diff
@@ -91,6 +91,9 @@ func unfoldIter(t reflect.Type) ([]reflect.Type, bool, error) {
 		if ok, err := isOutParam(t.In(i)); !ok {
 			return nil, false, errors.Wrap(err, errIllegalParametersInIter)
 		}
+		if  t.In(i).Elem().Kind() == reflect.Interface{
+			panic("Type interface{} isn't a supported PCollection type")
```
Comment (lostluck) [inline sdks/go/pkg/beam/core/funcx/sideinput.go:95]: Same here, don't panic, check for something more specific.

File: sdks/go/pkg/beam/io/parquetio/parquetio.go [hunk 4]
```diff
@@ -149,7 +149,7 @@ type parquetWriteFn struct {
 	Filename string `json:"filename"`
 }
 
-func (a *parquetWriteFn) ProcessElement(ctx context.Context, _ int, iter func(*any) bool) error {
+func (a *parquetWriteFn) ProcessElement(ctx context.Context, _ int, iter func(*beam.X) bool) error {
```
Comment (lostluck) [inline sdks/go/pkg/beam/io/parquetio/parquetio.go:152]: This is the correct fix! No notes here.

**Review by lostluck — CHANGES_REQUESTED** [review]
This is a good start! Thank you for exploring and finding these places.

I knew that this validation would cause some tests to fail, but this is a bit much. See the other comments for understanding what's next.

You can see that the "Go Precommit" tests are failing. This is analagous to running "go test ./..." from under the beam/sdks/go/pkg/beam directory on your own machine. But it's nice to have a static list to refer to.

https://ci-beam.apache.org/job/beam_PreCommit_Go_Commit/13553/console

Essentially, most of these failures are due to the current PR being overly specific, and restricting things that we should be allowing. But there will be some that may require some other changes, similar to the parquet IO change you've already done.

File: sdks/go/pkg/beam/core/funcx/output.go (hunk 2 above)
Comment (yyy1000) [reply sdks/go/pkg/beam/core/funcx/output.go]: Thanks a lot! I'm clearer about this now.
Does it mean we should not allow empty interfaces like "interface{}", but we do allow 'Universal Types'?
But I still have a question is that, if a function has a param with "interface{}", like that
```
Fn := func(interface{}){}
t := reflect.TypeOf(Fn)
```
but typex.ClassOf(t.In(0)) returns "Concrete", I ought to think it will return "Universal".
The type system is a bit complex, I'm still learning it. :)

**Comment by yyy1000** [comment]
Thank you very much!😊
I have made changes according to your advice, but I'm not sure I do it well. Your comments are very helpful but I may still make some mistakes because I'm not so familiar with the project now.
Could you please review it again?

**Comment by lostluck** [comment]
Ah that's what happened. When it was undrafted it feel off my review slate.

Looking at this today.

**Comment by lostluck** [comment]
R:@lostluck

File: sdks/go/pkg/beam/core/funcx/output.go (hunk 2 above)
Comment (lostluck) [reply sdks/go/pkg/beam/core/funcx/output.go]: Yes. Exactly. Deny "interface{}" but allow `beam.T` et al.

The "universal" types should only be referring to `beam.T` etc. Not arbitrary interfaces. Basically, it's important to distinguish between them (`beam.T` is not `beam.U`) so that for example, if a function is dropping a key or a value in a DoFn, we know which one is being used downstream./

Users can use beam.T and similar to escape the type system, but then they deserve any runtime type errors they get at pipeline execution time. The strictness of knowing what types are used where is to help users avoid expensive execution time issues.

File: sdks/go/pkg/beam/core/funcx/output.go [hunk 5]
```diff
@@ -84,8 +84,9 @@ func unfoldEmit(t reflect.Type) ([]reflect.Type, bool, error) {
 		if ok, err := isInParam(t.In(i)); !ok {
 			return nil, false, errors.Wrap(err, errIllegalParametersInEmit)
 		}
-		if t.In(i).Kind() == reflect.Interface || (t.In(i).Kind() == reflect.Pointer && t.In(i).Elem().Kind() == reflect.Interface) {
-			panic("Type interface{} isn't a supported PCollection type")
+		emptyInterface := reflect.TypeOf((*any)(nil)).Elem()
```
Comment (lostluck) [inline sdks/go/pkg/beam/core/funcx/output.go:87]: feel free to declare this outside the function so it's only done once, rather than every time the method is called.

Comment (yyy1000) [reply sdks/go/pkg/beam/core/funcx/output.go]: Oh, got it! Thanks! I changed it.

**Comment by riteshghorse** [comment]
@yyy1000 I think the check is failing because new line is missing at the end of `pkg/beam/runners/prism/internal/config/config.go` 
`pkg/beam/runners/prism/internal/urns/urns_test.go`

Not a part of your PR though. You may want to sync you branch with master and re-running `go fmt ./...`

**Comment by lostluck** [comment]
Whoops. That's my bad.

The GitHub unit test action has been broken so these slipped in. I'll be
handling them today.

**Review by lostluck — CHANGES_REQUESTED** [review]
Last change I'd request here is adding simple single cases to the unit tests in
https://github.com/apache/beam/blob/5a41a1611c7df386a8cbbf5497dab492da599d95/sdks/go/pkg/beam/core/funcx/output_test.go#L39
and
https://github.com/apache/beam/blob/5a41a1611c7df386a8cbbf5497dab492da599d95/sdks/go/pkg/beam/core/funcx/sideinput_test.go#L41

which would end up validating that `func(any)` and `func(*any) bool` are not valid as emitters or iterators.

Note: Not a whole new test, just an additional test case for each.

That will improve the change coverage as well.

It's best practice to ensure that "new behavior" has tests added to validate that behavior.

**Comment by yyy1000** [comment]
Got it!
I will add these tests today.

**Comment by yyy1000** [comment]
I have added an additional test case for each and comments.
May these comments be fitting.

File: sdks/go/pkg/beam/core/funcx/sideinput_test.go [hunk 6]
```diff
@@ -39,6 +39,7 @@ func TestIsIter(t *testing.T) {
 		{func(*typex.EventTime, *int, *string) bool { return false }, false},            // EventTimes disallowed
 		{func(*int, *typex.Y, *typex.Z) bool { return false }, false},                   // too many values
 		{func(*typex.EventTime, *int, *typex.Y, *typex.Z) bool { return false }, false}, // too many values, EventTimes disallowed
+		{func(any) bool { return false }, false},                                        // any is not allowed as a param
```
Comment (lostluck) [inline sdks/go/pkg/beam/core/funcx/sideinput_test.go:42]: Nit, this needs to be *any since these iterator functions always take the pointer to the value, not the value itself.

Comment (yyy1000) [reply sdks/go/pkg/beam/core/funcx/sideinput_test.go]: 😫So sorry for that.
I have fixed it.
Another question is: can 'emit function' take both pointer and non-pointer as params? If it can, I will add test cases for *any and any in output_test.go.

Comment (lostluck) [reply sdks/go/pkg/beam/core/funcx/sideinput_test.go]: Great question and point!

Yes emitter functions can take pointer elements. And similarly, since the iterator function parameter is the pointer to an element type, you can pass in a pointer to a pointer. 

Those would be `func(*any)` and `func(**any) bool`

Pointers to pointers are generally rare in Go, but it's consistent with the intended handling. If Go develops a standard approach to iterators, we'd also support that more directly, and hopefully avoid the ** question.

Comment (yyy1000) [reply sdks/go/pkg/beam/core/funcx/sideinput_test.go]: Thanks!
I made add one line of code for *any in the emitter.
I think we can make future changes if Go could develop a standard approach to iterators.

**Comment by yyy1000** [comment]
So far it's close to finished.😩
It seems that I made a lot of mistakes during the process, and I will do better next time.
Thank you for your patient guidance. :)

**Comment by lostluck** [comment]
Run Go Portable PreCommit

**Comment by lostluck** [comment]
Run GoPortable PreCommit
