### PR TITLE
Fix inconsistent data type in GenericRecord and AvroSchema for AvroWriter

### LINKED ISSUE #36735: [Bug]: BigQueryIO write inconsistent implicit int->long conversion for nullable long and for different write methods
### What happened?

 - write int to target schema int64, succeed

- write int to target schema nullable(int64), using storage_write_api, succeed

- write int to target schema nullable(int64), using file_load avro, failing with

```
Caused by: org.apache.avro.UnresolvedUnionException: Not in union ["null","long"]: 123 (field=nullableLong)
```

A simple reproduce (not using Beam):

```
public class AvroTest {
  private static final String SCHEMA_JSON = "{\n" +
      "  \"type\": \"record\",\n" +
      "  \"name\": \"UserEvent\",\n" +
      "  \"namespace\": \"com.example.avro\",\n" +
      "  \"fields\": [\n" +
      "    {\"name\": \"userId\", \"type\": \"string\"},\n" +
      "    {\"name\": \"nonNullLong\", \"type\": \"long\"},\n" +
      "    {\"name\": \"nullableLong\", \"type\": [\"null\", \"long\"], \"default\": null}\n" +
      "  ]\n" +
      "}";

  public static void main(String[] argv) throws AvroRuntimeException, IOException {
    Schema schema = new Schema.Parser().parse(SCHEMA_JSON);
    GenericRecord eventWithTimestamp = new GenericData.Record(schema);
    eventWithTimestamp.put("userId", "user-123");
    eventWithTimestamp.put("nonNullLong", 123);
    eventWithTimestamp.put("nullableLong", 123); // fail

    File avroOutputFile = new File("user-events.avro");
    DatumWriter<GenericRecord> datumWriter = new GenericDatumWriter<>(schema);
    try (DataFileWriter<GenericRecord> dataFileWriter = new DataFileWriter<>(datumWriter)) {
      dataFileWriter.create(schema, avroOutputFile);
      dataFileWriter.append(eventWithTimestamp);
    }
  }
}
```

this is a known avro issue: https://stackoverflow.com/questions/35963285/org-apache-avro-unresolvedunionexception-not-in-union-long-null

However this led a breaking change for Beam Yaml 2.69.0 where it switched the batch BigQueryIO write to storage_write_api to Managed IO (backed by file_load).

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fix #36735

**Please** add a meaningful description for your change here

* Fix inconsistent data type in GenericRecord and AvroSchema for AvroWriter

* Fixed PortableBigQueryDestinations not honoring avroschema attached to AvroWriteRequest, causing Avro Schema is inferred from Beam schema for every element.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java [hunk 1]
```diff
@@ -1230,6 +1240,18 @@ private static org.apache.avro.Schema getFieldSchema(
       return value;
     }
 
+    // Handle implicit up-cast: use avroSchema
+    if (INT_AVRO_TYPE.equals(typeWithNullability.type)) {
```
Comment (Abacn) [inline sdks/java/extensions/avro/src/main/java/org/apache/beam/sdk/extensions/avro/schemas/utils/AvroUtils.java]: This mirrors https://github.com/apache/avro/pull/737

**Comment by Abacn** [comment]
R: @tarun-google  @ahmedabu98

**Comment by tarun-google** [comment]
LGTM, Thanks for fixing !!

see if we can incorporate both Gemini suggestions for clean code.

**Comment by Abacn** [comment]
testCdcUsingHexSequenceNum (org.apache.beam.sdk.io.gcp.bigquery.StorageApiSinkRowUpdateIT) failed not related to the change. Test passed on previous commit. merging for now.
