### PR TITLE
#20812 handle @RequiresStableInput in portable flink

### LINKED ISSUE #20812: Cross-language consistency (RequiresStableInputs) is quietly broken (at least on portable flink runner)
Since the Python SDK does not seem to provide anything similar to [https://beam.apache.org/releases/javadoc/2.27.0/org/apache/beam/sdk/transforms/DoFn.RequiresStableInput.html,](https://beam.apache.org/releases/javadoc/2.27.0/org/apache/beam/sdk/transforms/DoFn.RequiresStableInput.html,) I wrote a small cross-language transform in Java, to be called from a Python SDK pipeline executed using the Flink runner. The expectation was that it would perform the necessary buffering to correctly implement exactly-once semantics in my use case.

However, this did not result in the creation of any Flink checkpoints. The reason seems to be that the code in [https://github.com/apache/beam/blob/73731ec4f3f2d185e89aa3e378d321c2154ecf53/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L492](https://github.com/apache/beam/blob/73731ec4f3f2d185e89aa3e378d321c2154ecf53/runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java#L492) is never executed, because the UDF is called using the FnApiDoFnRunner instead.

This behavior appears particularly problematic, because the RequiresStableInputs annotation is *silently* ignored, so users might falsely believe that they get exactly-once semantics (EOS), whereas they only get some kind of "at-least-once if the upstream pipeline happens to be deterministic" (which is not the case in general).

Thus, if a user where to use, e.g., the Kafka EOS sink ([https://beam.apache.org/releases/javadoc/2.27.0/org/apache/beam/sdk/io/kafka/KafkaIO.WriteRecords.html#withEOS-int-java.lang.String-](https://beam.apache.org/releases/javadoc/2.27.0/org/apache/beam/sdk/io/kafka/KafkaIO.WriteRecords.html#withEOS-int-java.lang.String-)) which relies on the RequiresStableInputs mechanism, in their cross-language Java UDF, that might not provide correct (i.e., potentially not even at-least-once) output in general if the upstream pipeline is not deterministic and needs to be replayed from a checkpoint.

I feel this issue should be prioritized, because it essentially makes it impossible to achieve source-to-sink exactly once guarantees when using Beam on Flink with the Python SDK.

From a user perspective, either (or a combination) of the following would resolve the issue:
 * Implement something like RequiresStableInputs for the Python SDK's DoFn (and ensure that using RequiresStableInputs in a Java-based DoFn results in an error if the latter is called from a pipeline defined with the Python SDK).
 * Extend the FnApiDoFnRunner to provide stable inputs to DoFn which require it.

Unfortunately, I do not feel familiar enough with the code base to address the issue myself — at least not without further guidance, so any feedback is welcome.

Imported from Jira [BEAM-11755](https://issues.apache.org/jira/browse/BEAM-11755). Original Jira may contain additional context.
Reported by: pikulmar.

### LINKED ISSUE #21333: Flink testParDoRequiresStableInput flaky
https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/20253/

org.apache.beam.runners.flink.FlinkRequiresStableInputTest.testParDoRequiresStableInput

java.util.concurrent.ExecutionException: java.util.concurrent.CompletionException: org.apache.flink.runtime.checkpoint.CheckpointException: Checkpoint triggering task Source: Impulse -\> CreatePCollectionOfOneValue/Read(CreateSource)/ParDo(OutputSingleSource)/ParMultiDo(OutputSingleSource) -\> CreatePCollectionOfOneValue/Read(CreateSource)/ParDo(BoundedSourceAsSDFWrapper)/ParMultiDo(BoundedSourceAsSDFWrapper)/Pair with initial restriction/ParMultiDo(PairWithRestriction) -\> CreatePCollectionOfOneValue/Read(CreateSource)/ParDo(BoundedSourceAsSDFWrapper)/ParMultiDo(BoundedSourceAsSDFWrapper)/Split restriction/ParMultiDo(SplitRestriction) -\> CreatePCollectionOfOneValue/Read(CreateSource)/ParDo(BoundedSourceAsSDFWrapper)/ParMultiDo(BoundedSourceAsSDFWrapper)/Explode windows/ParMultiDo(ExplodeWindows) -\> CreatePCollectionOfOneValue/Read(CreateSource)/ParDo(BoundedSourceAsSDFWrapper)/ParMultiDo(BoundedSourceAsSDFWrapper)/Assign unique key/AddKeys/Map/ParMultiDo(Anonymous) -\> ToKeyedWorkItem (1/1) of job 7bbb425ba325dbc1dc4d3cdf1c8b88f9 is not being executed at the moment. Aborting checkpoint. Failure reason: Not all required tasks are currently running.

Imported from Jira [BEAM-13575](https://issues.apache.org/jira/browse/BEAM-13575). Original Jira may contain additional context.
Reported by: ibzib.

### PR DESCRIPTION
**Pull request by je-ik**
Fixes #20812
Fixes #21333
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by je-ik** [comment]
assign set of reviewers

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
Run Flink ValidatesRunner

**Comment by je-ik** [comment]
Run Java Flink PortableValidatesRunner Streaming

**Comment by je-ik** [comment]
R: @lukecwik

**Comment by je-ik** [comment]
@aaltay @robertwb @kennknowles Looks I'm unable to find a reviewer for this one. It fixes correctness bug in Flink, cau you please help find one? Thanks. :+1:

**Comment by aaltay** [comment]
@kileys - Would you be able to review this? It is a medium sized change and does not require too much flink runner context.

**Comment by kennknowles** [comment]
Also @johnjcasey is interested in this feature working more broadly

File: runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java [hunk 1]
```diff
@@ -326,6 +324,17 @@ public DoFnOperator(
     this.finishBundleBeforeCheckpointing = flinkOptions.getFinishBundleBeforeCheckpointing();
   }
 
+  private boolean isRequiresStableInput(DoFn<InputT, OutputT> doFn) {
+    // WindowDoFnOperator does not use a DoFn
+    return doFn != null
```
Comment (lukecwik) [inline runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java:329]: This annotation can be added to other parts of the DoFn like onTimer as per: https://github.com/apache/beam/blob/8dd87491dcb2660f859f87b3336adb984c62c12d/sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/DoFn.java#L803

Is `@ProcessElement` the only place we are trying to add support for it?

If you copied this code from https://github.com/apache/beam/blob/434427e90b55027c5944fa73de68bff4f9a4e8fe/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/ParDoTranslation.java#L360, then that code is wrong based upon the specification.

File: runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java [hunk 2]
```diff
@@ -760,15 +769,18 @@ public long applyInputWatermarkHold(long inputWatermark) {
   }
 
   /**
-   * Allows to apply a hold to the output watermark before it is send out. By default, just passes
-   * the potential output watermark through which will make it the new output watermark.
+   * Allows to apply a hold to the output watermark before it is send out. Used to apply hold on
```
Comment (lukecwik) [inline runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/DoFnOperator.java:772]:
```suggestion
   * Allows to apply a hold to the output watermark before it is sent out. Used to apply hold on
```

File: runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java [hunk 3]
```diff
@@ -85,6 +86,8 @@ public static <InputT, OutputT> BufferingDoFnRunner<InputT, OutputT> create(
   int currentStateIndex;
   /** The current handler used for buffering. */
   private BufferingElementsHandler currentBufferingElementsHandler;
+  /** Minimum timestamp of all buffered elements. */
+  private volatile long currentOutputWatermarkHold;
```
Comment (lukecwik) [inline runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java:90]: Should we make this optional so that we can differentiate in the case where the are no elements to prevent the watermark from advancing to Long.MAX_VALUE?

File: runners/flink/src/test/java/org/apache/beam/runners/flink/PortableExecutionTest.java [hunk 4]
```diff
@@ -38,10 +38,15 @@
 import org.apache.beam.sdk.transforms.DoFn;
 import org.apache.beam.sdk.transforms.GroupByKey;
 import org.apache.beam.sdk.transforms.Impulse;
+import org.apache.beam.sdk.transforms.MapElements;
```
Comment (lukecwik) [inline runners/flink/src/test/java/org/apache/beam/runners/flink/PortableExecutionTest.java:41]: Can we instead run the RequiresStableInputIT instead?

https://github.com/apache/beam/blob/434427e90b55027c5944fa73de68bff4f9a4e8fe/sdks/java/core/src/test/java/org/apache/beam/sdk/RequiresStableInputIT.java

**Review by lukecwik — CHANGES_REQUESTED** [review]

**Comment by je-ik** [comment]
@lukecwik thanks for the review! :+1:
I'll look into it in a few days.

**Review by je-ik — COMMENTED** [review]
@lukecwik thanks for the review! Can we move fixing the @OnTimer and @RequiresStableInput issue to different issue? I'll add the IT test and ping you again.

**Comment by je-ik** [comment]
@lukecwik I was looking into using the `RequiresStableInputIT`, unfortunately, it looks not easily reusable. It is somewhat used internally in some tests inside FlinkRunner (namely `FlinkRequiresStableInputTest`), but it is reused only partially. I could copy&paste the code and try to run it using Flink portable runner, but a better approach seems to be to turn it into `@ValidatesRunner` test, that could be turned on/off automatically. That looks like something orthogonal to this PR and thus I'd prefer to do it in different issue, so that we don't block this one. WDYT?

File: runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java [hunk 5]
```diff
@@ -164,6 +171,8 @@ public <KeyT> void onTimer(
       Instant timestamp,
       Instant outputTimestamp,
       TimeDomain timeDomain) {
+
+    currentOutputWatermarkHold = Math.min(timestamp.getMillis(), currentOutputWatermarkHold);
```
Comment (lukecwik) [inline runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java:175]: Shouldn't this be `outputTimestamp` since `outputTimestamp` is the minimum timestamp that is used for producing output for a timer?

```suggestion
    currentOutputWatermarkHold = Math.min(outputTimestamp.getMillis(), currentOutputWatermarkHold);
```

File: runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java (hunk 3 above)
Comment (lukecwik) [reply runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java:90]: Your right, my confusion was about the purpose here. It would make more sense to call this `minOutputWatermarkHoldSeen`

**Comment by lukecwik** [comment]
> @lukecwik I was looking into using the `RequiresStableInputIT`, unfortunately, it looks not easily reusable. It is somewhat used internally in some tests inside FlinkRunner (namely `FlinkRequiresStableInputTest`), but it is reused only partially. I could copy&paste the code and try to run it using Flink portable runner, but a better approach seems to be to turn it into `@ValidatesRunner` test, that could be turned on/off automatically. That looks like something orthogonal to this PR and thus I'd prefer to do it in different issue, so that we don't block this one. WDYT?

I wouldn't say it is orthogonal. It is hard to have confidence that something works and isn't regressed without there being good test coverage. Your call if you still want to forge ahead without the tests.

**Comment by je-ik** [comment]
> I wouldn't say it is orthogonal. It is hard to have confidence that something works and isn't regressed without there being good test coverage. Your call if you still want to forge ahead without the tests.

100% agree with the test part. The current code has good coverage, but it builds upon the current implementation detail and it might break. Got your point, I will have a look if I can meaningfully extend the integration test and run in against both classic and portable runners. I'd definitely want to keep the original tests as well, because these tests should be more conclusive (under current implementation).

**Comment by je-ik** [comment]
I managed to get the same test to run for both classic and portable runner. But ... there is an issue with Pipeline fusion, it seems it must respect the boundary given by @RequiresStableInput. Started discussion about that [on the mailing list](https://lists.apache.org/thread/2s3jx62wh0rz09dcmz816sl5y3dnq432)

File: runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java (hunk 3 above)
Comment (je-ik) [reply runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java]: changed the name to `minBufferedElementTimestamp`

File: runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java (hunk 5 above)
Comment (je-ik) [reply runners/flink/src/main/java/org/apache/beam/runners/flink/translation/wrappers/streaming/stableinput/BufferingDoFnRunner.java]: Yes, I fixed the independently. Unfortunately, there is some other buf with timers in stable do fn. 
See https://github.com/apache/beam/issues/24662

File: runners/flink/src/test/java/org/apache/beam/runners/flink/PortableExecutionTest.java (hunk 4 above)
Comment (je-ik) [reply runners/flink/src/test/java/org/apache/beam/runners/flink/PortableExecutionTest.java]: Fixed and used the IT test for both classic and portable runners.

**Review by je-ik — COMMENTED** [review]
This is neverending story. I fixed several bugs, used the IT test, currently tests are locally passing on flink 1.15. On flink 1.14 (which is used in CI) the portable test hangs, I need to figure out why. But other than that, this should be ready for another review, there are two issues created from this:
 - https://github.com/apache/beam/issues/24662
 - https://github.com/apache/beam/issues/24655
 
 This also fixes https://github.com/apache/beam/issues/21333.

**Comment by je-ik** [comment]
@lukecwik is there any way to get logs of the failed pre commit?
https://ci-beam.apache.org/job/beam_PreCommit_Java_Commit/25421/

The tests pass locally, so without the log I'm not sure how to fix the problem. :-/

**Comment by je-ik** [comment]
@lukecwik I finally managed to make the tests pass, so this is ready for final review. I will squash the commits after.

**Comment by je-ik** [comment]
@lukecwik would you have time for review, or could you recommend someone please?

**Review by lukecwik — APPROVED** [review]
LGTM

**Comment by lukecwik** [comment]
I'm glad that you were able to work through the problems and get the tests fixed and passing.
