### PR TITLE
Skip runner Dataflow v1 steps when a job will run on v2

### LINKED ISSUE #30469: [Bug]: KafkaIO cannot enable Dynamic Reads on Dataflow Runner V2
## Issue

When running a pipeline with KafkaIO and withDynamicReads enabled I get the following error in Dataflow on Runner V2

```
Exception in thread "main" java.lang.IllegalStateException: 
The current runner does not support SDF-based Kafka read properly and the replacement runner lacks the support for the following properties: [DYNAMIC_READ, WATCH_TOPIC_PARTITION_DURATION]. 
For example if you are using Dataflow then consider using Dataflow Runner v2.; see consecutive INFO logs for details.
```

This is despite setting the `use_runner_v2` and `beam_fn_api` experiment flags.

Steps to reproduce:

1) Create a pipeline with KafkaIO and dynamic reads, heres my configuration

```
    KafkaIO
      .read[Array[Byte], Array[Byte]]
      .withBootstrapServers(kafkaBootstrapServers)
      .withDynamicRead(Duration.standardMinutes(15))
      .withTopics(kafkaTopics.asJava)
      .withReadCommitted()
      .withConsumerConfigUpdates(kafkaConsumerProperties.toMap[String, AnyRef].asJava)
      .commitOffsetsInFinalize
      .withKeyDeserializer(classOf[ByteArrayDeserializer])
      .withValueDeserializer(classOf[ByteArrayDeserializer])
```

2) Enable experiment flags for runner v2 and beam function api: `use_runner_v2`, `beam_fn_api`

3) Run the pipeline in Dataflow

## Investigation

I believe this error is happening because beam always [replaces V1 transforms](https://github.com/apache/beam/blob/935ca9c58d61e5d070056d36c21c6b6c03a97908/runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowRunner.java#L1227C1-L1229C35) and the transform replacement for V1 is a non-SDF based reader that doesn't support dynamic reads.

so when the replacement is attempted [Beam correctly validates](https://github.com/apache/beam/blob/master/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaIO.java#L1539-L1543) that the replacement is not compatible with Dynamic Reads and throws a compatibility exception.

I would like to propose that we only make this replacement for runner v1 like so https://github.com/damnMeddlingKid/beam/pull/1/files

```
        if (!hasExperiment(options, "use_runner_v2")) {
          overridesBuilder.add(KafkaIO.Read.KAFKA_READ_OVERRIDE);
        }
```

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by kennknowles**
Fixes #30469

Currently there is inconsistent rewriting and validation.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Review by damccorm — APPROVED** [review]
LGTM if it goes green

File: runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java [hunk 1]
```diff
@@ -428,7 +428,11 @@ public Job translate(List<DataflowPackage> packages) {
         environment.setDebugOptions(debugOptions);
       }
 
-      pipeline.traverseTopologically(this);
+      if (useUnifiedWorker(options)) {
```
Comment (damccorm) [inline runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java:431]:
```suggestion
      if (DataflowRunner.useUnifiedWorker(options)) {
```

Comment (liferoad) [reply runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java]: Can we add a flag (I know we have too many) to force the  v1 translation? It could help reserve the old behavior if needed.

**Comment by kennknowles** [comment]
R: @damccorm

File: runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java (hunk 1 above)
Comment (kennknowles) [reply runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java]: If runner v2 is specified it is dead code

Comment (kennknowles) [reply runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java]: (the equivalent code to this is in the Dataflow backend for v2 - this particular codepath does literally nothing for v2)

Comment (liferoad) [reply runners/google-cloud-dataflow-java/src/main/java/org/apache/beam/runners/dataflow/DataflowPipelineTranslator.java]: OK.

**Comment by damccorm** [comment]
Can we keep the files to run the postcommits?

**Comment by kennknowles** [comment]
Sure. I dropped them because the only risk of this change is catastrophically making all Dataflow v1 jobs fail, and we already have them on precommit. I can add them back.

**Comment by kennknowles** [comment]
Looks like there are some replacements and also things that happen in traversal that are explicitly expected by tests. TBD what the deal is. I expect we have an anti-pattern of doing some replacements and then producing a "portable" pipeline that is specialized to Dataflow on the client side.

**Comment by kennknowles** [comment]
Nope, it looks like there are just tests that set `use_runner_v2` but then check that things happen during the v1 translation. Specifically the runner v1 translation was used to do client-side validation of what features were supported on v2. That definitely needs to be service-side so that service can evolve support without an SDK release. So actually this PR is a major upgrade in that sense, but we need to check that the service-side translation has adequate validation. Might commit a smaller version like your PR first, considering all this.

**Comment by kennknowles** [comment]
R: @scwhittle for the removed tests. They were testing things that honestly wouldn't work right, but curious where are your thoughts on this, as it pertains to the status of the service's level of care in v2 codepaths:

- level of validation for SetState and MapState support which should happen in the backend
- don't really understand what is the deal with the GroupIntoBatches stuff
- whether there is something in the service that somehow was trying to depend on the pubsub sink v1 translation even in v2?

To be clear, all these tests are testing whether the v1 translation has some behavior when the actual pipeline is running on v2.

**Comment by kennknowles** [comment]
R: @reuvenlax

**Comment by kennknowles** [comment]
Laughing to myself that the response to failing tests here was to delete the tests, but I _think_ it is the right thing to do.

**Comment by kennknowles** [comment]
Test failures were GCE quota.

**Comment by kennknowles** [comment]
Internal tests green as well.
