### PR TITLE
21730 fix offset resetting

### LINKED ISSUE #21730: [Bug]: KafkaIO SplittableDoFn not resuming from last committed offset
### What happened?

Using `KafkaIO` with [ReadFromKafkaDoFn.java](https://github.com/apache/beam/blob/v2.39.0/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java) and `commitOffsetsFinalize` should commit offsets of processed messages and if the pipeline is restarted, should resume from the last committed offset.

While committing the offset works correctly, resuming from the latest committed offset does not work because the groupId used are not the same (using 2.39.0).

- Committing the offsets happens in [KafkaCommitOffset.java](https://github.com/apache/beam/blob/v2.39.0/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/KafkaCommitOffset.java) with a consumer defined as:
 `consumerFactoryFn.apply(updatedConsumerConfig)`

- Reading the startOffset is done in `initialRestriction()` in [ReadFromKafkaDoFn.java](https://github.com/apache/beam/blob/v2.39.0/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java) with a consumer defined as:
`consumerFactoryFn.apply(
            KafkaIOUtils.getOffsetConsumerConfig(
                "initialOffset", offsetConsumerConfig, updatedConsumerConfig)))`

Since the group name of the consumer is not the same as the group name of the consumer fetching the latest offset, the pipeline will always start from the beginning of the (topic,partition) again.

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-kafka

### PR DESCRIPTION
**Pull request by johnjcasey**
Remove code that generated a random group name
Added an integration test that verifies we don't re-process elements

Resolves #21730
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by johnjcasey** [comment]
@chamikaramj I figured out a way to test streaming. Its not super elegant, but it works for now

**Comment by johnjcasey** [comment]
run java precommit

**Comment by johnjcasey** [comment]
r: @chamikaramj

File: sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java [hunk 1]
```diff
@@ -239,6 +252,94 @@ public void testKafkaIOReadsAndWritesCorrectlyInBatch() throws IOException {
...
+    public CrashOnExtra(Collection<String> records) {
+      expected = new HashSet<>(records);
+    }
+
+    @ProcessElement
+    public void processElement(@Element String element, OutputReceiver<String> outputReceiver) {
+      if (!expected.contains(element)) {
+        throw new RuntimeException("Received unexpected element: " + element);
+      } else {
+        expected.remove(element);
```
Comment (chamikaramj) [inline sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java:329]: Also confirm that expected contains the element ?
Otherwise this would pass trivially for a run that does not read any data.

Comment (chamikaramj) [reply sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java:329]: Actually we might need to write output to a sink (for e.g. a file) and read that back after the pipeline to verify that this was a not a trivial execution.

Comment (johnjcasey) [reply sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java:329]: I do that via the log and expected logs. Its essentially a workaround sink

Comment (chamikaramj) [reply sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java:329]: Ah ok. Makes sense.

**Review by chamikaramj — COMMENTED** [review]
LGTM. Thanks.
