### PR TITLE
fix for adding unexpected Empty Records in Nested Arrays in BigQueryIO

### LINKED ISSUE #33842: [Bug]: Unexpected Empty Records in Nested Arrays When Using BigQueryIO.write() with .withAutoSchemaUpdate(true) and .ignoreUnknownValues()
### What happened?

When enabling .withAutoSchemaUpdate(true) and .ignoreUnknownValues() with BigQueryIO.write() method, unexpected behavior happens causing records with nested arrays to fail being written to BQ. An empty record is added into the array, causing schema validation issues. This behavior does not occur without these two settings enabled.

**Expected behavior:**
Records should be mapped without additional empty objects being added to array

**Actual Behavior:**
Records in arrays are unexpectedly populated with an empty record, resulting in schema validation failures during write operations.

**Steps to reproduce:**
1. Use BigQueryIO.write() with: .withAutoSchemaUpdate(true) and .ignoreUnknownValues() (Beam version is 2.59.0)
2. Write records containing array data with the schema mentioned above
3. Observe failures due to an empty record being inserted into arrays. 

**Example big querry nested record field:**
```
{
  "name": "external_ids",
  "mode": "REQUIRED",
  "type": "RECORD",
  "fields": [
    {
      "name": "id",
      "mode": "REQUIRED",
      "type": "STRING"
    },
    {
      "name": "name",
      "mode": "REQUIRED",
      "type": "STRING"
    }
  ]
}
```
This is what response would look like:

```
(...)
"errorMessage": "Field value of id cannot be empty. on field external_ids.",
(...)
  "stringifiedData": {
    "external_ids": [
      {
        "id": "fd7da837-13cb-4b67-8ced-220a27130e34",
        "name": "some_custom_id"
      },
      {}
    ],
  }
(...)
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by stankiewicz**
fixes #33842

### CODE REVIEW

**Comment by stankiewicz** [comment]
@ahmedabu98 can you take a look at this? thanks!

**Comment by stankiewicz** [comment]
do not merge yet, I think I found another bug.

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java [hunk 1]
```diff
@@ -1671,6 +1672,44 @@ public void testIgnoreUnknownRepeatedNestedField() throws Exception {
     assertEquals("foobar_doubly_nested", unknownDoublyNestedStruct.get("unknown_doubly_nested"));
   }
 
+  @Test
+  public void testIgnoreUnknownRepeatedNestedField2() throws Exception {
```
Comment (ahmedabu98) [inline sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java:1676]: nit: more descriptive test name 
```suggestion
  public void testIgnoreUnknownRepeatedNestedFieldWithNoUnknowns() throws Exception {
```

**Review by ahmedabu98 — APPROVED** [review]
This LGTM! Thanks for taking this @stankiewicz 

Lmk when it's ready to merge

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java [hunk 2]
```diff
@@ -1671,6 +1672,44 @@ public void testIgnoreUnknownRepeatedNestedField() throws Exception {
...
+        TableRowToStorageApiProto.getDescriptorFromTableSchema(schema, true, false);
+    TableRowToStorageApiProto.SchemaInformation schemaInformation =
+        TableRowToStorageApiProto.SchemaInformation.fromTableSchema(schema);
+    TableRow unknown = new TableRow();
+    DynamicMessage msg =
+        TableRowToStorageApiProto.messageFromTableRow(
+            schemaInformation, descriptor, tableRow, true, false, unknown, null, -1);
+    assertEquals(2, msg.getAllFields().size());
+
+    System.out.println(unknown);
```
Comment (ahmedabu98) [inline sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProtoTest.java:1709]: p.s. cleanup

**Comment by stankiewicz** [comment]
issue I see additional problem here: [StorageApiWriteUnshardedRecords](https://github.com/apache/beam/blob/master/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWriteUnshardedRecords.java#L587)

If we have a row with known fields (name:string, surname:string) and one unknown (foo:string) , this line will concat and not cause schema issues.

but if unknown field is part of repeated structure, 
e.g. (name:string, phone:(repeated struct type:string, num:string) ) and we have unknown in repeated struct (phone: [ null, {favourite:yes} ]) concat doesn't make any sense - should be mix of merge & concat at each level.  

For current bug, it is resolved - it won't add empty records so we can merge it.

Added issue for concatenating unknown nested fields which may require bigger changes #34145

**Review by ahmedabu98 — COMMENTED** [review]
Thanks @radhika-kulkarni, left some comments

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java [hunk 3]
```diff
@@ -539,16 +539,14 @@ public static DynamicMessage messageFromMap(
...
             && unknownFields != null) {
-          if (unknownFields.get(key) instanceof Map
-              && ((Map<?, ?>) unknownFields.get(key)).isEmpty()) {
+          if ((unknownFields.get(key) instanceof Map
+                  && ((Map<?, ?>) unknownFields.get(key)).isEmpty()) // single struct, empty
+              || (unknownFields.get(key)
+                      instanceof List // repeated struct, empty list or list with empty structs
+                  && (((List<?>) unknownFields.get(key)).isEmpty()
+                      || ((List<?>) unknownFields.get(key))
+                          .stream().allMatch(row -> row == null || ((Map<?, ?>) row).isEmpty())))) {
```
Comment (ahmedabu98) [inline sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java:548]: I guess we can also merge with the outer if-statement? this is gonna be a monster of an if-statement.

Maybe there's a way to clean it up, but it's not PR-blocking so will leave it up to you.

**Review by ahmedabu98 — APPROVED** [review]
LGTM! can merge when tests are green

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java (hunk 3 above)
Comment (stankiewicz) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/TableRowToStorageApiProto.java]: Done and green
