### PR TITLE
Fix multiple mutations affecting the same entity in Datastore write

### LINKED ISSUE #18521: DatastoreIO.Write fails multiple mutations of same entity
When streaming messages from a source that doesn't guarantee once-only-delivery, but has at-least-once-delivery, then the DatastoreIO.Write will throw an exception which leads to Dataflow retrying the same commit multiple times before giving up. This leads to a significant bottleneck in the pipeline, with the end-result that the data is dropped. This should be handled better.

There are a number of ways to fix this. One of them could be to drop any duplicate mutations within one batch. Non-duplicates should also be handled in some way. Perhaps a use NON-TRANSACTIONAL commit, or make sure the mutations are commited in different commits.

```

com.google.datastore.v1.client.DatastoreException: A non-transactional commit may not contain multiple
mutations affecting the same entity., code=INVALID_ARGUMENT
        com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:126)

       com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:169)
        com.google.datastore.v1.client.RemoteRpc.call(RemoteRpc.java:89)

       com.google.datastore.v1.client.Datastore.commit(Datastore.java:84)
        org.apache.beam.sdk.io.gcp.datastore.DatastoreV1$DatastoreWriterFn.flushBatch(DatastoreV1.java:1288)

       org.apache.beam.sdk.io.gcp.datastore.DatastoreV1$DatastoreWriterFn.processElement(DatastoreV1.java:1253)


```

Imported from Jira [BEAM-3039](https://issues.apache.org/jira/browse/BEAM-3039). Original Jira may contain additional context.
Reported by: routsi.

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #18521

* Use entity key instead of mutation hash value to decide flush

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @chamikaramj who commented the original Jira ticket
CC: @zhoufek

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java [hunk 1]
```diff
@@ -1579,7 +1579,7 @@ public void finishBundle() throws Exception {
      * @throws DatastoreException if the commit fails or IOException or InterruptedException if
      *     backing off between retries fails.
      */
-    private void flushBatch() throws DatastoreException, IOException, InterruptedException {
+    synchronized private void flushBatch() throws DatastoreException, IOException, InterruptedException {
```
Comment (Abacn) [inline sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java:1582]: As uniqueMutationKeys start working and flushBatch() is possible to get called, I am concerned about this apparently not thread-safe method. Within in bundle do we guarantee a processElement() being executed at the same time?

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java [hunk 2]
```diff
@@ -651,6 +652,45 @@ public void testDatatoreWriterFnWithLargeEntities() throws Exception {
       }
     }
 
+    /** Tests {@link DatastoreWriterFn} correctly flushes batch upon receive same entity keys. */
+    @Test
+    public void testDatatoreWriterFnWithDuplicateEntities() throws Exception {
```
Comment (damondouglas) [inline sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java:657]: Missing the 's' in Datastore:
`testDatatoreWriterFnWithDuplicateEntities` => `testDatastoreWriterFnWithDuplicateEntities`

**Review by damondouglas — COMMENTED** [review]
@Abacn Should there be a test that replicates the conditions that lead to the Exception reported in #18521 that we can validate resolves by the changes in [DatastoreV1.java](https://github.com/Abacn/beam/blob/datastoremutationkey/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java).  What I attempted was revert the [DatastoreV1.java](https://github.com/Abacn/beam/blob/datastoremutationkey/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1.java) changes and re-run both DatastoreV1Test and RampupThrottlingFnFnTest to see if I could get the Exception reported by #18521.  RampupThrottlingFnFnTest passed.  Yet, DatastoreV1Test failed but with an expected error that was due to an unexpected transaction.  I didn't know enough about the fix to see if I could further replicate the reported #18521 by refactoring the new test function in DatastoreV1Test.

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java (hunk 2 above)
Comment (Abacn) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java:657]: Thanks @damondouglas! This unit test is exactly `replicates the conditions that lead to the Exception reported in #18521 that we can validate resolves by the changes in DatastoreV1.java.` Though it is running on mock datastore client. Prior to the change the mutation sent to datastore would have keys `{0, 1, 0, 2}` and cause the exception because there are duplicated key in a single request. Now it send two requests with keys `{0, 1}` and `{0, 2}` and would not cause exception.

The RampupThrottlingFnFnTest change is because originally the mutations are having all the same (Void), but due to that the duplication did not work properly, a single commit will be called. This is a bad test case because for real datastore (not mock), this would throw exception. Now I just use a mutation with random elements to let the test works properly.

Comment (Abacn) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java:657]: will fix typo once jenkins back

**Review by chamikaramj — APPROVED** [review]
LGTM. Thanks.

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java (hunk 2 above)
Comment (damondouglas) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/datastore/DatastoreV1Test.java:657]: Thank you for explaining this!

**Comment by Abacn** [comment]
Run Java PreCommit
