### PR TITLE
[Managed Iceberg] Support writing to partitioned tables

### LINKED ISSUE #31943: [Bug]: Writing partitioned data with Managed IcebergIO fails
### What happened?

After following Dataflow example (https://cloud.google.com/dataflow/docs/guides/write-to-iceberg), i'm trying to add a partition, but it breaks when writing.

**Given** the following table:
```kotlin
    val catalogConfig = IcebergCatalogConfig.builder()
        .setIcebergCatalogType("hadoop")
        .setName("hadoop.catalog")
        .setWarehouseLocation("file:///warehouse")
        .build()


    val icebergSchema = IcebergSchema(
        Types.NestedField.required(1, "id", Types.LongType.get()),
        Types.NestedField.required(2, "name", Types.StringType.get()),
        Types.NestedField.required(3, "day", Types.StringType.get())
    )

    val partitionSpec = PartitionSpec.builderFor(icebergSchema)
        .identity("id")
        .build()

    catalogConfig.catalog().createTable(
        TableIdentifier.of("table"),
        icebergSchema,
        partitionSpec
    )
```

**When** writing with the following code
```kotlin

    val TABLE_ROWS: List<String> = listOf(
        "{\"id\":0, \"name\":\"Alice\", \"day\":\"01\"}",
        "{\"id\":1, \"name\":\"Bob\", \"day\":\"02\"}",
        "{\"id\":2, \"name\":\"Charles\", \"day\":\"02\"}"
    )

    val SCHEMA: Schema = Schema.builder()
        .addInt64Field("id")
        .addStringField("name")
        .addStringField("day")
        .build()


    pipeline.apply(Create.of(TABLE_ROWS))
        .apply(JsonToRow.withSchema(SCHEMA))
        .apply(
           Managed.write(Managed.ICEBERG).withConfig(mapOf("table" to "table",
           "catalog_config" to mapOf(
               "catalog_name" to "hadoop.catalog",
               "warehouse_location" to "file:///warehouse",
               "catalog_type" to "hadoop"
           )
        )))
```
**Then** it breaks with the following stacktrace:
```sh
Caused by: java.lang.IllegalArgumentException: Partition must not be null when creating data writer for partitioned spec
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:143)
	at org.apache.iceberg.parquet.Parquet$DataWriteBuilder.build(Parquet.java:704)
	at org.apache.beam.sdk.io.iceberg.RecordWriter.<init>(RecordWriter.java:73)
	at org.apache.beam.sdk.io.iceberg.RecordWriter.<init>(RecordWriter.java:47)
	at org.apache.beam.sdk.io.iceberg.WriteUngroupedRowsToFiles$WriteUngroupedRowsToFilesDoFn.createAndInsertWriter(WriteUngroupedRowsToFiles.java:219)
	at org.apache.beam.sdk.io.iceberg.WriteUngroupedRowsToFiles$WriteUngroupedRowsToFilesDoFn.getWriterIfPossible(WriteUngroupedRowsToFiles.java:242)
	at org.apache.beam.sdk.io.iceberg.WriteUngroupedRowsToFiles$WriteUngroupedRowsToFilesDoFn.processElement(WriteUngroupedRowsToFiles.java:258)
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [x] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixes #31943

Adds support for writing to partitioned Iceberg tables. 

A record writer manager is introduced to open and close writers as necessary. An Iceberg data writer instance is configured to write to only one partition, so multiple writers are needed to write to multiple partitions. 

The behavior remains unchanged when writing to unpartitioned tables.

Also some small but key changes:
- Use Iceberg APIs to determine the datafile location (as opposed to hardcoding the location to be at `<warehouse>/<table>/<data-file>`
- Write manifest files under `<table>/metadata/`

### CODE REVIEW

**Comment by ahmedabu98** [comment]
R: @chamikaramj 
CC: @arthurpessoa

**Comment by ahmedabu98** [comment]
assign set of reviewers

**Comment by ahmedabu98** [comment]
CC: @arthurpessoa, @chamikaramj

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java [hunk 1]
```diff
@@ -0,0 +1,289 @@
...
+      // build a cache of RecordWriters.
+      // writers will expire after 1 min of idle time.
+      // when a writer expires, its data file is collected.
+      this.writers =
+          CacheBuilder.newBuilder()
+              .expireAfterAccess(1, TimeUnit.MINUTES)
+              .removalListener(
+                  (RemovalNotification<PartitionKey, RecordWriter> removal) -> {
+                    final RecordWriter recordWriter =
+                        Preconditions.checkNotNull(removal.getValue());
```
Comment (kennknowles) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java:110]: Recommend using Beam's fork of `Preconditions` which raises correct exceptions and differentiates `IllegalStateException` and `IllegalArgumentException`. Guava is incorrect - it just raises NPE which should only be raised when the code in question has failed, not in response to bad data.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java [hunk 2]
```diff
@@ -0,0 +1,289 @@
...
+                    try {
+                      recordWriter.close();
+                      openWriters--;
+                      dataFiles.add(recordWriter.getDataFile());
+                    } catch (IOException e) {
+                      throw new RuntimeException(e);
```
Comment (kennknowles) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java:116]: This exception only comes from `recordWriter.close()` right? Perhaps narrow the scope of the catch-and-rethrow to make this clear? Or if it could come from multiple lines, it would be best to catch them separate and add some information to the propagated exception.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java [hunk 3]
```diff
@@ -0,0 +1,289 @@
...
+      this.fileIO = table.io();
+
+      // build a cache of RecordWriters.
+      // writers will expire after 1 min of idle time.
+      // when a writer expires, its data file is collected.
+      this.writers =
+          CacheBuilder.newBuilder()
+              .expireAfterAccess(1, TimeUnit.MINUTES)
+              .removalListener(
+                  (RemovalNotification<PartitionKey, RecordWriter> removal) -> {
```
Comment (kennknowles) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java:108]: Readability nit: I think this lambda would actually be more readable as a named method, especially since it mutates instance fields.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java [hunk 4]
```diff
@@ -0,0 +1,289 @@
...
+ * <ol>
+ *   <li>Close all underlying {@link RecordWriter}s
+ *   <li>Collect all {@link DataFile}s
+ *   <li>Create a new {@link ManifestFile} referencing these {@link DataFile}s
+ * </ol>
+ *
+ * <p>After closing, the resulting {@link ManifestFile}s can be retrieved using {@link
+ * #getManifestFiles()}.
+ */
+class RecordWriterManager {
```
Comment (kennknowles) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java:72]: Based on the documentation, this might be accurately named `PartitionedRecordWriter` or something. That communicates better than "Manager" which could mean almost anything. And it seems it could be `Autocloseable` which would enable using it in try-with-resources blocks, no?

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteGroupedRowsToFiles.java [hunk 5]
```diff
@@ -75,28 +84,35 @@ private org.apache.iceberg.catalog.Catalog getCatalog() {
...
+        PaneInfo pane)
+        throws Exception {
 
       Row destMetadata = element.getKey().getKey();
       IcebergDestination destination = dynamicDestinations.instantiateDestination(destMetadata);
-      RecordWriter writer = createWriter(destination);
+      WindowedValue<IcebergDestination> windowedDestination =
+          WindowedValue.of(destination, window.maxTimestamp(), window, pane);
+      RecordWriterManager writer =
+          new RecordWriterManager(getCatalog(), filePrefix, maxFileSize, Integer.MAX_VALUE);
```
Comment (kennknowles) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteGroupedRowsToFiles.java:100]: With above change to autocloseable and rename, everything up to `close()` becomes:

```
try(PartitionedWriter writer = new PartitionedWriter(getCatalog(), filePrefix, maxFileSize, Integer.MAX_VALUE) {
   ...
}
```

Otherwise, you want a `try { ... } finally { close() }` pattern I think. But try-with-resources is easier to read and more robust.

**Review by kennknowles — COMMENTED** [review]
Fairly quick pass

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java (hunk 1 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java]: Thanks, I substituted it for our `checkStateNotNull()`

I still needed Guava's Preconditions because Beam doesn't have equivalents for  `checkArgument()`, `checkState()`

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java (hunk 2 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java]: Yep, just from `recordWriter.close()`. Narrowing it down

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java (hunk 3 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java]: Thanks, done

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java (hunk 4 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java]: I originally had it as `PartitionedRecordWriter` but thought it may be misleading since the class is also used for unpartitioned writes

Added Autocloseable implementation

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteGroupedRowsToFiles.java (hunk 5 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/WriteGroupedRowsToFiles.java]: Done

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java (hunk 3 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java:111]: Actually this ends up complaining that we're trying to use an instance method while the DestinationState is still under initialization. There might be a way around this but it will require some refactoring, so I'm leaning towards keeping it the way it is

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java [hunk 6]
```diff
@@ -17,15 +17,12 @@
  */
 package org.apache.beam.sdk.io.iceberg;
 
-import static org.apache.beam.sdk.io.iceberg.IcebergUtils.beamRowToIcebergRecord;
```
Comment (liferoad) [inline sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java:20]: can we add this to CHANGES.md to call it out?

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java (hunk 1 above)
Comment (kennknowles) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java]: 👍  those Guava methods throw the right kind of exception so they are g2g

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java (hunk 4 above)
Comment (kennknowles) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriterManager.java]: Fair enough. A reason I don't like the "Manager" name is that I don't know what it is doing in the managing, and it really doesn't communicate that this is a thing that does the writing. We have so many things called "manager" and none of them have anything in common.

**Review by kennknowles — APPROVED** [review]
LGTM to get it merged for the release.

File: sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java (hunk 6 above)
Comment (ahmedabu98) [reply sdks/java/io/iceberg/src/main/java/org/apache/beam/sdk/io/iceberg/RecordWriter.java:20]: done
