### PR TITLE
#25962 Fix for Java SDF-based Kafka ingestion being stuck at certain offsets in certain conditions

### LINKED ISSUE #25962: [Bug]: Java SDF-based Kafka ingestion can be stuck at certain offsets in certain conditions
### What happened?

Scenario:
Batch Kafka ingestion (`.withStartReadTime()`, `.withStopReadTime()`, experiments: `beam_fn_api`, `unsafely_attempt_to_process_unbounded_data_in_batch_mode`, `shuffle_mode=appliance`) reading a few billions / few hundred gb of kafka records from a few hundred ktable topic partitions. Some of these partitions has a tendency to get stuck.

The issue started happening with 2.45 (still do with 2.46), so my original idea was that there must have been some change introduced in 2.45 that caused this. ... but after some investigation my guess is that previously it was just hidden/supressed, but the issue already existed and some change only revealed/emphasized it.

So I think the problematic part is this: https://github.com/apache/beam/blob/ddae966f3346fbe247486324cbf8a8a532895316/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java#L383-L388

What causes the issue is that the `consumer.poll` can return `ConsumerRecords` that contains no `KafkaRecord` - so we assume we have reached the end - when there are still remaining records to be consumed. This happens because if you check the kafka consumer implementation ( https://github.com/apache/kafka/blob/f79c2a6e04129832eacec60bbc180173ecc37549/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L1259-L1276 and https://github.com/apache/kafka/blob/f79c2a6e04129832eacec60bbc180173ecc37549/clients/src/main/java/org/apache/kafka/clients/consumer/internals/Fetch.java#L102-L104 ) you can see that the `poll()` will consider a `Fetch` "successful" if the "position has advanced" even if the `numRecords` is 0.

I'm not completely sure this is the reason, but totally seems plausible to me:
So lets assume we have KTable kafka topics with key compaction turned on. Lets assume they exist for a long time, and has a very huge compaction rate (only a few percent of the offsets contain a record.) It is not hard to imagine there are huge ranges of offsets that has no records. Well this is the case with our topics.

So what I see is that it tries to poll, gets back an "empty" `ConsumerRecords` (0 record, but `positionAdvanced` is true), and returns with a `ProcessContinuation.resume()`. This keeps repeating forever.

The loop happens because, we stop the current consumption with a return, and the next `processElement()` will `seek()` the consumer to the `startOffset` (aka `tracker.currentRestriction().getFrom()`  https://github.com/apache/beam/blob/ddae966f3346fbe247486324cbf8a8a532895316/sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java#L376 ), but in the previous `processElement()` we didn't notify the tracker of the progress at all, so the `startOffset` stays the same.

Essentially what was fixed with the watermark for streaming jobs with https://github.com/apache/beam/pull/24205 has to be also fixed for the tracker/restriction/offset.

In order to solve this we have to know if the "empty" `ConsumerRecord` is really at the end of the stream, or it's just at a "gap".

So what I came up with as some possible solutions:
1. Contribute to [Kafka](https://github.com/apache/kafka) so the returned `ConsumerRecords` contains some distinction between the two types of "empty". (Essentially representing `positionAdvanced`, or possible the consumer position.) - _No idea if they will accept it, and even if they do it's going to take the longest to include in beam_
2. Compare `consumer.position()` before and after `consumer.poll()` to figure out if we have "advanced" or not. - _It can be used to detect the advancement, but not sure if the position of the consumer always correlates with the end of the returned range or it might differ so if it can be used to update the tracker or not_
3. Compare the returned `ConsumerRecords` to `ConsumerRecords.EMPTY` - _I would say this is ugly as it's an implementation detail of the Kafka library, but we can test if they change it with unit tests_
4. Check if `((HasProgress) tracker).getProgress().getWorkRemaining()` is positive. - _I'm not sure how up-to-date that information is, but it can certainly indicate if we are in a huge gap in the middle of the processing._
5. Check if this is a BOUNDED or UNBOUNDED consumption as batch pipelines should return with a `.stop()` when they reach the end of the range anyway. - _This will fix this issue only when consuming kafka in batch pipelines, but this could most likely happen with streaming pipelines too if they use the same SDF implementation._

Once we know what case we encountered, we can either continue the `while (true)` loop and `poll` the next batch, or if we have the position/offset, we can update the tracker and return with `.resume()`.

FYI increasing batch/poll size by increasing `ConsumerConfig.FETCH_MAX_BYTES_CONFIG`, `ConsumerConfig.MAX_POLL_RECORDS_CONFIG`, etc alleviates the issue, but doesn't fix it completely.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [x] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by nbali**
fixes #25962

**Please** add a meaningful description for your change here
This fix simulate the behaviour of `org.apache.kafka:kafka-clients` prior to `3.2.0` even if a newer version is being used.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - ~[ ] Update `CHANGES.md` with noteworthy changes.~
 - ~[ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).~

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java [hunk 1]
```diff
@@ -424,6 +425,29 @@ public ProcessContinuation processElement(
...
+    final Stopwatch sw = Stopwatch.createStarted();
+    long previousPosition = -1;
+    while (true) {
+      final ConsumerRecords<byte[], byte[]> rawRecords =
+          consumer.poll(KAFKA_POLL_TIMEOUT.minus(sw.elapsed()));
+      if (!rawRecords.isEmpty()) {
+        // return as we have found some entries
+        return rawRecords;
+      }
+      if (previousPosition == (previousPosition = consumer.position(topicPartition))) {
```
Comment (nbali) [inline sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java:440]: I'm not completely sure we need this. There is a pretty high chance it works flawlessly even without this.

Comment (nbali) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java:440]: (end of stream -> no offset change possible)
pre-3.2.0+EOS -> poll should block for timeout already, return empty, *both position and timeout check should return*
post-3.2.0+EOS -> poll should block for timeout already, return empty, *both position and timeout check should return*

(small gap -> timeout is enough to iterate over it)
pre-3.2.0+small gap -> poll blocks until it returns a non-empty result, *non-empty check should return*
post-3.2.0+small gap -> poll return empty immediately, *every check fails*

(big gap -> timeout isn't enough to iterate over it)
pre-3.2.0+big gap -> poll should block for timeout already, return empty, *timeout check should return*
post-3.2.0+big gap -> poll return empty immediately, *every check fails*

So _theoretically_ there isn't any scenario where the position check triggers the return, but nothing else.

**Comment by Abacn** [comment]
Run Java_Kafka_IO_Direct PreCommit

**Comment by nbali** [comment]
Run Java_Kafka_IO_Direct PreCommit

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java [hunk 2]
```diff
@@ -424,6 +425,29 @@ public ProcessContinuation processElement(
...
   }
 
+  // see https://github.com/apache/beam/issues/25962
+  private ConsumerRecords<byte[], byte[]> poll(
+      Consumer<byte[], byte[]> consumer, TopicPartition topicPartition) {
+    final Stopwatch sw = Stopwatch.createStarted();
+    long previousPosition = -1;
+    while (true) {
+      final ConsumerRecords<byte[], byte[]> rawRecords =
+          consumer.poll(KAFKA_POLL_TIMEOUT.minus(sw.elapsed()));
```
Comment (johnjcasey) [inline sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java:435]: Based on a test failure, it looks like this can get negative, which we would need to avoid

**Comment by johnjcasey** [comment]
Structurally, this looks good to me. There are some test failures, and I'll defer to your judgement on whether we need the extra checking block or not

File: sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java (hunk 2 above)
Comment (nbali) [reply sdks/java/io/kafka/src/main/java/org/apache/beam/sdk/io/kafka/ReadFromKafkaDoFn.java]: Should be fixed now.

**Comment by nbali** [comment]
.

**Comment by johnjcasey** [comment]
LGTM
