### PR TITLE
Fix PostCommit Java ValidatesRunner Samza job

### LINKED ISSUE #31725: The PostCommit Java ValidatesRunner Samza job is flaky
The PostCommit Java ValidatesRunner Samza is failing over 50% of the time.
Please visit https://github.com/apache/beam/actions/workflows/beam_PostCommit_Java_ValidatesRunner_Samza.yml?query=is%3Afailure+branch%3Amaster to see all failed workflow runs.
See also Grafana statistics: http://metrics.beam.apache.org/d/CTYdoxP4z/ga-post-commits-status?orgId=1&viewPanel=3&var-Workflow=PostCommit%20Java%20ValidatesRunner%20Samza

### PR DESCRIPTION
**Pull request by Amar3tto**
Fixes #31725

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Amar3tto** [comment]
Run Samza ValidatesRunner

**Comment by Amar3tto** [comment]
Run Samza ValidatesRunner

**Comment by Amar3tto** [comment]
R: @Abacn

File: sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java [hunk 1]
```diff
@@ -733,7 +733,7 @@ public void testWriteUnboundedWithCustomBatchParameters() throws Exception {
         LINES2_ARRAY,
         null,
         null,
-        3,
+        0,
         baseFilename,
```
Comment (Abacn) [inline sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java:737]: this test is exercises by different runner's vallidaterunner test suite. Only SamzaRunner fails. Would this change break other runners test?

Probably we just need to exclude this specific test from validateRunner target in runners/samza/build.gradle

Comment (Amar3tto) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java:737]: It doesn't break other tests (tested with DirectRunner). If we pass 0, then it searches for `file.txt*`.

Comment (Abacn) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java:737]: I see, then it will no longer assert if the GroupintoBatches works as intended for those runners currently passing this test. Still think exclude from SamzaRunner test suite is preferred for now

Comment (Amar3tto) [reply sdks/java/core/src/test/java/org/apache/beam/sdk/io/TextIOWriteTest.java]: Done

**Review by Abacn — APPROVED** [review]
