### PR TITLE
Fix SpannerIO flakes

### LINKED ISSUE #21729: [Bug]: Flaky test  org.apache.beam.sdk.io.gcp.spanner.SpannerIOWriteExceptionHandlingTest.testExceptionHandlingForWriteGrouped
### What happened?

The test `org.apache.beam.sdk.io.gcp.spanner.SpannerIOWriteExceptionHandlingTest.testExceptionHandlingForWriteGrouped`
([SpannerIOWriteExceptionHandlingTest.java:222](https://github.com/apache/beam/blob/3c623abd631b493c8a71d05fe591065754c75d0c/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java#L222)) seems to be flaky as a sleeper can be fired more or less times than what is required (I have seen errors with both 8 and 10 times instead of the required 9)

```
> is a org.mockito.exceptions.verification.TooManyActualInvocations
Stacktrace was: org.mockito.exceptions.verification.TooManyActualInvocations: 
sleeper.sleep(<any long>);
Wanted 9 times:
-> at org.apache.beam.sdk.io.gcp.spanner.SpannerIOWriteExceptionHandlingTest.testExceptionHandlingForWriteGrouped(SpannerIOWriteExceptionHandlingTest.java:222)
But was 10 times:
```

### Issue Priority

Priority: 2

### Issue Component

Component: io-java-gcp

### LINKED ISSUE #21999: [Bug]: org.apache.beam.sdk.io.gcp.spanner.SpannerIOReadTest.runBatchQueryTestWithFailures flaky
### What happened?

Example: https://ci-beam.apache.org/job/beam_PreCommit_Java_Phrase/5314/

### Issue Priority

Priority: 1

### Issue Component

Component: io-java-gcp

### PR DESCRIPTION
**Pull request by Abacn**
This fixes #21999

~Also fixes #21729~

* Fix runBatchQueryTestWithFailures api call verify condition.
  Also remove PAssert that never executes due to exception thrown upstream

* Fix SpannerIOWriteExceptionHandlingTest

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @johnjcasey

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java [hunk 1]
```diff
@@ -171,9 +163,21 @@ public void testExceptionHandlingForSimpleWrite() throws InterruptedException {
...
     } finally {
-      verify(SpannerIO.WriteToSpannerFn.sleeper, times(callsToSleeper)).sleep(anyLong());
-      verify(serviceFactory.mockDatabaseClient(), times(callsToWrite))
-          .writeAtLeastOnceWithOptions(any(), any(Options.ReadQueryUpdateTransactionOption.class));
+      if (exceptionErrorcode == ErrorCode.DEADLINE_EXCEEDED) {
+        // Due to randomOffset retry is done by most likely but not always 9 times.
+        int sleepCalled =
+            Mockito.mockingDetails(SpannerIO.WriteToSpannerFn.sleeper).getInvocations().size();
+        assertTrue(sleepCalled >= 8);
+        assertTrue(sleepCalled <= 10);
```
Comment (Abacn) [inline sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java:171]: Ran backOff 1 milliion times and found number of retry is distributed as: {8=52661, 9=878266, 10=69073}. i.e. Originally it has a flake probability of 12%

**Comment by Abacn** [comment]
R: @nielm

**Comment by johnjcasey** [comment]
@byronellis is this the same issue you were looking at?

**Comment by Abacn** [comment]
oops #21729 and #22008 are duplicated and I did not notice the later by the time of this solution.

**Comment by byronellis** [comment]
This approach works too, though I'd go the extra step and "invert" the test---method per error type and then testing the responses from single and batched writes via a helper method rather than special casing the error type in the loop

**Comment by byronellis** [comment]
[Another approach](https://github.com/apache/beam/pull/22035) over here

**Comment by Abacn** [comment]
> This approach works too, though I'd go the extra step and "invert" the test---method per error type and then testing the responses from single and batched writes via a helper method rather than special casing the error type in the loop

Time_exceed and other error types are treated differently in the tested DoFn and that's why I did branching here. Fine to me since they fixes flakes.

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java (hunk 1 above)
Comment (nielm) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java:171]: That was more effort than I was prepared to do - I was just going to test that steeps >= 8 and  writes >= 9!

**Comment by nielm** [comment]
> This approach works too, though I'd go the extra step and "invert" the test---method per error type and then testing the responses from single and batched writes via a helper method rather than special casing the error type in the loop

I was also half-way through a PR for this. 

In my solution I was just going to switch from numSleeps, numWrites parameters to a "hasRetries" parameter, then then if there are retries assert that numSleeps >= 8 and numWrites >= 9

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java [hunk 2]
```diff
@@ -73,49 +70,43 @@ public static Collection<Object[]> data() {
     return Arrays.asList(
         new Object[][] {
           // DEADLINE_EXCEEDED is the only exception type that generates retries in-SDK
-          // The default backoff generates 9 retries, and then errors out the pipeline.
-          {ErrorCode.DEADLINE_EXCEEDED, "deadline passed!", 9, 10},
+          // The default backoff generates _ABOUT_ 9 retries, and then errors out the pipeline.
+          {ErrorCode.DEADLINE_EXCEEDED, "deadline passed!"},
```
Comment (nielm) [inline sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIOWriteExceptionHandlingTest.java]: Rather than testing for DEADLINE_EXEEDED in the assert, put a hasRetries parameter here, and use that to determine whether to test no sleeps and 1 write, or writes >=9 and sleeps => 8

**Comment by Abacn** [comment]
> 

Yeah agree. Exact number retry is implementation details of backOff which is not needed to test here. Dropped this approach as this test is fixed in #22035.

**Comment by byronellis** [comment]
It's more a comment on the structure of the test suite. In the original suite, which assumes all the results are deterministic, you want to test many different error scenarios parameterized by number of retries (number of calls parameter is redundant as its always number of retries + 1) 

Fixing DEADLINE_EXCEEDED changes by putting the number of retries into a range. That suggests a third maybe even cleaner approach which would be to specify a min and max number of expected calls and then just drop the sleeper check entirely.

**Review by nielm — APPROVED** [review]

**Comment by Abacn** [comment]
R: @pabloem

**Comment by Abacn** [comment]
JavaPreCommit failed due to StyleCheck violation in master which is just fixed in #22046

**Comment by pabloem** [comment]
ok lgtm
