### PR TITLE
[Playground] infrastructure ci/cd unify

### LINKED ISSUE #24645: [Task]: Amend CI/CD Python scripts
### What needs to happen?

CD scripts sends RunCode requests to runners to ensure examples are correct before they can be stored in Datastore. In some cases, failed examples are saved to Datastore regardless of runner status.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by eantyshev**
resolves #24645

### Unify CI and CD logic
To use the same code for examples validation, to make CD step more stable
Specifically, `ci_helper.CIHelper` and `cd_helper::CDHelper` were merged into `verify::Verifier`

### Use [pydantic](https://docs.pydantic.dev/) instead of hand-written validators
To optimize `beam-playground` tag content verification and other example's properties
Easy-to-implement additional validators (and enrichers that were scattered across the code)
Found a context_line bug in one of Python katas, after applying line_context validators.

### Kafka examples tag: make `emulators` a list
__note__ Playground API isn't changed
It makes the logic more maintainable, reduces "1 emulator, 1 dataset" limitation of the initial version of code

### Unittest
Pytest common fixtures to create Example/Tag objects, revised test_helper.py

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: learning/katas/python/Examples/Word Count/Word Count/task.py [hunk 1]
```diff
@@ -18,7 +18,7 @@
 #   name: WordCountKata
 #   description: Task from katas to create a pipeline that counts the number of words.
 #   multifile: false
```
Comment (eantyshev) [inline learning/katas/python/Examples/Word Count/Word Count/task.py:20]: that's the mistake that previous validation didn't find

File: examples/java/src/main/java/org/apache/beam/examples/KafkaWordCountJson.java [hunk 2]
```diff
@@ -32,14 +32,14 @@
 //     - strings
 //     - emulator
 //   emulators:
```
Comment (eantyshev) [inline examples/java/src/main/java/org/apache/beam/examples/KafkaWordCountJson.java:34]: Using `kafka` as a mapping key is questionable, since it is a `type` of emulator

File: playground/infrastructure/config.py [hunk 3]
```diff
@@ -57,7 +55,7 @@ class Config:
     ]
     BEAM_PLAYGROUND_TITLE = "beam-playground:\n"
     BEAM_PLAYGROUND = "beam-playground"
```
Comment (eantyshev) [inline playground/infrastructure/config.py:57]: this minor setting impoves pytest timings

File: playground/infrastructure/conftest.py [hunk 4]
```diff
@@ -0,0 +1,99 @@
...
+            "categories": ["Testing", "Schemas"],
+            "pipeline_options": "--MOCK_OPTION MOCK_OPTION_VALUE",
+        }
+        if with_kafka:
+            meta.update(
+                emulators=[
+                    {"type": "kafka", "topic": {"id": "topic1", "source_dataset": "dataset_id_1"}}
+                ],
+                datasets={"dataset_id_1": {"format": "avro", "location": "local"}},
+            )
```
Comment (eantyshev) [inline playground/infrastructure/conftest.py:86]: this logic allows to test absent fields

File: learning/katas/python/Examples/Word Count/Word Count/task.py [hunk 5]
```diff
@@ -18,7 +18,7 @@
...
-#   context_line: 29
+#   context_line: 32
```
Comment (eantyshev) [inline learning/katas/python/Examples/Word Count/Word Count/task.py:21]: that's the mistake that previous validation didn't find

**Review by damccorm — COMMENTED** [review]
LGTM (pending CI), just had one minor question

File: playground/infrastructure/datastore_client.py [hunk 6]
```diff
@@ -29,18 +28,13 @@
...
 
 
 class DatastoreException(Exception):
-    def __init__(self, error: str):
-        super().__init__()
-        self.msg = error
-
-    def __str__(self):
-        return self.msg
+    pass
```
[the remark this answers is not in the document]
Comment (eantyshev) [reply playground/infrastructure/datastore_client.py:38]: This logic is trivial and is already implemented in BaseException
https://docs.python.org/3/library/exceptions.html#base-classes

File: playground/infrastructure/verify.py [hunk 7]
```diff
@@ -13,56 +13,90 @@
...
+        Outputs for multifile examples are left empty.
         """
-        single_file_examples = list(filter(
-            lambda example: example.tag.multifile is False, examples))
-        set_dataset_path_for_examples(single_file_examples)
-        async with GRPCClient() as client:
-            await get_statuses(client, single_file_examples)
-            await self._verify_examples(client, single_file_examples, origin)
+        single_file_examples = list(
+            filter(lambda example: example.tag.multifile is False, examples)
```
Comment (olehborysevych) [inline playground/infrastructure/verify.py:56]: @eantyshev Looks like we are doing this two times. First time in _run_ci_cd. Is it intended?

Comment (eantyshev) [reply playground/infrastructure/verify.py]: Nope, it is redundant, removed
Thanks for pointing out!

**Review by damccorm — APPROVED** [review]
