### PR TITLE
Do not panic if an element has no windows during PersistBundle.

### LINKED ISSUE #36609: [Bug]: Failed pipeline on Prism when sliding window size is smaller than sliding interval
### What happened?

The following code failed to run in Prism. This is a special use case of sliding window, where the window size is smaller than the sliding interval. This leads to some timestamps being filtered.

```python
import logging

import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions
from apache_beam.transforms.window import TimestampedValue, SlidingWindows
from apache_beam.utils.timestamp import Timestamp

logging.basicConfig(level=logging.INFO)


options = PipelineOptions([
    "--environment_type=LOOPBACK",
    "--runner=PrismRunner",
])


with beam.Pipeline(options=options) as p:
  now = Timestamp.now()
  _ = (
      p | beam.Create([TimestampedValue(1, 1),
                       TimestampedValue(2, 2),
                       TimestampedValue(3, 3),
                       TimestampedValue(4, 4),
                       TimestampedValue(5, 5),
                       TimestampedValue(6, 6),
                       TimestampedValue(7, 7),
                       TimestampedValue(8, 8),
                       TimestampedValue(9, 9),
                       TimestampedValue(10, 10)],
                       )
      | beam.WithKeys(0)
      | beam.WindowInto(SlidingWindows(5, 10))
      | beam.LogElements(
          prefix="result=",
          level=logging.WARNING,
          with_timestamp=True,
          with_window=True,
          use_epoch_time=True))

```

Error message is like:

```
error decoding residual header: sdk provided a windowed value header 0 windows
```

On the other hand, FnApiRunner and Dataflow Runner both returns elements in the windows correctly.

```
WARNING:root:result=(0, 1), timestamp=1, window(start=0, end=5)
WARNING:root:result=(0, 2), timestamp=2, window(start=0, end=5)
WARNING:root:result=(0, 3), timestamp=3, window(start=0, end=5)
WARNING:root:result=(0, 4), timestamp=4, window(start=0, end=5)
WARNING:root:result=(0, 10), timestamp=10, window(start=10, end=15)
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by shunping**
After removing the panic statement, such element will be ignored in the current prism implementation.

fixes #36609

### CODE REVIEW

**Comment by shunping** [comment]
cc'ed @lostluck

File: sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go [hunk 1]
```diff
@@ -791,8 +791,7 @@ func reElementResiduals(residuals []Residual, inputInfo PColInfo, rb RunBundle)
 			panic("error decoding residual header:" + err.Error())
 		}
 		if len(ws) == 0 {
-			slog.Error("reElementResiduals: sdk provided a windowed value header 0 windows", "bundle", rb)
-			panic("error decoding residual header: sdk provided a windowed value header 0 windows")
+			slog.Warn("reElementResiduals: sdk provided a windowed value header 0 windows", "bundle", rb)
```
Comment (liferoad) [inline sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go:794]: do we need to mention this could cause data loss? or make the warning message more clear about why this happens?

Comment (shunping) [reply sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go:794]: Dataflow and FnAPI runners all silently drop these events without  even a warning. Not sure if we want to handle that more differently prism.

On the other hand, we may add a warning message at the SDK side when a user tries to initialize a sliding window with the slide interval longer than window size.

Comment (liferoad) [reply sdks/go/pkg/beam/runners/prism/internal/engine/elementmanager.go:794]: Sounds good if we can add a warning message for SDKs.
