### PR TITLE
Attempt deserialize all non-standard portable logical types from proto

### LINKED ISSUE #24870: [Bug]: Encoding issue when reading BQ query result set in DataflowRunner
### What happened?

I tried to run a pipeline that ran a SQL query with a BQ DATE field in the result set with DataflowRunner and it resulted in an encoding error.  The exception message suggests that the correct coder was chosen (The Date logical type resolves to a Long) but the value resolution doesn't appear to happen with DataflowRunner.  It did with DirectRunner.

Affected Runners: DataflowRunner (DirectRunner with 2.43.0 and previous versions was fine)
Affected Versions: 2.43.0 (2.41.0, 2.42.0 do not appear to exhibit this behaviour.)

Sample Code

```
import com.google.api.services.bigquery.model.TableRow;
import org.apache.beam.runners.dataflow.options.DataflowPipelineOptions;
import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.MapElements;
import org.apache.beam.sdk.transforms.ParDo;
import org.apache.beam.sdk.values.PCollection;
import org.apache.beam.sdk.values.Row;
import org.apache.beam.sdk.values.TypeDescriptors;

import java.io.File;
import java.util.Arrays;
import java.util.stream.Collectors;

public class TestPipeline {
    public static void main(String[] args) {
        PipelineOptionsFactory.register(DataflowPipelineOptions.class);
        DataflowPipelineOptions options = PipelineOptionsFactory.fromArgs(args).as(DataflowPipelineOptions.class);
        options.setFilesToStage(
                Arrays.stream(System.getProperty("java.class.path").
                        split(File.pathSeparator)).
                        map(entry -> (new File(entry)).toString()).collect(Collectors.toList()));


        String testQuery = "select cast(\"2022-12-21\" as date) dt";
        Pipeline pipeline = Pipeline.create(options);
        PCollection<TableRow> tableRows = pipeline.apply(BigQueryIO.readTableRowsWithSchema()
                .fromQuery(testQuery)
                .usingStandardSql()
        );
        PCollection<Row> rows = tableRows.apply(MapElements.into(TypeDescriptors.rows())
                .via(tableRows.getToRowFunction()))
                .setRowSchema(tableRows.getSchema());
        rows.apply("println", ParDo.of(new DoFn<Row, Row>() {
            @ProcessElement
            public void processElement(@Element Row row) {
                System.out.println("println row" + row);
            }
        })).setRowSchema(tableRows.getSchema());
        pipeline.run();
    }
}
```

Exception
```
Error message from worker: java.lang.IllegalArgumentException: Unable to encode element 'GenericData{classInfo=[f], {dt=2022-12-21}}' with coder 'SchemaCoder<Schema: Fields:
Field{name=dt, description=, type=LOGICAL_TYPE, options={{}}}
Encoding positions:
{dt=0}
Options:{{}}UUID: 9622aec6-90b4-4021-b112-a7e4d2abecef  UUID: 9622aec6-90b4-4021-b112-a7e4d2abecef delegateCoder: org.apache.beam.sdk.coders.Coder$ByteBuddy$0cxD4zOH@3ef9d47a'.
	org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:300)
	org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
	org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:642)
	org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:558)
	org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$ElementByteSizeObservableCoder.registerByteSizeObserver(IntrinsicMapTaskExecutorFactory.java:403)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputObjectAndByteCounter.update(OutputObjectAndByteCounter.java:128)
	org.apache.beam.runners.dataflow.worker.DataflowOutputCounter.update(DataflowOutputCounter.java:67)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:43)
	org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:275)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:85)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:423)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:411)
	org.apache.beam.sdk.io.gcp.bigquery.PassThroughThenCleanup$IdentityFn.processElement(PassThroughThenCleanup.java:84)
Caused by: java.lang.ClassCastException: java.time.LocalDate cannot be cast to java.lang.Long
	org.apache.beam.sdk.coders.VarLongCoder.encode(VarLongCoder.java:35)
	org.apache.beam.sdk.schemas.SchemaCoderHelpers$LogicalTypeCoder.encode(SchemaCoderHelpers.java:89)
	org.apache.beam.sdk.coders.RowCoderGenerator$EncodeInstruction.encodeDelegate(RowCoderGenerator.java:333)
	org.apache.beam.sdk.coders.Coder$ByteBuddy$0cxD4zOH.encode(Unknown Source)
	org.apache.beam.sdk.coders.Coder$ByteBuddy$0cxD4zOH.encode(Unknown Source)
	org.apache.beam.sdk.schemas.SchemaCoder.encode(SchemaCoder.java:124)
	org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:297)
	org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
	org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:642)
	org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:558)
	org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$ElementByteSizeObservableCoder.registerByteSizeObserver(IntrinsicMapTaskExecutorFactory.java:403)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputObjectAndByteCounter.update(OutputObjectAndByteCounter.java:128)
	org.apache.beam.runners.dataflow.worker.DataflowOutputCounter.update(DataflowOutputCounter.java:67)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:43)
	org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:285)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:275)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900(SimpleDoFnRunner.java:85)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:423)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:411)
	org.apache.beam.sdk.io.gcp.bigquery.PassThroughThenCleanup$IdentityFn.processElement(PassThroughThenCleanup.java:84)
	org.apache.beam.sdk.io.gcp.bigquery.PassThroughThenCleanup$IdentityFn$DoFnInvoker.invokeProcessElement(Unknown Source)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:211)
	org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:188)
	org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:340)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process(ParDoOperation.java:44)
	org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:49)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:218)
	org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:169)
	org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:83)
	org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:420)
	org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:389)
	org.apache.beam.runners.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:314)
	org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:140)
	org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:120)
	org.apache.beam.runners.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:107)
	java.util.concurrent.FutureTask.run(FutureTask.java:266)
	org.apache.beam.sdk.util.UnboundedScheduledExecutorService$ScheduledFutureTask.run(UnboundedScheduledExecutorService.java:162)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	java.lang.Thread.run(Thread.java:748)
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
Fixes #24870

* Fixes portable and not-yet-standard logical type get deserialized to UnknownLogicalType

**Please** add a meaningful description for your change here

This was broken by #23014 in particular, prior to the change, SchemaTransform sets the identifier of all  not-yet-STANDARD logical types as "beam:logical_type:java_sdk:v1" when translating to proto

https://github.com/apache/beam/blob/release-2.42.0/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java#L183

after the change, it keeps URNs of portable logical types (identifier is a URN starts with  "beam:logical_type:"). This enables translating them from another SDK.

https://github.com/apache/beam/blob/release-2.43.0/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java#L176

But, when translating back, the code here did not change accordingly:

https://github.com/apache/beam/blob/f9a86e5e2e3bbb345dad0953d7fe6a6b8ffe7a68/sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java#L417

Causing the deserialization not attempted and reduced to UnknownLogicalType.

Unfortunately Schema containing logical type with same identifier but different class is not considered equal, and is not caught by the unit test SchemaTranslationTest.FromProtoToProtoTest <- this could be a followup fix

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Abacn** [comment]
There is a draft PR #23785 ran the use case of #24870 and succeeded: https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV1_PR/158/testReport/org.apache.beam.sdk.io.gcp.bigquery/BigQueryIOJsonIT/testDateType/

Ran without this change indeed failed: https://ci-beam.apache.org/job/beam_PostCommit_Java_DataflowV1_PR/156/testReport/org.apache.beam.sdk.io.gcp.bigquery/BigQueryIOJsonIT/testDateType/

**Comment by Abacn** [comment]
CC: @ahmedabu98 
CC: @kennknowles

File: sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java [hunk 1]
```diff
@@ -426,26 +431,33 @@ private static FieldType fieldTypeFromProtoWithoutNullable(SchemaApi.FieldType p
...
-            argumentValue = fieldValueFromProto(argumentType, logicalType.getArgument());
+        } else if (urn.startsWith("beam:logical_type:")) {
+          try {
+            return FieldType.logicalType(
+                (LogicalType)
+                    SerializableUtils.deserializeFromByteArray(
+                        logicalType.getPayload().toByteArray(), "logicalType"));
+          } catch (IllegalArgumentException e) {
+            LOG.warn(
+                String.format(
```
Comment (kennknowles) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/schemas/SchemaTranslation.java:442]: `LOG.warn("Unable to deserialize the logical type {} from proto. Mark as UnknownLogicalType", urn)`

File: sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/SchemaTranslationTest.java [hunk 2]
```diff
@@ -395,6 +402,41 @@ public void typeInfoNotSet() {
...
+              .add(FieldType.logicalType(new NanosInstant()))
+              .add(FieldType.logicalType(new NanosDuration()))
+              .add(FieldType.logicalType(FixedBytes.of(10)))
+              .add(FieldType.logicalType(VariableBytes.of(10)))
+              .add(FieldType.logicalType(FixedString.of(10)))
+              .add(FieldType.logicalType(VariableString.of(10)))
+              .add(FieldType.logicalType(FixedPrecisionNumeric.of(10)))
+              .build();
+
+      for (Schema.FieldType fieldType : testCases) {
```
Comment (kennknowles) [inline sdks/java/core/src/test/java/org/apache/beam/sdk/schemas/SchemaTranslationTest.java:424]: You can do this with `@RunWith(Parameterized.class)` as a cleanup.

**Comment by Abacn** [comment]
Run Java PreCommit

**Comment by Abacn** [comment]
all test succeeded, PTAL @kennknowles thanks!

**Comment by kennknowles** [comment]
Nice!

**Review by kennknowles — APPROVED** [review]

**Comment by kennknowles** [comment]
Will you open a cherry pick pull request as well?

**Comment by Abacn** [comment]
> Will you open a cherry pick pull request as well?

Thanks!

opened #24925
