### PR TITLE
Install venv dependencies in local env setup

### LINKED ISSUE #24460: [Failing Test]: Local environment tests failing on GHA
### What happened?

These tests are consistently failing - https://github.com/apache/beam/actions/workflows/local_env_tests.yml?query=branch%3Amaster

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1

### Issue Component

Component: sdk-py-core

### PR DESCRIPTION
**Pull request by damccorm**
These are needed for setting up a virtual environment in various python versions. Right now, not having them can cause our local environment setup actions to fail, this fixes that problem. It also ensures that Python 3.8 is installed since that is the version we use by default (it seems like that version may have been removed from the runner images)

Fixes #24460

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: local-env-setup.sh [hunk 1]
```diff
@@ -55,6 +55,10 @@ if [ "$kernelname" = "Linux" ]; then
         exit
     fi
 
+    for ver in 3.7 3.8 3.9 3; do
```
Comment (AnandInguva) [inline local-env-setup.sh:58]: Can we add 3.10?

**Comment by damccorm** [comment]
R: @AnandInguva

**Review by AnandInguva — APPROVED** [review]
