### PR TITLE
Playground Cloud Build deployment and CI/CD triggers

### LINKED ISSUE #21350: [Playground] Run CI for examples for each PR
Need to add one more check (CI for examples) to verify examples automatically for each PR.

Imported from Jira [BEAM-13957](https://issues.apache.org/jira/browse/BEAM-13957). Original Jira may contain additional context.
Reported by: Aydar Zaynutdinov.

### LINKED ISSUE #21532: Collect And Deploy Playground Examples workflow consistently fails
https://github.com/apache/beam/actions/workflows/playground_deploy_examples.yml?query=is%3Afailure is failing consistently. Has failed 344 times and have never succeeded in the past 3 months.

Fails with:
```

Run helm del --namespace $K8S_NAMESPACE $HELM_APP_NAME
Error: Kubernetes cluster unreachable: Get
"http://localhost:8080/version": dial tcp [::1]:8080: connect: connection refused
Error: Process completed
with exit code 1.

```

Imported from Jira [BEAM-14154](https://issues.apache.org/jira/browse/BEAM-14154). Original Jira may contain additional context.
Reported by: lcwik.

### LINKED ISSUE #23600: [Playground] [Task]: Restore workflow trigger for Playground deploy examples GA
### What needs to happen?
Playground example deploy workflow was switched to manual trigger due to existing bug in workflow code.
Some broken examples might get into Playground storage bucket. New Playground CI/CD will address and fix this bug but it might catch broken examples before playground backend is redeployed. Since we plan to switch to new backend deployment model soon, we don't want to be blocked until backend is fixed. 
As soon as we switch to a new backend in GKE we need to return to automated triggers for this workflow

### Issue Priority
Priority: 3

### Issue Component
Component: beam-playground

### LINKED ISSUE #24706: [Task]: Update Playground infrastructure after deployment
### What needs to happen?

Clean up old scripts and GCP artifacts for old production environment (based on GCP AppEngine)
CD: Configure CB triggers to update a new staging environment when new Playground changes merged to master branch
CD: Configure triggers for CD examples pipeline to update example catalog when examples updated/added to master branch

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### LINKED ISSUE #25735: [Task]: Update Cloud Build configuration to deploy Playground Infrastructure
### What needs to happen?

Need to update #24006 according to new changes. 
Triggers should support deployment of multiple environments to the same GCP Project.

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by rshamunov**
Terraform scripts to create Cloud Build triggers to deploy Playground environment to a GCP project, to run CI validation to check GitHub PRs, to run CD to integrate new examples from master branch to the environment.

Resolves #23600
Resolves #25735
Resolves #21350
Resolves #21532
Resolves #24706

### CODE REVIEW

File: playground/infrastructure/cloudbuild/cloudbuild_playground_infra.sh [hunk 1]
```diff
@@ -40,6 +40,8 @@ git clone --branch $BRANCH_NAME $REPO_NAME --single-branch
 cd beam
 mkdir playground/terraform/environment/$ENVIRONMENT_NAME
  
+gcloud create bucket gs://$TF_VAR_state_bucket --location $TF_VAR_region --project $TF_VAR_project_id --pap
```
Comment (rshamunov) [inline playground/infrastructure/cloudbuild/cloudbuild_playground_infra.sh:43]: Check return value and exit the script if bucket can't be created. We should consider the case when the name is not unique

File: playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/secret.tf [hunk 2]
```diff
@@ -16,7 +20,7 @@ resource "google_secret_manager_secret" "secret_gh_pat_cloudbuild" {
 
 resource "google_secret_manager_secret_version" "secret_webhook_cloudbuild_trigger_cicd_data" {
   secret = google_secret_manager_secret.secret_webhook_cloudbuild_trigger_cicd.id
-  secret_data = var.data_for_cicd_webhook_secret
+  secret_data = random_string.data_for_cicd_webhook_secret.result
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/secret.tf:23]: This also should be pre-configured by user in GitHub WebHooks. Request the parameter,

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 3]
```diff
@@ -48,34 +48,25 @@ $BEAM_GIT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars
...
-image_tag = "playground-xxx"
-docker_repository_name = "playground-xxx"
-playground_region = "europe-west3"
-playground_zone = "europe-west3-c"
+playground_deploy_sa = "DEPLOY_SA_NAME"
+playground_update_sa = "UPDATE_SA_NAME"
+playground_ci_sa = "CI_SA_NAME"
+playground_cd_sa = "CD_SA_NAME"
+project_id = "PROJECT_ID"
+playground_environment_name = "ENVIRONMENT_NAME"
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:56]: Triggers not environment specific. Can you set environment-name to "environment" or "env" as default value for substitution and not request it?

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 4]
```diff
@@ -48,34 +48,25 @@ $BEAM_GIT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars
...
+playground_dns_name = "DNS"
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:57]: DNS is not environment specific. Set to default value, e.g. "fqdn.your.playground.zone"

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 5]
```diff
@@ -48,34 +48,25 @@ $BEAM_GIT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars
...
+playground_service_account = "SA_NAME"
+webhook_trigger_secret_id = "SECRET_ID"
+gh_pat_secret = "PAT_SECRET_ID"
+data_for_github_pat_secret = "PAT"
 trigger_source_repo = "https://github.com/apache/beam"
-project_id = "playground-xxx"
 terraform_source_repo = "https://github.com/apache/beam"
 terraform_source_branch = "master"
-state_bucket = "playground-xxx-terraform"
+state_bucket = "BUCKET_NAME"
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:69]: Do we need variables for public and private logs buckets?

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 6]
```diff
@@ -48,34 +48,25 @@ $BEAM_GIT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars
...
-playground_service_account = "playground-xxx-sa"
-datastore_namespace = "playground-xxx"
-webhook_trigger_secret_id = "playground-xxx-wb"
-gh_pat_secret = "playground-xxx"
-data_for_github_pat_secret = "GH_SECRET"
-data_for_cicd_webhook_secret = "RANDOM DATA" # will be automated
-private_logs_bucket = "playground-xxx"
+playground_service_account = "SA_NAME"
+webhook_trigger_secret_id = "SECRET_ID"
+gh_pat_secret = "PAT_SECRET_ID"
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:64]: Change gh_pat_secret->gh_pat_secret_id

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 7]
```diff
@@ -48,34 +48,25 @@ $BEAM_GIT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars
...
+data_for_github_pat_secret = "PAT"
 trigger_source_repo = "https://github.com/apache/beam"
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:66]: trigger_source_repo = "https://github.com/beamplayground/deploy-workaround"

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md (hunk 5 above)
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:69]: State backet is sent via -backend-config parameter. Do we need it here?

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 8]
```diff
@@ -48,34 +48,25 @@ $BEAM_GIT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars
...
-project_id = "playground-xxx"
 terraform_source_repo = "https://github.com/apache/beam"
 terraform_source_branch = "master"
-state_bucket = "playground-xxx-terraform"
+state_bucket = "BUCKET_NAME"
 ```
 
 Please make sure you change the values.
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:72]: terraform apply -var="project_id=$(gcloud config get-value project)" -var-file="../../../environment/cf07/common.tfvars"

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 9]
```diff
@@ -66,19 +98,26 @@ cd playground/terraform/infrastructure/cloudbuild-manual-setup/01.setup/
...
 # Run terraform commands
 terraform init -backend-config="bucket=$STATE_BUCKET"
-terraform apply -var="project_id=$(gcloud config get-value project)"
+terraform apply var="project_id=$(gcloud config get-value project)" -var-file="$BEAM_ROOT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars"
 ```
 
-## 2. Connect Apache Beam GitHub repository and GCP Cloud Build
 
-**Note:** Ensure correct `region` is set in [Cloud Build Triggers](https://console.cloud.google.com/cloud-build/triggers) page before proceeding further.
+## 3. Provide IAM role for Google-managed service account
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:105]: We use custom service accounts for triggers, not default Cloud Build SA

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 10]
```diff
@@ -66,19 +98,26 @@ cd playground/terraform/infrastructure/cloudbuild-manual-setup/01.setup/
...
+
+1. Navigate to GCP Console.
+2. Navigate to `IAM & Admin`.
+3. Check the box `Include Google-provided role grants` on the right side of the IAM & Admin page.
+4. Look for `service-XXXXXXXXXXX@gcp-sa-cloudbuild.iam.gserviceaccount.com` service account.
+5. Assign `Secret Manager Secret Accessor` to it.
 
-Follow [Connect to a GitHub repository](https://cloud.google.com/build/docs/automating-builds/github/connect-repo-github) to connect Apache Beam GitHub repository and GCP Cloud Build.
+## 4. Connect beamplayground/deploy-workaround GitHub repository and GCP Cloud Build
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:113]: It could be any repo. Define beamplayground/deploy-workaround as default value, but describe general approach

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 11]
```diff
@@ -88,29 +127,9 @@ cd ../02.builders
 
 # Run terraform commands
 terraform init -backend-config="bucket=$STATE_BUCKET"
-terraform apply -var="project_id=$(gcloud config get-value project)" -var="state_bucket=$STATE_BUCKET"
+terraform apply -var="project_id=$(gcloud config get-value project)" -var="state_bucket=$STATE_BUCKET" -var-file="$BEAM_ROOT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars"
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:130]: Do we need state_bucket var in terraform apply command line?

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 12]
```diff
@@ -31,18 +31,50 @@ Cloud Build triggers created by terraform scripts from this directory automate s
...
+$BEAM_GIT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars 
+```
+And put the following:
+```
+playground_deploy_sa = "DEPLOY_SA_NAME"
+playground_update_sa = "UPDATE_SA_NAME"
+playground_ci_sa = "CI_SA_NAME"
+playground_cd_sa = "CD_SA_NAME"
+project_id = "PROJECT_ID"
+playground_environment_name = "ENVIRONMENT_NAME"
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:56]: Remove all environment specific variables from the list. Set default values instead:
ENVIRONMENT_NAME  =  "environment"
image_tag = "tag"
playground_zone = "fqdn.playground.zone
playground_region = "us-central1"
playground_location = "us-central1-a"
playground_service_account = "pg-gke-sa-env" (SA name length is limited to 25 symbols)
skip_appengine_deploy  = false
state_bucket = "playground-tf-state-environment"

Comment (volatilemolotov) [reply playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:56]: What do you mean by environment specific?

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 13]
```diff
@@ -48,34 +48,25 @@ $BEAM_GIT/playground/terraform/environment/$ENVIRONMENT_NAME/common.tfvars
...
-playground_environment_name = "playground-xxx"
-playground_dns_name = "playground.dev"
-playground_network_name = "playground-xxx"
-playground_subnetwork_name = "playground-xxx"
-playground_gke_name = "playground-xxx"
-image_tag = "playground-xxx"
-docker_repository_name = "playground-xxx"
-playground_region = "europe-west3"
-playground_zone = "europe-west3-c"
+playground_deploy_sa = "DEPLOY_SA_NAME"
```
[the remark this answers is not in the document]
Comment (volatilemolotov) [reply playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:52]: Different variable name. Ill sync it

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md (hunk 8 above)
Comment (volatilemolotov) [reply playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:72]: Final agreement: cloudbuild-manual-setup/common.tfvars

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md (hunk 11 above)
Comment (volatilemolotov) [reply playground/terraform/infrastructure/cloudbuild-manual-setup/README.md]: No need for separate var, its provided via commons varfile

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 14]
```diff
@@ -31,18 +31,51 @@ Cloud Build triggers created by terraform scripts from this directory automate s
...
 ## 1. Set up the Google Cloud Build for your GCP project
 
-The `playground/terraform/infrastructure/cloudbuild-manual-setup/01.setup` provisions dependencies required to set up Cloud Build for Playground:
+First provide the variables by creating a `common.tfvars`
+```
+beam/playground/terraform/infrastructure/cloudbuild-manual-setup/common.tfvars 
+```
+And put the following:
+```
+playground_deploy_sa = "DEPLOY_SA_NAME" # SA name used for Deploy trigger
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:52]: align comments

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 15]
```diff
@@ -31,18 +31,51 @@ Cloud Build triggers created by terraform scripts from this directory automate s
...
+playground_environment_name = "environment" # Name of the environment. Used for prefixing (dev- stag- prod- etc.)
+playground_dns_name = "fqdm.playground.zone" # FQDN used for Playground deployment
+image_tag = "tag" # Container image tag to build
+playground_region = "us-central1" # GCP Region to deploy in
+playground_zone = "us-central1-a" # GCP Zone to deploy in
+skip_appengine_deploy = false # Workaround for Appengine issue. Appengine can only be deployed once so subsequent runs need to set this to true
+webhook_trigger_secret_id = "SECRET_ID" # Secret ID for webhook
+gh_pat_secret_id = "PAT_SECRET_ID" # Secret ID with github PAT
+data_for_github_pat_secret = "PAT" # Actual Github PAT
+trigger_source_repo = "https://github.com/beamplayground/deploy-workaround" # Repo used as a workaround
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:66]: Also request trigger source branch. It can be master or main

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 16]
```diff
@@ -31,18 +31,51 @@ Cloud Build triggers created by terraform scripts from this directory automate s
...
+beam/playground/terraform/infrastructure/cloudbuild-manual-setup/common.tfvars 
+```
+And put the following:
+```
+playground_deploy_sa = "DEPLOY_SA_NAME" # SA name used for Deploy trigger
+playground_update_sa = "UPDATE_SA_NAME" # SA name used for Update trigger
+playground_ci_sa = "CI_SA_NAME" # SA name used for CI trigger
+playground_cd_sa = "CD_SA_NAME" # SA name used for CD trigger
+project_id = "PROJECT_ID" # ID of the project used
+playground_environment_name = "environment" # Name of the environment. Used for prefixing (dev- stag- prod- etc.)
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:57]: Don't request env specific variables:
playground_environment_name
playground_dns_name
image_tag
playground_region
playground_zone
skip_appengine_deploy
state_bucket
terraform_source_repo
terraform_source_branch

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 17]
```diff
@@ -66,19 +99,16 @@ cd playground/terraform/infrastructure/cloudbuild-manual-setup/01.setup/
 
 # Run terraform commands
 terraform init -backend-config="bucket=$STATE_BUCKET"
-terraform apply -var="project_id=$(gcloud config get-value project)"
+terraform apply -var="project_id=$(gcloud config get-value project)" -var-file=../common.tfvars"
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:102]: "../common.tfvars" (" symbol)

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 18]
```diff
@@ -31,18 +31,51 @@ Cloud Build triggers created by terraform scripts from this directory automate s
...
+playground_zone = "us-central1-a" # GCP Zone to deploy in
+skip_appengine_deploy = false # Workaround for Appengine issue. Appengine can only be deployed once so subsequent runs need to set this to true
+webhook_trigger_secret_id = "SECRET_ID" # Secret ID for webhook
+gh_pat_secret_id = "PAT_SECRET_ID" # Secret ID with github PAT
+data_for_github_pat_secret = "PAT" # Actual Github PAT
+trigger_source_repo = "https://github.com/beamplayground/deploy-workaround" # Repo used as a workaround
+terraform_source_repo = "https://github.com/apache/beam" # Repo from which terraform code is fetched 
+terraform_source_branch = "master" # Branch from which terraform code is fetched
+state_bucket = "BUCKET_NAME" # State bucket to preseve environment state
+data_for_cicd_webhook_secret = "secret_sting"  # Secret used when creating the Github webhook
```
Comment (rshamunov) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:70]: request bucket names

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 19]
```diff
@@ -20,97 +20,131 @@
...
-- Required API services
-- Cloud Build service account
-- IAM roles for Cloud Build service account
+4. DNS name for your Playground deployment instance
 
-#### To execute the module:
-
-**Note:**  Please see [Cloud Build locations](https://cloud.google.com/build/docs/locations) for the list of all supported locations.
+5. OS with installed software listed below:
+- [Java](https://adoptopenjdk.net/)
```
Comment (olehborysevych) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:45]: @rshamunov  Why do we need java and go here?

File: playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/variables.tf [hunk 20]
```diff
@@ -16,93 +16,149 @@
...
-variable "playground_gke_name" {
-  description = "The Playground GKE Cluster name in Google Cloud Platform (GCP)"
+variable "cloudbuild_bucket_private" {
+  description = "The Google Cloud Platform GCS bucket name for Playground Cloudbuild Private logs"
 }
 
-variable "state_bucket" {
-  description = "The Google Cloud Platform (GCP) GCS bucket name for Beam Playground temp files and Terraform state"
+variable "cloudbuild_bucket_public" {
+  description = "The Google Cloud Platform GCS bucket name for Playground Cloudbuild Private logs"
```
Comment (olehborysevych) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/variables.tf:77]: should be "Public"

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md [hunk 21]
```diff
@@ -20,97 +20,125 @@
...
-```console
-# Set environment variable for state bucket
-export STATE_BUCKET="state-bucket"
+1. Generate a Terraform variable file called `beam/playground/terraform/infrastructure/cloudbuild-manual-setup/common.tfvars`. Place the values listed below into the file, adjusting them as needed:
+```
+playground_deploy_sa = "pg-cb-deploy"                                       # Service account for Initialize-Playground-environment trigger
+playground_update_sa = "pg-cb-update"                                       # Service account for Deploy-Update-Playground-environment trigger
+playground_ci_sa = "pg-cb-ci"                                               # SA name used for CI trigger
+playground_cd_sa = "pg-cb-cd"                                               # SA name used for CD trigger
+project_id = "<PROJECT_ID>"                                                   # GCP Project ID
```
Comment (damccorm) [inline playground/terraform/infrastructure/cloudbuild-manual-setup/README.md:58]:
```suggestion
project_id = "<PROJECT_ID>"                                                 # GCP Project ID
```

Indentation nit

File: playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/variables.tf (hunk 20 above)
Comment (damccorm) [reply playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/variables.tf:77]:
```suggestion
  description = "The Google Cloud Platform GCS bucket name for Playground Cloudbuild public logs"
```

+1

**Review by damccorm — COMMENTED** [review]
LGTM other than a few nits

File: playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/variables.tf (hunk 20 above)
Comment (rshamunov) [reply playground/terraform/infrastructure/cloudbuild-manual-setup/02.builders/variables.tf]: Fixes

File: playground/terraform/infrastructure/cloudbuild-manual-setup/README.md (hunk 21 above)
Comment (rshamunov) [reply playground/terraform/infrastructure/cloudbuild-manual-setup/README.md]: Fixed

**Review by damccorm — APPROVED** [review]
Thanks
