### PR TITLE
Fix retaining unsaved pipeline options (#22075)

### LINKED ISSUE #22075: [Playground] [Bug]: Pipeline Options pop-up retains changes even if unsaved
## Steps to Reproduce: ##

1. Open Playground: https://play.beam.apache.org
2. Open 'Pipeline Options' dropdown.
3. Enter any name and value for an option.
4. Click outside of the pop-up instead of saving.
5. Open the pop-up again.

**Expected results:** The fields are blank.

**Actual results:** The fields retain the same values.

The options with which the pipeline actually runs are only set if saved.

### Issue Priority

Priority: 3

### Issue Component

Component: beam-playground

### PR DESCRIPTION
**Pull request by alexeyinkin**
Remove `kDefaultOption` global variable that had been caching an option even if unsaved.
Fixes #22075 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_dropdown_body.dart [hunk 1]
```diff
@@ -29,19 +29,16 @@ import 'package:playground/modules/editor/parsers/run_options_parser.dart';
 const kOptionsTabIndex = 0;
 const kRawTabIndex = 1;
 
-final kDefaultOption = [PipelineOptionController()];
-
```
Comment (alexeyinkin) [inline playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_dropdown_body.dart:33]: This variable was the root cause of the issue.

File: playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_dropdown_body.dart [hunk 2]
```diff
@@ -29,19 +29,16 @@ import 'package:playground/modules/editor/parsers/run_options_parser.dart';
...
   final void Function() close;
 
-  const PipelineOptionsDropdownBody({
-    Key? key,
+  PipelineOptionsDropdownBody({
     required this.pipelineOptions,
     required this.setPipelineOptions,
     required this.close,
-  }) : super(key: key);
+  }) : super(key: ValueKey(pipelineOptions));
```
Comment (alexeyinkin) [inline playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_options_dropdown_body.dart:41]: So that the old state is dropped and options are re-parsed to new controllers if they change.

File: playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_option_controller.dart [hunk 3]
```diff
@@ -16,14 +16,19 @@
  * limitations under the License.
  */
 
-import 'package:flutter/cupertino.dart';
+import 'package:flutter/widgets.dart';
 
 class PipelineOptionController {
-  final TextEditingController name = TextEditingController();
-  final TextEditingController value = TextEditingController();
+  final TextEditingController nameController = TextEditingController();
```
Comment (damondouglas) [inline playground/frontend/lib/modules/editor/components/pipeline_options_dropdown/pipeline_option_controller.dart:22]: @alexeyinkin Maybe change to: `final nameController = TextEditingController();`

**Review by damondouglas — APPROVED** [review]
@pabloem LGTM
