### PR TITLE
[Playground] Resolve issue with SCIO examples failing on start due to a timeout

### LINKED ISSUE #24943: [Bug]: SCIO examples time out in RunCode endpoint
### What happened?

Runs of Scala examples time out during initialization due to `sbt` tool downloading Scala dependencies for more than 30 seconds

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by TSultanov**
SCIO examples timeout when it's a first run in the container. The reason is that `sbt` tool downloads Scala dependencies upon the first run, which happens synchronously and takes a significant amount of time.

Downloading the Scala dependencies during the container build time mitigates this problem as `sbt` will use already downloaded files instead of fetching them from a remote host.

Fixes issue with excessive memory usage, examples now can be run under 1GB of memory usage.

Also this PR resolves issue with execution environment not being properly removed after the example execution.

resolves #24943

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by olehborysevych** [comment]
Run RAT PreCommit

File: playground/backend/containers/scio/Dockerfile [hunk 1]
```diff
@@ -84,4 +83,18 @@ RUN chown -R appuser:appgroup /opt/playground/backend/executable_files/ \
...
+RUN /opt/playground/backend/new_scio_project.sh
+WORKDIR /tmp/sbt-initialize/scio
+RUN sbt "+compile"
+WORKDIR /
+RUN rm -r /tmp/sbt-initialize
+
+# Enable mitmproxy
+ENV HTTP_PROXY="http://127.0.0.1:8081"
+ENV HTTPS_PROXY="http://127.0.0.1:8081"
+ENV SBT_OPTS="-Xmx512M -XX:+UseG1GC -XX:+UseStringDeduplication"
```
Comment (damondouglas) [inline playground/backend/containers/scio/Dockerfile:98]: Can you explain again why we need mitmproxy?  I read the website briefly and it looks like a networking tool.  However, aren't we achieving our networking needs using kubernetes Service and other related kinds?  Can our images and the Dockerfiles that describe them serve just to ship the binary?

**Review by damondouglas — CHANGES_REQUESTED** [review]

File: playground/backend/containers/scio/Dockerfile (hunk 1 above)
Comment (TSultanov) [reply playground/backend/containers/scio/Dockerfile:98]: It's being used to filter out which Google Cloud Storage buckets are accessible by the examples.

However, after investigating a little bit it seems that this is not the best place to have it. We discussed this with @MakarkinSAkvelon and think that the best solution would be to have a single proxy node which would act as a reverse proxy for letting external connections to the runners and also as a single point though which runners would be able to only access the allowlisted hosts. 

This approach with a single proxy node will simplify origin policy for frontend and we will be able to get rid of [the need to generate](https://github.com/apache/beam/pull/25022) `config.g.dart` completely.

File: playground/backend/internal/utils/common_test.go [hunk 2]
```diff
@@ -28,6 +28,7 @@ const (
...
...ing word) -> !word.isEmpty()))\n        // Concept #3: Apply the Count transform to our PCollection of individual words. The Count\n        // transform returns a new PCollection of key/value pairs, where each key represents a\n        // unique word in the text. The associated value is the occurrence count for that word.\n        .apply(Count.perElement())\n        // Apply a MapElements transform that formats our PCollection of word counts into a\n        // printable string, suitable for writing to an output file.\n        .apply(\n            MapElements.into(TypeDescriptors.strings())\n                .via(\n                    (KV<String, Long> wordCount) ->\n                        wordCount.getKey() + \": \" + wordCount.getValue()))\n        // Concept #4: Apply a write transform, TextIO.Write, at the end of the pipeline.\n        // TextIO.Write writes the contents of a PCollection (in this case, our PCollection of\n        // formatted strings) to a series of text files.\n        //\n        // By default, it will write to a set of files with names like wordcounts-00001-of-00005\n        .apply(TextIO.write().to(\"wordcounts\"));\n\n    p.run().waitUntilFinish();\n  }\n}"
```
Comment (damondouglas) [inline playground/backend/internal/utils/common_test.go:34]: Could you use https://pkg.go.dev/embed to replace this large blob of text?

File: playground/infrastructure/grpc_client.py [hunk 3]
```diff
@@ -34,7 +34,7 @@ class GRPCClient:
 
     def __init__(self, wait_for_ready=True):
         use_webgrpc = os.getenv("BEAM_USE_WEBGRPC", False)
-        timeout = os.getenv("GRPC_TIMEOUT", 10)
+        timeout = int(os.getenv("GRPC_TIMEOUT", 10))
```
Comment (damondouglas) [inline playground/infrastructure/grpc_client.py:37]: I think we should not hard code const keys in the code but hoist them using for example
```go
const (
    grpcTimeoutKey = "GRPC_TIMEOUT"
)
```

**Review by damondouglas — CHANGES_REQUESTED** [review]

File: playground/backend/internal/utils/common_test.go (hunk 2 above)
Comment (TSultanov) [reply playground/backend/internal/utils/common_test.go]: It's possible to use directly from file

File: playground/infrastructure/grpc_client.py (hunk 3 above)
Comment (TSultanov) [reply playground/infrastructure/grpc_client.py:37]: Files a task to do this: https://github.com/apache/beam/issues/25202. This change seems to be outside of the scope of this PR.

**Review by damondouglas — CHANGES_REQUESTED** [review]
This PR at commit `d645408223` has the following test failures:

1. go test beam.apache.org/playground/backend/internal/code_processing

```
=== RUN   Test_getRunOrTestCmd/Get_run_cmd
    code_processing_test.go:632: getExecuteCmd() = runCommand arg1, want runCommand arg1
    --- FAIL: Test_getRunOrTestCmd/Get_run_cmd (0.00s)

=== RUN   Test_getRunOrTestCmd/Get_test_cmd
    code_processing_test.go:632: getExecuteCmd() = testCommand arg1 , want testCommand arg1 
    --- FAIL: Test_getRunOrTestCmd/Get_test_cmd (0.00s)
```

2. go test beam.apache.org/playground/backend/internal/setup_tools/life_cycle

```
=== RUN   TestSetup/Successfully_setup_life_cycle_with_Scio_sdk
    life_cycle_setuper_test.go:342: Setup() error = error during create necessary files for the Scio sdk: exit status 1, wantErr false
    --- FAIL: TestSetup/Successfully_setup_life_cycle_with_Scio_sdk (0.01s)
```

**Review by damondouglas — CHANGES_REQUESTED** [review]
FYI after running tests, I see that the following files are untracked.  Should they be added to `.gitignore`?

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	playground/backend/cmd/server/configs/
	playground/backend/cmd/server/logging.properties

```

**Comment by TSultanov** [comment]
@damondouglas, could you please provide some information about the environment in which you ran the tests? I was unable to reproduce the failures in backend/internal/code_processing. I tried running these tests on Linux (Ubuntu 22.40 amd64) and on macOS (arm64).

Regarding the internal/setup_tools/life_cycle test - it requires sbt tool to be present on the machine to be able to test SCIO lifecycle creation. If sbt is not installed the test will fail. This is expected.

**Comment by TSultanov** [comment]
@damondouglas added `sbt` to the list of dependencies

As for the another test, the problem lies in changes in Go 1.20, published a fix here: https://github.com/apache/beam/pull/25379

**Review by damondouglas — CHANGES_REQUESTED** [review]
I got the following failures at `f02d56a835`, running `go test ./...` in [playground/backend](https://github.com/akvelon/beam/tree/f02d56a835f1813901450bdaac9afd027b787b98/playground/backend) per the [instructions](https://github.com/akvelon/beam/tree/f02d56a835f1813901450bdaac9afd027b787b98/playground/backend#go-commands-to-runtest-application-locally).

# Environment

<details>

```
====== OS =======
amd64 Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

====== GO =============
go version go1.20 linux/amd64
==================

====== JAVA ======

openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode, sharing)

==================

==================

====== docker ======
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:54 2023
 OS/Arch:           linux/amd64
 Context:           default
==================

====== SBT ======
sbt version in this project: 1.8.2
sbt script version: 1.8.2
```
</details>

# Error

<details>

```
playground/backend$ go test ./...
go: downloading go.uber.org/goleak v1.2.0
go: downloading github.com/improbable-eng/grpc-web v0.15.0
go: downloading github.com/rs/cors v1.8.2
go: downloading cloud.google.com/go/datastore v1.9.0
go: downloading google.golang.org/grpc v1.51.0
go: downloading github.com/stretchr/testify v1.8.1
go: downloading cloud.google.com/go v0.104.0
go: downloading github.com/go-redis/redis/v8 v8.11.5
go: downloading github.com/go-redis/redismock/v8 v8.0.6
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/google/go-cmp v0.5.9
go: downloading github.com/confluentinc/confluent-kafka-go v1.9.2
go: downloading github.com/linkedin/goavro v2.1.0+incompatible
go: downloading github.com/spf13/viper v1.14.0
go: downloading cloud.google.com/go/logging v1.5.0
go: downloading github.com/procyon-projects/chrono v1.1.2
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/cenkalti/backoff/v4 v4.1.1
go: downloading github.com/desertbit/timer v0.0.0-20180107155436-c41aec40b27f
go: downloading golang.org/x/net v0.0.0-20221014081412-f15817d10f9b
go: downloading nhooyr.io/websocket v1.8.6
go: downloading github.com/googleapis/gax-go/v2 v2.6.0
go: downloading google.golang.org/api v0.102.0
go: downloading google.golang.org/genproto v0.0.0-20221024183307-1bc688fe9f3e
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/dgryski/go-rendezvous v0.0.0-20200823014737-9f7001d12a5f
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading github.com/spf13/afero v1.9.2
go: downloading github.com/spf13/jwalterweatherman v1.1.0
go: downloading golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2
go: downloading golang.org/x/oauth2 v0.0.0-20221014153046-6fdb5e3db783
go: downloading github.com/klauspost/compress v1.11.7
go: downloading cloud.google.com/go/compute/metadata v0.2.1
go: downloading cloud.google.com/go/compute v1.12.1
go: downloading golang.org/x/sys v0.0.0-20220908164124-27713097b956
go: downloading golang.org/x/text v0.4.0
go: downloading github.com/subosito/gotenv v1.4.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/magiconair/properties v1.8.6
go: downloading github.com/pelletier/go-toml/v2 v2.0.5
go: downloading github.com/pelletier/go-toml v1.9.5
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.2.0
?       beam.apache.org/playground/backend/cmd  [no test files]
# beam.apache.org/playground/backend/internal/emulators
internal/emulators/kafka.go:45:17: undefined: kafka.MockCluster
internal/emulators/kafka.go:51:24: undefined: kafka.NewMockCluster
internal/emulators/kafka.go:90:18: undefined: kafka.Producer
internal/emulators/kafka.go:94:18: undefined: kafka.NewProducer
internal/emulators/kafka.go:94:37: undefined: kafka.ConfigMap
internal/emulators/kafka.go:129:40: undefined: kafka.Message
internal/emulators/kafka.go:130:26: undefined: kafka.TopicPartition
?       beam.apache.org/playground/backend/internal/api/v1      [no test files]
?       beam.apache.org/playground/backend/internal/cache       [no test files]
FAIL    beam.apache.org/playground/backend/cmd/server [build failed]
ok      beam.apache.org/playground/backend/internal/cache/local 1.013s
?       beam.apache.org/playground/backend/internal/constants   [no test files]
?       beam.apache.org/playground/backend/internal/db  [no test files]
ok      beam.apache.org/playground/backend/internal/cache/redis 0.079s
FAIL    beam.apache.org/playground/backend/internal/code_processing [build failed]
?       beam.apache.org/playground/backend/internal/db/schema   [no test files]
?       beam.apache.org/playground/backend/internal/tasks       [no test files]
?       beam.apache.org/playground/backend/internal/tests/test_cleaner  [no test files]
?       beam.apache.org/playground/backend/internal/tests/test_data     [no test files]
panic: test timed out after 10m0s
running tests:
        TestCacheComponent_GetSdkCatalogFromCacheOrDatastore (10m0s)
        TestCacheComponent_GetSdkCatalogFromCacheOrDatastore/Getting_sdk_catalog_from_datastore_in_the_usual_case (10m0s)

goroutine 59 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:2241 +0x3b9
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000417520, {0xc55c12?, 0x52bb05?}, 0xc7f2b8)
        /usr/local/go/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x1208760?)
        /usr/local/go/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc000417520, 0xc0003dfc20)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0004705a0?, {0x11f7c00, 0x3, 0x3}, {0x40e3a7?, 0x18?, 0x1207c00?})
        /usr/local/go/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0004705a0)
        /usr/local/go/src/testing/testing.go:1906 +0x63a
beam.apache.org/playground/backend/internal/components.TestMain(0xc00005c730?)
        /beam-24943-scio-run-timeout/playground/backend/internal/components/cache_component_test.go:44 +0x28
main.main()
        _testmain.go:53 +0x1d3

goroutine 18 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00020cf00)
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x96

goroutine 19 [select]:
beam.apache.org/playground/backend/internal/cache/local.(*Cache).startGC(0xc00046f9d0, {0xd393c0, 0xc000415b00})
        /beam-24943-scio-run-timeout/playground/backend/internal/cache/local/local_cache.go:170 +0x8a
created by beam.apache.org/playground/backend/internal/cache/local.New
        /beam-24943-scio-run-timeout/playground/backend/internal/cache/local/local_cache.go:57 +0x13a

goroutine 20 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000476540)
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/balancer_conn_wrappers.go:115 +0x73
created by google.golang.org/grpc.newCCBalancerWrapper
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/balancer_conn_wrappers.go:76 +0x22a

goroutine 22 [chan receive]:
testing.(*T).Run(0xc0004176c0, {0xc55bde?, 0x1063008?}, 0xc000500360)
        /usr/local/go/src/testing/testing.go:1630 +0x405
beam.apache.org/playground/backend/internal/components.TestCacheComponent_GetSdkCatalogFromCacheOrDatastore(0x0?)
        /beam-24943-scio-run-timeout/playground/backend/internal/components/cache_component_test.go:92 +0x167
testing.tRunner(0xc0004176c0, 0xc7f2b8)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea

goroutine 24 [select]:
github.com/googleapis/gax-go/v2.Sleep({0xd393c0, 0xc0005006f0}, 0xc0001cf901?)
        /go/pkg/mod/github.com/googleapis/gax-go/v2@v2.6.0/invoke.go:57 +0x7b
cloud.google.com/go/internal.retry({0xd393c0, 0xc0005006f0}, {0x5f5e100, 0x6fc23ac00, 0x4000000000000000, 0x6fc23ac00}, 0xc00010dc00, 0xc7fac0)
        /go/pkg/mod/cloud.google.com/go@v0.104.0/internal/retry.go:49 +0x159
cloud.google.com/go/internal.Retry(...)
        /go/pkg/mod/cloud.google.com/go@v0.104.0/internal/retry.go:33
cloud.google.com/go/datastore.(*datastoreClient).invoke(0xd393c0?, {0xd393c0, 0xc0005006c0}, 0xc00010dcb0)
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/client.go:122 +0xdf
cloud.google.com/go/datastore.(*datastoreClient).Commit(0xc0005001e0, {0xd393c0?, 0xc0005003f0?}, 0xc00020dd80, {0x0, 0x0, 0x0})
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/client.go:91 +0x17b
cloud.google.com/go/datastore.(*Client).PutMulti(0xc000476680, {0xd393c0?, 0xc000415b00?}, {0xc0001cf980?, 0x4, 0x4}, {0xaebe20, 0xc0001a35a8})
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/datastore.go:541 +0x212
beam.apache.org/playground/backend/internal/db/datastore.(*Datastore).PutSDKs(0xc0001a3488, {0xd393c0, 0xc000415b00}, {0xc0001cf880?, 0x4, 0x4})
        /beam-24943-scio-run-timeout/playground/backend/internal/db/datastore/datastore_db.go:161 +0x279
beam.apache.org/playground/backend/internal/components.TestCacheComponent_GetSdkCatalogFromCacheOrDatastore.func2()
        /beam-24943-scio-run-timeout/playground/backend/internal/components/cache_component_test.go:86 +0x3a
beam.apache.org/playground/backend/internal/components.TestCacheComponent_GetSdkCatalogFromCacheOrDatastore.func3(0xc000417d40)
        /beam-24943-scio-run-timeout/playground/backend/internal/components/cache_component_test.go:93 +0x4e
testing.tRunner(0xc000417d40, 0xc000500360)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea

goroutine 46 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc0002218c0)
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/clientconn.go:1164 +0x3b8
google.golang.org/grpc.(*addrConn).connect(0xc0002218c0)
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/clientconn.go:803 +0x105
created by google.golang.org/grpc.(*acBalancerWrapper).Connect
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/balancer_conn_wrappers.go:413 +0xbc
FAIL    beam.apache.org/playground/backend/internal/components  600.018s
2023/02/15 22:06:35 [DEBUG]: putting snippet "MOCK_ID", persistent key ""...
panic: test timed out after 10m0s
running tests:
        TestDatastore_PutSnippet (10m0s)
        TestDatastore_PutSnippet/PutSnippet()_in_the_usual_case (10m0s)

goroutine 12 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:2241 +0x3b9
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0003f4680, {0xc65845?, 0x52bb05?}, 0xca7c48)
        /usr/local/go/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x124a280?)
        /usr/local/go/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc0003f4680, 0xc0002dfc20)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0003e8820?, {0x123c3c0, 0x10, 0x10}, {0xc0000114e8?, 0xc0002dfd30?, 0x1249720?})
        /usr/local/go/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0003e8820)
        /usr/local/go/src/testing/testing.go:1906 +0x63a
beam.apache.org/playground/backend/internal/db/datastore.TestMain(0xc00005c730?)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/datastore/datastore_db_test.go:41 +0x28
main.main()
        _testmain.go:79 +0x1d3

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000d4e80)
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x96

goroutine 7 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0003f2580)
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/balancer_conn_wrappers.go:115 +0x73
created by google.golang.org/grpc.newCCBalancerWrapper
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/balancer_conn_wrappers.go:76 +0x22a

goroutine 51 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc00024b8c0)
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/clientconn.go:1164 +0x3b8
google.golang.org/grpc.(*addrConn).connect(0xc00024b8c0)
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/clientconn.go:803 +0x105
created by google.golang.org/grpc.(*acBalancerWrapper).Connect
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/balancer_conn_wrappers.go:413 +0xbc

goroutine 9 [chan receive]:
testing.(*T).Run(0xc0003f4820, {0xc6add8?, 0x0?}, 0xc00034fff0)
        /usr/local/go/src/testing/testing.go:1630 +0x405
beam.apache.org/playground/backend/internal/db/datastore.TestDatastore_PutSnippet(0xc0003f4820)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/datastore/datastore_db_test.go:118 +0x113
testing.tRunner(0xc0003f4820, 0xca7c48)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea

goroutine 10 [select]:
github.com/googleapis/gax-go/v2.Sleep({0xd65a40, 0xc0003fe540}, 0xc000049901?)
        /go/pkg/mod/github.com/googleapis/gax-go/v2@v2.6.0/invoke.go:57 +0x7b
cloud.google.com/go/internal.retry({0xd65a40, 0xc0003fe540}, {0x5f5e100, 0x6fc23ac00, 0x4000000000000000, 0x6fc23ac00}, 0xc00010db68, 0xca84b0)
        /go/pkg/mod/cloud.google.com/go@v0.104.0/internal/retry.go:49 +0x159
cloud.google.com/go/internal.Retry(...)
        /go/pkg/mod/cloud.google.com/go@v0.104.0/internal/retry.go:33
cloud.google.com/go/datastore.(*datastoreClient).invoke(0xd65a40?, {0xd65a40, 0xc0003fe510}, 0xc000098c18)
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/client.go:122 +0xdf
cloud.google.com/go/datastore.(*datastoreClient).BeginTransaction(0xc0003fe300, {0xd65a40?, 0xc0003fe4b0?}, 0xc000089680, {0x0, 0x0, 0x0})
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/client.go:80 +0x17b
cloud.google.com/go/datastore.(*Client).newTransaction(0xc0003f26c0, {0xd65a40, 0xc0003fe4b0}, 0xc0003fe4e0)
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/transaction.go:157 +0x423
cloud.google.com/go/datastore.(*Client).RunInTransaction(0xd65a40?, {0xd65a40?, 0xc000373cb0?}, 0xc00010ded0, {0x0, 0x0, 0x0})
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/transaction.go:198 +0x168
beam.apache.org/playground/backend/internal/db/datastore.(*Datastore).PutSnippet(0xc000011500, {0xd65a40, 0xc000373cb0}, {0xc57c53, 0x7}, 0xc0003fe420)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/datastore/datastore_db.go:86 +0x27e
beam.apache.org/playground/backend/internal/db/datastore.TestDatastore_PutSnippet.func2(0xc0003f4b60)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/datastore/datastore_db_test.go:119 +0x49
testing.tRunner(0xc0003f4b60, 0xc00034fff0)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL    beam.apache.org/playground/backend/internal/db/datastore        600.020s
ok      beam.apache.org/playground/backend/internal/db/dto      0.009s
ok      beam.apache.org/playground/backend/internal/db/entity   0.009s
ok      beam.apache.org/playground/backend/internal/db/mapper   0.008s
panic: test timed out after 10m0s
running tests:
        TestInitialStructure_InitiateData (10m0s)
        TestInitialStructure_InitiateData/Test_migration_with_version_0.0.1_in_the_usual_case (10m0s)

goroutine 69 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:2241 +0x3b9
created by time.goFunc
        /usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00039f040, {0xc593ad?, 0x52bb05?}, 0xc923e8)
        /usr/local/go/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x1225aa0?)
        /usr/local/go/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc00039f040, 0xc00035fc20)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc0003fa460?, {0x1210440, 0x2, 0x2}, {0xc00035fd38?, 0xa04f09?, 0x1224f40?})
        /usr/local/go/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc0003fa460)
        /usr/local/go/src/testing/testing.go:1906 +0x63a
beam.apache.org/playground/backend/internal/db/schema/migration.TestMain(0xc00005c730?)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/schema/migration/migrations_test.go:37 +0x28
main.main()
        _testmain.go:51 +0x1d3

goroutine 34 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00018cf00)
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x96

goroutine 35 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000402540)
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/balancer_conn_wrappers.go:115 +0x73
created by google.golang.org/grpc.newCCBalancerWrapper
        /go/pkg/mod/google.golang.org/grpc@v1.51.0/balancer_conn_wrappers.go:76 +0x22a

goroutine 37 [chan receive]:
testing.(*T).Run(0xc00039f1e0, {0xc68628?, 0x107f8c8?}, 0xc0004143f0)
        /usr/local/go/src/testing/testing.go:1630 +0x405
beam.apache.org/playground/backend/internal/db/schema/migration.TestInitialStructure_InitiateData(0x0?)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/schema/migration/migrations_test.go:87 +0x11d
testing.tRunner(0xc00039f1e0, 0xc923e8)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea

goroutine 38 [select]:
github.com/googleapis/gax-go/v2.Sleep({0xd4f8e0, 0xc00040a600}, 0xc00014fa01?)
        /go/pkg/mod/github.com/googleapis/gax-go/v2@v2.6.0/invoke.go:57 +0x7b
cloud.google.com/go/internal.retry({0xd4f8e0, 0xc00040a600}, {0x5f5e100, 0x6fc23ac00, 0x4000000000000000, 0x6fc23ac00}, 0xc000095b20, 0xc92bf8)
        /go/pkg/mod/cloud.google.com/go@v0.104.0/internal/retry.go:49 +0x159
cloud.google.com/go/internal.Retry(...)
        /go/pkg/mod/cloud.google.com/go@v0.104.0/internal/retry.go:33
cloud.google.com/go/datastore.(*datastoreClient).invoke(0xd4f8e0?, {0xd4f8e0, 0xc00040a5d0}, 0xc000095bd0)
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/client.go:122 +0xdf
cloud.google.com/go/datastore.(*datastoreClient).Commit(0xc00040a150, {0xd4f8e0?, 0xc00040a4b0?}, 0xc00018de80, {0x0, 0x0, 0x0})
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/client.go:91 +0x17b
cloud.google.com/go/datastore.(*Client).PutMulti(0xc000402680, {0xd4f8e0?, 0xc00039db00?}, {0xc000095d58?, 0x1, 0x1}, {0xb06220, 0xc000121578})
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/datastore.go:541 +0x212
cloud.google.com/go/datastore.(*Client).Put(0xd4f8e0?, {0xd4f8e0, 0xc00039db00}, 0x10?, {0xaedb60?, 0xc000414430})
        /go/pkg/mod/cloud.google.com/go/datastore@v1.9.0/datastore.go:511 +0xbe
beam.apache.org/playground/backend/internal/db/datastore.(*Datastore).PutSchemaVersion(0xc000121488, {0xd4f8e0, 0xc00039db00}, {0xc41676?, 0xf?}, 0xc000414430)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/datastore/datastore_db.go:144 +0xfb
beam.apache.org/playground/backend/internal/db/schema/migration.(*InitialStructure).InitiateData(0x59a?, 0xc00040a450)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/schema/migration/migration_v001.go:31 +0x83
beam.apache.org/playground/backend/internal/db/schema/migration.TestInitialStructure_InitiateData.func1(0xc00039f520)
        /beam-24943-scio-run-timeout/playground/backend/internal/db/schema/migration/migrations_test.go:89 +0x34
testing.tRunner(0xc00039f520, 0xc0004143f0)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL    beam.apache.org/playground/backend/internal/db/schema/migration 600.017s
ok      beam.apache.org/playground/backend/internal/environment 0.011s
ok      beam.apache.org/playground/backend/internal/errors      0.002s
FAIL    beam.apache.org/playground/backend/internal/executors [build failed]
FAIL    beam.apache.org/playground/backend/internal/fs_tool [build failed]
ok      beam.apache.org/playground/backend/internal/logger      1.174s
FAIL    beam.apache.org/playground/backend/internal/preparers [build failed]
FAIL    beam.apache.org/playground/backend/internal/setup_tools/builder [build failed]
FAIL    beam.apache.org/playground/backend/internal/setup_tools/life_cycle [build failed]
ok      beam.apache.org/playground/backend/internal/streaming   0.007s
ok      beam.apache.org/playground/backend/internal/tests/test_utils    0.002s
ok      beam.apache.org/playground/backend/internal/utils       0.012s
FAIL    beam.apache.org/playground/backend/internal/validators [build failed]
FAIL
```
</details>

**Comment by TSultanov** [comment]
@damondouglas I looked into this errors, seems that there should be additional measures taken to make tests runnable in Cloud Shell environment.

I [updated](https://github.com/apache/beam/blob/c8900dfa2a04c76ca538535bdb2e355d001ccc64/playground/backend/README.md#prerequisite) Readme to clarify that tests need local Datastore emulator to run and they will not run with real datastore (although this should be easily fixable - but I'm not if this change worth the effort).

**Comment by damondouglas** [comment]
> I looked into this errors, seems that there should be additional measures taken to make tests runnable in Cloud Shell environment.

FYI this was a compute engine instance but nonetheless a clean environment.

> I [updated](https://github.com/apache/beam/blob/c8900dfa2a04c76ca538535bdb2e355d001ccc64/playground/backend/README.md#prerequisite) Readme to clarify that tests need local Datastore emulator to run and they will not run with real datastore (although this should be easily fixable - but I'm not if this change worth the effort).

Instead of the emulator, have you tried to:
1. Implement a mock [google.golang.org/genproto/googleapis/datastore/v1](https://pkg.go.dev/google.golang.org/genproto/googleapis/datastore/v1#DatastoreServer) with only the endpoints needed for the tests?  Endpoints not needed could simply return fmt.Errorf("not implemted")
2.  In your test you can add https://pkg.go.dev/google.golang.org/api/option#WithEndpoint to the https://pkg.go.dev/google.golang.org/api/option#WithEndpoint after service begins
3. When test(s) complete, shut down the service

If you still want to use the emulator, I recommend the tests that need it to actually activate and shut down the emulator but personally when I test Google api dependent code in the context of Go, I implement the grpc server.  This doesn't replace integration tests but serves as a quicker way to detect errors in code.

**Comment by TSultanov** [comment]
@damondouglas
I agree with your points that unit tests should preferably use mock of the server and integration tests should be able to start and stop their dependencies automatically, but such change certainly goes beyond the scope of this PR. We can estimate efforts for the change to the tests in this task (#25588).

**Comment by Abacn** [comment]
R: @damondouglas

File: playground/backend/internal/utils/preparers_utils_test.go [hunk 4]
```diff
@@ -27,6 +27,61 @@ import (
...
+	}
+	sourceJavaFilePath := filepath.Join(testDataDir, javaFileName)
+	javaFilePath := filepath.Join(sourceDir, javaFileName)
+	err = CopyFile(sourceJavaFilePath, javaFilePath)
+	if err != nil {
+		return err
+	}
+	if err != nil {
+		return err
+	}
```
Comment (damccorm) [inline playground/backend/internal/utils/preparers_utils_test.go:69]:
```suggestion
	if err != nil {
		return err
	}
```

**Comment by damccorm** [comment]
Mostly LGTM other than a few small comments

**Review by damccorm — APPROVED** [review]

**Comment by damccorm** [comment]
I'm waiting on CI checks to pass before merging, probably will check back tomorrow
