### PR TITLE
Issue26977 changing sdk bug

### LINKED ISSUE #26977: [Bug]: changing sdk in ToB doesn't changes the example
### What happened?

changing sdk in ToB doesn't changes the example

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Malarg**
fixed bug when changing sdk does not changes the example
resolves #26977 
------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by Malarg** [comment]
@alexeyinkin R

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 1]
```diff
@@ -49,8 +51,15 @@ void main() {
...
-      // await _checkResizeUnitContent(wt);
+      await _checkRunCodeWorks(wt);
+      await _checkResizeUnitContent(wt);
+
+      if (ExamplesLoader.failedToLoadExamples.isNotEmpty) {
+        final tokens = ExamplesLoader.failedToLoadExamples.join(', ');
+        print(
+          'There are some havent loaded examples with tokens: $tokens',
+        );
+      }
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:62]: That's from another task, do not mix it. Especially so since I have changed this part there. Please isolate the bug fix.

File: learning/tour-of-beam/frontend/lib/pages/tour/state.dart [hunk 2]
```diff
@@ -137,22 +135,27 @@ class TourNotifier extends ChangeNotifier with PageStateMixin<void> {
...
-      _setUnitContent(content);
-      await _unitProgressCache.loadUnitProgress(currentSdk);
-      _trySetSnippetType(SnippetType.saved);
-      await _loadSnippetByType();
+      await _updateUnitState(currentNode);
     }
     notifyListeners();
   }
 
+  Future<void> _updateUnitState(NodeModel? currentNode) async {
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/lib/pages/tour/state.dart:143]: I don't see what it does from the name.

**Review by alexeyinkin — CHANGES_REQUESTED** [review]

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart (hunk 1 above)
Comment (Malarg) [reply learning/tour-of-beam/frontend/integration_test/tour_page_test.dart]: Sure, removed

**Review by nausharipov — CHANGES_REQUESTED** [review]

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 3]
```diff
@@ -125,6 +132,30 @@ Future<void> _checkUnitContentLoadsProperly(
...
 
+Future<void> _checkSdkChangesProperly(WidgetTester wt, UnitModel node) async {
+  final defaultSdk = _getTourNotifier(wt).playgroundController.sdk;
+  final sdkCache = GetIt.instance.get<SdkCache>();
+  String? previousId;
+  for (final sdk in sdkCache.getSdks()) {
+    await _setSdk(sdk.title, wt);
+    final actualId =
+        _getTourNotifier(wt).playgroundController.selectedExample?.path;
+    expect(actualId, isNot(previousId));
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:143]: This is too weak. Test the SDK of the newly loaded unit or example.

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 4]
```diff
@@ -100,6 +102,11 @@ Future<void> _checkNode(UnitModel node, WidgetTester wt) async {
   );
 
   await _checkUnitContentLoadsProperly(node, wt);
+
+  final hasSnippet = _getTourNotifier(wt).isUnitContainsSnippet;
+  if (!_isSdkChangingChecked && hasSnippet) {
+    await _checkSdkChangesProperly(wt, node);
+  }
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:109]: People would not expect `_checkNode` to go into such extra work depending on the global state. And if it breaks, it will be confusing, because it has nothing to do with 'check node'.

Move this to a separate function on the same level as other globals.

**Review by alexeyinkin — CHANGES_REQUESTED** [review]

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart (hunk 3 above)
Comment (Malarg) [reply learning/tour-of-beam/frontend/integration_test/tour_page_test.dart]: added

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 5]
```diff
@@ -259,3 +262,104 @@ Set<String> _getExpandedIds(WidgetTester wt) {
...
+  final contentTrees = await _loadAllContentTrees(wt);
+  final sdkUnits = List<List<UnitModel>>.empty(growable: true);
+  for (final tree in contentTrees) {
+    sdkUnits.add(tree.getUnits().toList());
+  }
+
+  final commonUnitTitles = sdkUnits.first;
+  for (final units in sdkUnits.skip(1)) {
+    commonUnitTitles.removeWhere((u) => !units.contains(u));
+  }
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:317]: Explain.

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 6]
```diff
@@ -259,3 +262,104 @@ Set<String> _getExpandedIds(WidgetTester wt) {
...
+  await wt.pumpAndSettle();
+}
+
+Future<UnitModel?> _findUnitWithSnippetsInAllSdks(WidgetTester wt) async {
+  final unitContentCache = GetIt.instance.get<UnitContentCache>();
+  final commonUnits = await _getCommonUnitsInAllSdks(wt);
+  final sdks = GetIt.instance.get<SdkCache>().getSdks();
+
+  UnitModel? unitWithSnippets;
+  for (final unit in commonUnits) {
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:289]: Simplify with `continue` and `return`.

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 7]
```diff
@@ -259,3 +262,104 @@ Set<String> _getExpandedIds(WidgetTester wt) {
...
+}
+
+Future<void> _checkSnippetChangesOnSdkChanging(WidgetTester wt) async {
+  final defaultSdk = _getTourNotifier(wt).playgroundController.sdk;
+  final sdkCache = GetIt.instance.get<SdkCache>();
+
+  String? previousPath;
+  Sdk? previousSdk;
+  for (final sdk in sdkCache.getSdks()) {
+    if (sdk.title == defaultSdk?.title) {
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:340]: Compare as objects or by `.id`.

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 8]
```diff
@@ -259,3 +262,104 @@ Set<String> _getExpandedIds(WidgetTester wt) {
...
+    }
+
+    await _setSdk(sdk.title, wt);
+
+    final selectedExample =
+        _getTourNotifier(wt).playgroundController.selectedExample;
+    final actualPath = selectedExample?.path;
+    final actualSdk = selectedExample?.sdk;
+    expect(actualPath, isNot(previousPath));
+    expect(actualSdk, isNot(previousSdk));
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:351]: `expect(selectedExample.sdk, sdk)` or `.id`

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 9]
```diff
@@ -259,3 +262,104 @@ Set<String> _getExpandedIds(WidgetTester wt) {
...
+  }
+
+  await _setSdk(defaultSdk!.title, wt);
+}
+
+Future<void> _setSdk(String title, WidgetTester wt) async {
+  await wt.tapAndSettle(find.sdkDropdown());
+  await wt.tapAndSettle(
+    find.dropdownMenuItemWithText(title).first,
+    warnIfMissed: false,
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:363]: Explain. Link to the Flutter bug.

**Review by alexeyinkin — CHANGES_REQUESTED** [review]

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart (hunk 9 above)
Comment (Malarg) [reply learning/tour-of-beam/frontend/integration_test/tour_page_test.dart]: Unnecessary, removed

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart (hunk 8 above)
Comment (Malarg) [reply learning/tour-of-beam/frontend/integration_test/tour_page_test.dart]: done

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart (hunk 6 above)
Comment (Malarg) [reply learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:287]: simplified even more :)

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 10]
```diff
@@ -259,3 +262,99 @@ Set<String> _getExpandedIds(WidgetTester wt) {
...
+
+Future<List<ContentTreeModel>> _loadAllContentTrees(WidgetTester wt) async {
+  final sdkCache = GetIt.instance.get<SdkCache>();
+  final contentTreeCache = GetIt.instance.get<ContentTreeCache>();
+  final sdks = sdkCache.getSdks();
+  final nullableTrees = await Future.wait(
+    sdks.map((sdk) async => contentTreeCache.getContentTree(sdk)),
+  );
+
+  return nullableTrees.where((t) => t != null).map((t) => t!).toList();
```
[the remark this answers is not in the document]
Comment (Malarg) [reply learning/tour-of-beam/frontend/integration_test/tour_page_test.dart]: done

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 11]
```diff
@@ -259,3 +264,103 @@ Set<String> _getExpandedIds(WidgetTester wt) {
...
+    }
+  }
+  return true;
+}
+
+Future<List<UnitModel>> _getCommonUnitsInAllSdks(WidgetTester wt) async {
+  final contentTrees = await _loadAllContentTrees(wt);
+  final sdkUnits = List<List<UnitModel>>.empty(growable: true);
+  for (final tree in contentTrees) {
+    sdkUnits.add(tree.getUnits().toList());
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:311]: `toSet()` maybe?

File: learning/tour-of-beam/frontend/integration_test/tour_page_test.dart [hunk 12]
```diff
@@ -259,3 +264,103 @@ Set<String> _getExpandedIds(WidgetTester wt) {
...
+    }
+
+    await _setSdk(sdk.title, wt);
+
+    final selectedExample =
+        _getTourNotifier(wt).playgroundController.selectedExample;
+    final appNotifier = GetIt.instance.get<AppNotifier>();
+    final actualPath = selectedExample?.path;
+    final actualSdk = selectedExample?.sdk;
+    expect(actualPath, isNot(previousPath));
```
Comment (alexeyinkin) [inline learning/tour-of-beam/frontend/integration_test/tour_page_test.dart:353]: Redundant.

**Review by alexeyinkin — APPROVED** [review]
LGTM (internal review).

**Comment by alexeyinkin** [comment]
R: @pabloem

**Comment by pabloem** [comment]
LGTM!
