### PR TITLE
[Playground] [Backend] added SDK validation to save a code snippet

### LINKED ISSUE #22789: [Playground][Task]: SDK validation for sharing any code
### What needs to happen?

To avoid side effects related to a bad request from a client, namely, a wrong SDK, we have to validate the SDK from a payload

### Issue Priority

Priority: 2

### Issue Component

Component: beam-playground

### PR DESCRIPTION
**Pull request by vchunikhin**
fixes #22789 

@olehborysevych 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: playground/backend/cmd/server/controller_test.go [hunk 1]
```diff
@@ -813,7 +815,7 @@ func TestPlaygroundController_SaveSnippet(t *testing.T) {
 				},
 			},
 			wantErr: false,
-			wantId:  "xHce_LOg7Zm",
+			wantId:  "l7OFah5mLHU",
```
Comment (olehborysevych) [inline playground/backend/cmd/server/controller_test.go:818]: @vchunikhin what changed here so that id is changed?

File: playground/backend/internal/db/mapper/datastore_mapper_test.go [hunk 2]
```diff
@@ -122,7 +123,7 @@ func TestEntityMapper_ToFileEntity(t *testing.T) {
 
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
-			result := testable.ToFileEntity(tt.args.info, tt.args.file)
+			result, _ := testable.ToFileEntity(tt.args.info, tt.args.file)
```
Comment (olehborysevych) [inline playground/backend/internal/db/mapper/datastore_mapper_test.go:126]: Could you please add tests for cases where ToFileEntity returns an error?

File: playground/backend/internal/utils/file_utils.go [hunk 3]
```diff
@@ -35,53 +37,105 @@ const (
...
+		return sdk == pb.Sdk_SDK_JAVA
+	case goExt:
+		return sdk == pb.Sdk_SDK_GO
+	case pythonExt:
+		return sdk == pb.Sdk_SDK_PYTHON
+	case scioExt:
+		return sdk == pb.Sdk_SDK_SCIO
 	default:
-		return name
+		return true
```
Comment (olehborysevych) [inline playground/backend/internal/utils/file_utils.go:94]: Why do we have "true" here?

File: playground/backend/internal/utils/file_utils.go [hunk 4]
```diff
@@ -35,53 +37,105 @@ const (
...
+	if strings.Contains(content, javaMainMethod) {
+		return javaExt
+	}
+	if strings.Contains(content, goMainMethod) {
+		return goExt
+	}
+	if strings.Contains(content, pythonMainMethod) {
+		return pythonExt
+	}
+	if strings.Contains(content, goMainMethod) {
```
Comment (olehborysevych) [inline playground/backend/internal/utils/file_utils.go:117]: goMainMethod looks incorrect here

**Comment by vchunikhin** [comment]
R: @pabloem

File: playground/backend/cmd/server/controller_test.go [hunk 5]
```diff
@@ -863,7 +863,7 @@ func TestPlaygroundController_SaveSnippet(t *testing.T) {
 				t.Errorf("PlaygroundController_SaveSnippet() error = %v, wantErr %v", err, tt.wantErr)
 			}
 			if err == nil {
-				if len(got.Id) != 11 || got.Id != tt.wantId {
+				if len(got.Id) != 11 {
```
Comment (pabloem) [inline playground/backend/cmd/server/controller_test.go:866]: why is the length always 11?

**Comment by pabloem** [comment]
lgtm otherwise. Thanks!

File: playground/backend/cmd/server/controller_test.go (hunk 5 above)
Comment (vchunikhin) [reply playground/backend/cmd/server/controller_test.go:866]: It's the length of the identifier that is used to store snippets in the Cloud Datastore. It's appropriate length to save storage size in the Cloud Datastore and provide good randomnicity. This parameter stores in the playground/backend/properties.yaml file
