### PR TITLE
Use Periodic Impulse for BQ SchemaUpdate tests

### LINKED ISSUE #27911: [Failing Test]: StorageApiSinkSchemaUpdateIT fails on Dataflow V1 PostCommit
### What happened?

https://ci-beam.apache.org/view/PostCommit/job/beam_PostCommit_Java_DataflowV1/3394/testReport/

It added 24 tests, all fail.

Do we need all these tests run on Dataflow PostCommit anyway or selected one?

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [X] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixes #27911
Follow-up for #27740

Switch to using PeriodicImpulse instead of TestStream, which is only available on Direct and Flink runners.

Had to make an addition to PeriodicImpulse to make it more streaming friendly. The default behavior is that PeriodicImpulse emits all instants from start until Instant.now(). After that, it starts firing at the specified interval. The changes here add an option to make it fire at the specified interval for all elements. This was needed to test schema update because in this test case we care very much about maintaining a consistent interval period between stream appends. 

Other changes include manually enabling streaming engine. The storage API sink uses GroupIntoBatches, which requires streaming engine. This streaming mode is automatically enabled in Runner V2 but not V1. 

Also followed @Abacn's suggestion of only running the important tests on TestDataflowRunner so that we don't eat too many resources unnecessarily.

### CODE REVIEW

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_DataflowV2

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_DataflowV2

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_DataflowV2

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_DataflowV2

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_DataflowV2

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by ahmedabu98** [comment]
R: @Abacn 
R: @reuvenlax

**Comment by ahmedabu98** [comment]
Failing tests are irrelevant:
`org.apache.beam.sdk.io.gcp.pubsublite.ReadWriteIT.testReadWrite`
`org.apache.beam.sdk.io.gcp.spanner.changestreams.it.SpannerChangeStreamOrderedWithinKeyGloballyIT.testOrderedWithinKey`

**Review by johnjcasey — APPROVED** [review]

**Comment by Abacn** [comment]
Just note that there is a GenerateSequence transform can emit integers with given interval, from pipeline startup (do not flush backlogs at the beginning)

File: sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PeriodicSequence.java [hunk 1]
```diff
@@ -223,11 +233,17 @@ public ProcessContinuation processElement(
...
+        }
       }
 
       ProcessContinuation continuation = ProcessContinuation.stop();
       if (claimSuccess) {
-        Duration offset = new Duration(Instant.now(), Instant.ofEpochMilli(nextOutput));
+        Duration offset =
+            srcElement.catchUpToNow
+                ? new Duration(Instant.now(), Instant.ofEpochMilli(nextOutput))
+                : new Duration(interval);
```
Comment (Abacn) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PeriodicSequence.java:246]: If catchUpToNow=False, then the emitted interval can be minutes old than now, is that true?

I think the real problem for current PeriodicImpulse is that it does not support a start time to be the time pipeline starts being processed. It needs to specify a constant start time, but we cannot control when pipeline will actually start processing

Is it possible to keep the emitted timestamp nearly now? Also the naming could be more formal (`catch up` sounds informal)

Comment (ahmedabu98) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/transforms/PeriodicSequence.java:246]: >If catchUpToNow=False, then the emitted interval can be minutes old than now, is that true? 

That's right, this would allow having a start time of `new Instant(0)` and still respecting the fire interval.

> Is it possible to keep the emitted timestamp nearly now?

I think if a user needs this, they can just not set the flag. The current behavior does just that.

**Comment by ahmedabu98** [comment]
> Just note that there is a GenerateSequence transform can emit integers with given interval, from pipeline startup 

That's true, but GenerateSequence as a streaming doesn't have a stop. We would need to rely on manually canceling the pipeline (or draining for Dataflow).

**Review by Abacn — APPROVED** [review]

**Comment by Abacn** [comment]
Experiment result shows fastjson in general is much more relax in non-standard syntax. We may need to add other configs, see below.

| config | fastjson default | jackson default | jackson relaxed |
|---|---|---|---|
| normal | o | o | o |
| ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER | o | x | o |
| ALLOW_COMMENTS | o | x | o |
| ALLOW_MISSING_VALUES | o | x | o |
| ALLOW_NON_NUMERIC_NUMBERS | o | x | o |
| ALLOW_NUMERIC_LEADING_ZEROS | o | x | o |
| ALLOW_SINGLE_QUOTES | o | x | o |
| ALLOW_TRAILING_COMMA | o | x | o |
| ALLOW_UNQUOTED_CONTROL_CHARS | o | x | o |
| ALLOW_UNQUOTED_FIELD_NAMES | o | x | o |
| ALLOW_YAML_COMMENTS | x | x | o |

**Comment by Abacn** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by Abacn** [comment]
Run PostCommit_Java_DataflowV2

**Comment by Abacn** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run Java_GCP_IO_Direct PreCommit

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by Abacn** [comment]
interestingly, org.apache.beam.sdk.io.gcp.bigquery.StorageApiSinkSchemaUpdateIT.testExactlyOnceWithIgnoreUnknownValues[1] is a flaky test

**Comment by ahmedabu98** [comment]
Looking into it now.. seems like test is flaky when using ignoreUnknownValues. The previous run failed on `testAtLeastOnceWithIgnoreUnknownValues[1]`

**Comment by ahmedabu98** [comment]
Ahh this is happening because ignoreUnkownValues are not included in the "wait longer" tests:
`boolean waitLonger = changeTableSchema && useAutoSchemaUpdate;`

In the flakes, we don't use an input schema and the destination table schema is updated really quickly before any streams are created. From my understanding when the connector fetches the destination schema (because we don't use an input schema), it fetches the updated one and so the extra field is actually expected and not ignored.

Trying locally, ignoreUnknownValue tests that wait longer seem to not flake anymore

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_Dataflow

**Comment by ahmedabu98** [comment]
Run PostCommit_Java_DataflowV2

**Comment by ahmedabu98** [comment]
Run Java_IOs_Direct PreCommit
