### PR TITLE
[Bug]: avro_dict_to_beam_row negative integer incorrectly converts to uint

### LINKED ISSUE #34438: [Bug]: avro_dict_to_beam_row negative integer incorrectly converts to uint
### What happened?

Found in https://github.com/apache/beam/pull/34354#issuecomment-2754793208 . The tests has been accidentally succeeding.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by DKER2**
fixes #34438

Revert https://github.com/apache/beam/pull/30770 as we already has permanent fix https://github.com/apache/beam/pull/34354. https://github.com/apache/beam/pull/30770 is a [workaround](https://github.com/apache/beam/pull/34542/files#diff-1718dfb556afab4509fcebea73250e0955c49c6b5194227046dbb0a5a9bdbad6L198-L206) to avoid negative value in https://github.com/apache/beam/blob/master/sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java#L103-L109 

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [x] Update `CHANGES.md` with noteworthy changes.
 - [x] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java [hunk 1]
```diff
@@ -102,7 +102,7 @@ public static void encode(long v, OutputStream stream) throws IOException {
   /** Decodes an integer value from the given stream. */
   public static int decodeInt(InputStream stream) throws IOException {
     long r = decodeLong(stream);
-    if (r < 0 || r >= 1L << 32) {
```
Comment (Abacn) [inline sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java:105]: This is a valid check. when encoding int, there is a bit operation:

https://github.com/apache/beam/blob/c59ba993122414af645734f4e3518cdda25a7da4/sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java#L35

where negative int will become a positive long

please revert java side changes

Comment (Abacn) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java:105]: cc: @kennknowles opinion here?

File: sdks/python/apache_beam/io/avroio.py [hunk 2]
```diff
@@ -646,9 +646,9 @@ def avro_atomic_value_to_beam_atomic_value(avro_type: str, value):
   if value is None:
     return value
   elif avro_type == "int":
-    return ctypes.c_uint32(value).value
```
Comment (Abacn) [inline sdks/python/apache_beam/io/avroio.py:649]: We may simply revert the workaround in #30770 that is remove this helper function, and see if `test_avro_schema_to_beam_schema_with_nullable_atomic_fields` still pass

File: sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java (hunk 1 above)
Comment (kennknowles) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java:105]: OK my opinions are more like:

1. Use more parentheses when mixing `<` and `>=` and `<<` 😅 .
2. If the bytes on the stream are a valid `VarInt` in the right range then they should decode correctly, otherwise they shouldn't.
3. I think re-using the logic of `decodeLong` makes things less clear. We have this problem but also the error message is less specific (always says "varint"). It would be better to duplicate the logic so `decodeInt` and `decodeLong` are independent.
4. This loop has so few iterations that it could be unrolled and it would be perfectly clear and potentially faster.

Perhaps these are not the answers to the question you really are asking, but that is my opinion of how to improve the code here.

Comment (Abacn) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java:105]: Thanks, from `#2` let's keep VarInt.java as is for this moment (do not loose check)

Comment (DKER2) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java:105]: Sorry, but I do not get it clear. Can I clarify that we should revert back this change?

File: sdks/python/apache_beam/io/avroio.py (hunk 2 above)
Comment (Abacn) [reply sdks/python/apache_beam/io/avroio.py:649]: We no longer need avro_atomic_value_to_beam_atomic_value (and beam_atomic_value_to_avro_atomic_value) after #30770. I tested in a branch: https://github.com/Abacn/beam/commit/979940b1c7b2cf083c654199dc56cae1efa2670d

where I find `test_avro_schema_to_beam_schema_with_nullable_atomic_fields` can pass, and no longer experience int overflow in intermediate results:

```
_______________________________________________________________________ TestFastAvro.test_avro_schema_to_beam_schema_with_nullable_atomic_fields ________________________________________________________________________
--------- Captured stdout call ----------
Row(name='Thomas', favorite_number=1, favorite_color='blue')
Row(name='Henry', favorite_number=3, favorite_color='green')
Row(name='Toby', favorite_number=7, favorite_color='brown')
Row(name='Gordon', favorite_number=4, favorite_color='blue')
Row(name='Emily', favorite_number=-1, favorite_color='Red')
Row(name='Percy', favorite_number=6, favorite_color='Green')
Row(name='Bruce', favorite_number=None, favorite_color=None)
BeamSchema_(name='Thomas', favorite_number=1, favorite_color='blue')
BeamSchema_(name='Henry', favorite_number=3, favorite_color='green')
BeamSchema_(name='Toby', favorite_number=7, favorite_color='brown')
BeamSchema_(name='Gordon', favorite_number=4, favorite_color='blue')
BeamSchema_(name='Emily', favorite_number=-1, favorite_color='Red')
BeamSchema_(name='Percy', favorite_number=6, favorite_color='Green')
BeamSchema_(name='Bruce', favorite_number=None, favorite_color=None)
======= 1 passed, 1 warning in 11.70s =======
```

To test, build sql expansion service first, then run `pytest -rP -v apache_beam/io/avroio_test.py::TestFastAvro::test_avro_schema_to_beam_schema_with_nullable_atomic_fields`

File: sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java (hunk 1 above)
Comment (Abacn) [reply sdks/java/core/src/main/java/org/apache/beam/sdk/util/VarInt.java:105]: replied below. The workaround is no longer needed to convert -1

File: sdks/python/apache_beam/io/avroio.py (hunk 2 above)
Comment (DKER2) [reply sdks/python/apache_beam/io/avroio.py:649]: Thank you @Abacn for detailed instruction. I have made changes according. 

Not related, but interestingly, when I test local, it still call decodeInt function

**Review by Abacn — APPROVED** [review]

**Comment by Abacn** [comment]
Thank you!
