### PR TITLE
fix jdbc transform validation

### LINKED ISSUE #35122: [Bug]: YAML JDBC sources broken in Beam 2.65
### What happened?

The Beam YAML JDBC sources(`ReadFromPostgres`, `ReadFromSqlServer`, `ReadFromOracle`, etc.) appear to be broken in Beam 2.65. For example, running this pipeline:

```
pipeline:
  type: chain
  transforms:
    - type: ReadFromPostgres
      config:
        url: "jdbc:sqlserver://my-host:1433/database"
        query: "SELECT * FROM table"
    - type: LogForTesting
```

produces the following error:

```
ValueError: Error applying transform "ReadFromPostgres" at line 4: java.lang.IllegalArgumentException: If JDBC type is not specified, then Driver Class Name and Driver Jars must be specified.
        at org.apache.beam.sdk.io.jdbc.JdbcReadSchemaTransformProvider$JdbcReadSchemaTransformConfiguration.validate(JdbcReadSchemaTransformProvider.java:369)
        at org.apache.beam.sdk.io.jdbc.JdbcReadSchemaTransformProvider$JdbcReadSchemaTransformConfiguration.validate(JdbcReadSchemaTransformProvider.java:355)
        at org.apache.beam.sdk.io.jdbc.JdbcReadSchemaTransformProvider$JdbcReadSchemaTransform.expand(JdbcReadSchemaTransformProvider.java:217)
        at org.apache.beam.sdk.io.jdbc.JdbcReadSchemaTransformProvider$JdbcReadSchemaTransform.expand(JdbcReadSchemaTransformProvider.java:171)
        at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:559)
        at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:507)
        at org.apache.beam.sdk.expansion.service.TransformProvider.apply(TransformProvider.java:121)
        at org.apache.beam.sdk.expansion.service.ExpansionService.expand(ExpansionService.java:657)
        at org.apache.beam.sdk.expansion.service.ExpansionService.expand(ExpansionService.java:758)
        at org.apache.beam.model.expansion.v1.ExpansionServiceGrpc$MethodHandlers.invoke(ExpansionServiceGrpc.java:306)
        at org.apache.beam.vendor.grpc.v1p69p0.io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at org.apache.beam.vendor.grpc.v1p69p0.io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:356)
        at org.apache.beam.vendor.grpc.v1p69p0.io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
        at org.apache.beam.vendor.grpc.v1p69p0.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at org.apache.beam.vendor.grpc.v1p69p0.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

Based on the release and source history, [this PR](https://github.com/apache/beam/pull/34514) seems like a possible cause. The issue does not reproduce in Beam 2.64.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [x] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by stankiewicz**
fixes #35122

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

File: sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProviderTest.java [hunk 1]
```diff
@@ -47,6 +51,25 @@
 @RunWith(JUnit4.class)
 public class JdbcReadSchemaTransformProviderTest {
 
+  @AutoService(SchemaTransformProvider.class)
+  public static class ReadFromDerbySchemaTransformProvider extends JdbcReadSchemaTransformProvider {
+
+    @Override
+    public @UnknownKeyFor @NonNull @Initialized String identifier() {
```
Comment (Abacn) [inline sdks/java/io/jdbc/src/test/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProviderTest.java]: Let's remove the IDE auto populated `@UnknownKeyFor @NonNull @Initialized`. existing occurrence in this file wasn't needed either.

**Comment by Abacn** [comment]
There is another validation here:

https://github.com/apache/beam/blob/ca7fc1794017625a02fd659cadb5ff05477727bd/sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java#L167

Shall we simply remove the offending validate call?

**Comment by stankiewicz** [comment]
> There is another validation here:
> 
> https://github.com/apache/beam/blob/ca7fc1794017625a02fd659cadb5ff05477727bd/sdks/java/io/jdbc/src/main/java/org/apache/beam/sdk/io/jdbc/JdbcReadSchemaTransformProvider.java#L167
> 
> Shall we simply remove the offending validate call?

i think this one is good.

**Review by Abacn — APPROVED** [review]
