### PR TITLE
Remove flakes of BeamFnClientLoggingTest

### LINKED ISSUE #27292: [Failing Test]: Java Unit Test GitHub Action failing on MacOS and Windows
### What happened?

Both fail at the same test:

```
> Task :sdks:java:harness:test


org.apache.beam.fn.harness.logging.BeamFnLoggingClientTest > testClosableWhenBlockingForOnReady FAILED
    java.lang.AssertionError at BeamFnLoggingClientTest.java:446
```

Unfortunately there is no further logging available for GA.

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 1 (unhealthy code / failing or flaky postcommit so we cannot be sure the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by scwhittle**
fixes #27292 
Handles that the client may batch logs into fewer requests than would trigger onReady evaluation
Fix phaser usage error which didn't sychronize threads as intended
Only counts attempted fake logs to avoid other logging from causing failures.
Improves test speed by fixing fake server to terminate stream.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by scwhittle** [comment]
R: @Abacn

**Comment by scwhittle** [comment]
One successful, not sure how to rerun manually so closing and reopening to trigger.

File: sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java [hunk 1]
```diff
@@ -249,7 +251,7 @@ public StreamObserver<BeamFnApi.LogEntry.List> logging(
                       StreamObserver<BeamFnApi.LogControl> outboundObserver) {
                     // Block before returning an error on the stream so that we can observe the
                     // loggers before they are reset.
-                    streamBlocker.awaitAdvance(1);
```
Comment (scwhittle) [inline sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java:252]: this should have been awaitAdvance(0) to have effect. Replaced with CompletableFuture which is simpler for this single block and then trigger.

File: sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java [hunk 2]
```diff
@@ -430,21 +449,31 @@ public boolean isReady() {
...
       int sleepTime = 0;
-      while (values.size() < numEntries) {
+      while (testEntriesObserved.get() < numEntries) {
         ++sleepTime;
         Thread.sleep(1);
       }
       // Attempt to enter the blocking state by pushing back on the stream, publishing records and
       // then giving them time for it to block.
       elementsAllowed.set(false);
-      for (int i = 0; i < numEntries; ++i) {
```
Comment (scwhittle) [inline sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java:440]: this wouldn't always trigger blocking since onReady is called every 100 rpc messages, and each message coudl be a batch of up to 1OK logs.

File: sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java [hunk 3]
```diff
@@ -356,15 +358,28 @@ public StreamObserver<BeamFnApi.LogEntry.List> logging(
...
+                      int observed = testEntriesObserved.addAndGet(1);
+                      if (observed % 100 == 0) {
+                        originalOutStream.println("Saw test record " + observed);
+                      }
+                    } else {
+                      originalOutStream.println("Logging: " + entry);
+                    }
+                  }
+                })
+            .withOnCompleted(() -> outboundServerObserver.get().onCompleted())
```
Comment (scwhittle) [inline sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java:382]: missing this led to 10 second wait for soft flush in client, slowing down test

**Comment by scwhittle** [comment]
Another success, trying once more

File: sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java (hunk 3 above)
Comment (Abacn) [reply sdks/java/harness/src/test/java/org/apache/beam/fn/harness/logging/BeamFnLoggingClientTest.java:382]: great, observed the teat took 20 s long, now it's 2 s

**Review by Abacn — APPROVED** [review]
Thanks for the fix!

Just one minor question

- I see some OringinalOutStream.println call which is equivalent to System.out.println. Are print to stdout intended or leftover of debugging?

**Comment by scwhittle** [comment]
Removed the logging, was helpful to see what was going on on non-local run. But easy to add back if needded.

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow PreCommit

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit"

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java17 PreCommit

**Comment by Abacn** [comment]
Run Java_Examples_Dataflow_Java11 PreCommit
