### PR TITLE
Fix JavaPreCommit on Java11

### LINKED ISSUE #32911: [Failing Test]: Prism runner execution test failing on Java11
### What happened?

Apparently on Java11 console output has fancy colors, which fails assert:

image

```
expected to contain:
    INFO Serving JobManagement endpoint=localhost:5555
but was:
    ?[2m?[37m[2024-10-23T18:04:52.324084899Z]?[0m ?[42m?[30m INFO ?[0m ?[32mServing JobManagement?[0m
    ?[34m*?[0m ?[35mendpoint?[0m: ?[4m?[34mlocalhost:5555?[0m?[0m
    
    ?[2m?[37m[2024-10-23T18:04:52.328261009Z]?[0m ?[42m?[30m INFO ?[0m ?[32mServing WebUI?[0m
    ?[34m*?[0m ?[35mendpoint?[0m: ?[4m?[34mhttp://localhost:8074?[0m?[0m
    
    
	at app//org.apache.beam.runners.prism.PrismExecutorTest.executeWithCustomArgumentsThenStop(PrismExecutorTest.java:89)
```

### Issue Failure

Failure: Test is continually failing

### Issue Priority

Priority: 2 (backlog / disabled test but we think the product is healthy)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Abacn**
FIx #32911, mitigate #32208

* Fix PrismRunner test assert

* Disable affected Samza runner test in Java9+

**Please** add a meaningful description for your change here

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Abacn** [comment]
R: @lostluck @damccorm

File: runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismExecutorTest.java [hunk 1]
```diff
@@ -102,4 +102,12 @@ private void sleep(long millis) {
     } catch (InterruptedException ignored) {
     }
   }
+
+  private static String normalizeConsoleOutput(String output) {
```
Comment (lostluck) [inline runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismExecutorTest.java:106]: This could be alternately fixed by setting

'--log_kind=json' 
or 
'--log_kind=text'

as a flag to the process here:
 https://github.com/apache/beam/blob/master/runners/prism/java/src/main/java/org/apache/beam/runners/prism/PrismRunner.java#L110

**Review by lostluck — APPROVED** [review]

File: runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismExecutorTest.java (hunk 1 above)
Comment (Abacn) [reply runners/prism/java/src/test/java/org/apache/beam/runners/prism/PrismExecutorTest.java]: Thanks, changed to use '--log_kind=text'
