### PR TITLE
[Java]Fix IllegalStateException in WindmillSink by Clearing Stream Before Encoding (#31914)

### LINKED ISSUE #31914: [Bug]: java.lang.IllegalStateException: Expected output stream to be empty
### What happened?
Apache Beam 2.57.0, Java 21

My pipeline on GCP time to time log an exception, for last 24 hours it was 1_000 times:

` java.lang.IllegalStateException: Expected output stream to be empty but had <ByteString@6ea215ba size=33 contents="\002\030bison casino\002\000\b0.00\b0.00\f1.0000">
at org.apache.beam.vendor.guava.v32_1_2_jre.com.google.common.base.Preconditions.checkState ( org/apache.beam.vendor.guava.v32_1_2_jre.com.google.common.base/Preconditions.java:601 )
at org.apache.beam.runners.dataflow.worker.WindmillSink$WindmillStreamWriter.encode ( org/apache.beam.runners.dataflow.worker/WindmillSink.java:142 )
at org.apache.beam.runners.dataflow.worker.WindmillSink$WindmillStreamWriter.add ( org/apache.beam.runners.dataflow.worker/WindmillSink.java:159 )
at org.apache.beam.runners.dataflow.worker.WindmillSink$WindmillStreamWriter.add ( org/apache.beam.runners.dataflow.worker/WindmillSink.java:130 )
at org.apache.beam.runners.dataflow.worker.SizeReportingSinkWrapper$SizeLimitingWriterWrapper.add ( org/apache.beam.runners.dataflow.worker/SizeReportingSinkWrapper.java:63 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.WriteOperation.process ( org/apache.beam.runners.dataflow.worker.util.common.worker/WriteOperation.java:89 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process ( org/apache.beam.runners.dataflow.worker.util.common.worker/OutputReceiver.java:54 )
at org.apache.beam.runners.dataflow.worker.AssignWindowsParDoFnFactory$AssignWindowsParDoFn.processElement ( org/apache.beam.runners.dataflow.worker/AssignWindowsParDoFnFactory.java:115 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process ( org/apache.beam.runners.dataflow.worker.util.common.worker/ParDoOperation.java:44 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process ( org/apache.beam.runners.dataflow.worker.util.common.worker/OutputReceiver.java:54 )
at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output ( org/apache.beam.runners.dataflow.worker/SimpleParDoFn.java:285 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:276 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900 ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:86 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:432 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:412 )
at com.prizeengine.jobs.ParseMessageFromCasinoEngine.parseStringToLogElement ( com/prizeengine.jobs/ParseMessageFromCasinoEngine.java:123 )
at com.prizeengine.jobs.ParseMessageFromCasinoEngine$DoFnInvoker.invokeProcessElement
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:212 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:189 )
at org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement ( org/apache.beam.runners.dataflow.worker/SimpleParDoFn.java:340 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process ( org/apache.beam.runners.dataflow.worker.util.common.worker/ParDoOperation.java:44 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process ( org/apache.beam.runners.dataflow.worker.util.common.worker/OutputReceiver.java:54 )
at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output ( org/apache.beam.runners.dataflow.worker/SimpleParDoFn.java:285 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:276 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$900 ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:86 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:432 )
at org.apache.beam.sdk.transforms.DoFnOutputReceivers$WindowedContextOutputReceiver.output ( org/apache.beam.sdk.transforms/DoFnOutputReceivers.java:89 )
at org.apache.beam.sdk.transforms.MapElements$2.processElement ( org/apache.beam.sdk.transforms/MapElements.java:151 )
at org.apache.beam.sdk.transforms.MapElements$2$DoFnInvoker.invokeProcessElement
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.invokeProcessElement ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:212 )
at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.processElement ( org/apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core/SimpleDoFnRunner.java:189 )
at org.apache.beam.runners.dataflow.worker.SimpleParDoFn.processElement ( org/apache.beam.runners.dataflow.worker/SimpleParDoFn.java:340 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.ParDoOperation.process ( org/apache.beam.runners.dataflow.worker.util.common.worker/ParDoOperation.java:44 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process ( org/apache.beam.runners.dataflow.worker.util.common.worker/OutputReceiver.java:54 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.runReadLoop ( org/apache.beam.runners.dataflow.worker.util.common.worker/ReadOperation.java:218 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.ReadOperation.start ( org/apache.beam.runners.dataflow.worker.util.common.worker/ReadOperation.java:169 )
at org.apache.beam.runners.dataflow.worker.util.common.worker.MapTaskExecutor.execute ( org/apache.beam.runners.dataflow.worker.util.common.worker/MapTaskExecutor.java:83 )
at org.apache.beam.runners.dataflow.worker.streaming.ComputationWorkExecutor.executeWork ( org/apache.beam.runners.dataflow.worker.streaming/ComputationWorkExecutor.java:78 )
at org.apache.beam.runners.dataflow.worker.windmill.work.processing.StreamingWorkScheduler.executeWork ( org/apache.beam.runners.dataflow.worker.windmill.work.processing/StreamingWorkScheduler.java:377 )
at org.apache.beam.runners.dataflow.worker.windmill.work.processing.StreamingWorkScheduler.processWork ( org/apache.beam.runners.dataflow.worker.windmill.work.processing/StreamingWorkScheduler.java:252 )
at org.apache.beam.runners.dataflow.worker.windmill.work.processing.StreamingWorkScheduler.lambda$scheduleWork$2 ( org/apache.beam.runners.dataflow.worker.windmill.work.processing/StreamingWorkScheduler.java:211 )
at org.apache.beam.runners.dataflow.worker.streaming.ExecutableWork.run ( org/apache.beam.runners.dataflow.worker.streaming/ExecutableWork.java:38 )
at org.apache.beam.runners.dataflow.worker.util.BoundedQueueExecutor.lambda$executeMonitorHeld$0 ( org/apache.beam.runners.dataflow.worker.util/BoundedQueueExecutor.java:232 )
at java.util.concurrent.ThreadPoolExecutor.runWorker ( java/util.concurrent/ThreadPoolExecutor.java:1144 )
at java.util.concurrent.ThreadPoolExecutor$Worker.run ( java/util.concurrent/ThreadPoolExecutor.java:642 )
at java.lang.Thread.run ( java/lang/Thread.java:1583 ) `

The code is rather simple, a java class annotated with defaultCoder(Avro.class) put to output:

`res = KV.of(sessionId, baseTransaction);
c.output(res);`

I tried to bring same guava version as in error log, but it doesn't help.

Locally with the test suite, this DoFn works without any issues with same input.

### Issue Priority

Priority: 3 (minor)

### Issue Components

- [ ] Component: Python SDK
- [X] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [X] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by Suvrat1629**
**Please** add a meaningful description for your change here

------------------------
Fixes #31914 by adding stream.toByteStringAndReset() before each encode call in WindmillSink$WindmillStreamWriter.add to clear residual data, preventing IllegalStateException.

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by Suvrat1629** [comment]
assign set of reviewers

**Comment by tvalentyn** [comment]
R: @scwhittle

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java [hunk 1]
```diff
@@ -155,10 +155,12 @@ private <EncodeT> ByteString encode(Coder<EncodeT> coder, EncodeT object) throws
     public long add(WindowedValue<T> data) throws IOException {
       ByteString key, value;
       ByteString id = ByteString.EMPTY;
+      stream.toByteStringAndReset();
```
Comment (scwhittle) [inline runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java]: It seems the issue is likely that an exception is being thrown from line 149 `coder.encode` which causes line 150 not to reset the stream.  Then if at a higher level that exception is caught and ignored and further encoding is attempted the checkState will be encountered.

Since this is executed often it seems it would be better to fix by changing `encode` to wrap the existing logic with try/catch and resetting the stream before propagating an exception thrown by the coder, instead of the additional resets here.

**Review by scwhittle — CHANGES_REQUESTED** [review]
Thanks!

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java (hunk 1 above)
Comment (Suvrat1629) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java]: @scwhittle Thanks for the feedback.
I have updated the fix to wrap `coder.encode` in a try-catch in encode, resetting stream on exception and I have reverted add method back to its original state. Please take a look.

Thank you

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java [hunk 2]
```diff
@@ -146,8 +146,15 @@ private <EncodeT> ByteString encode(Coder<EncodeT> coder, EncodeT object) throws
           stream.size() == 0,
           "Expected output stream to be empty but had %s",
           stream.toByteString());
-      coder.encode(object, stream, Coder.Context.OUTER);
-      return stream.toByteStringAndReset();
+      ByteString result;
+      try {
+        coder.encode(object, stream, Coder.Context.OUTER);
+        result = stream.toByteStringAndReset();
```
Comment (scwhittle) [inline runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java]: nit: I think you can just 
`return stream.toByteStringAndReset();`
and remove the result variable

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java [hunk 3]
```diff
@@ -146,8 +146,15 @@ private <EncodeT> ByteString encode(Coder<EncodeT> coder, EncodeT object) throws
...
+      } catch (IOException e) {
```
Comment (scwhittle) [inline runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java]: How about catching Exception e? in case there is a RuntimeException the coder throws

**Review by scwhittle — CHANGES_REQUESTED** [review]

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java (hunk 2 above)
Comment (Suvrat1629) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java]: Done!

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java (hunk 3 above)
Comment (Suvrat1629) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillSink.java]: Done!

**Comment by Suvrat1629** [comment]
@scwhittle 
Ok sure thank you :)
