### PR TITLE
[Playground] Make fields "categories" and "context_line" optional in examples tags

### LINKED ISSUE #26256: [Task]: Improve Playground examples tags handling
### What needs to happen?

Make fields categories and context_line optional in examples tag
Resolve bug with incorrectly calculated context line after tag is removed from an example
Resolve bug with an incorrectly reported context line for an example in catalog

### Issue Priority

Priority: 3 (nice-to-have improvement)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by TSultanov**
- Make fields categories and context_line optional in examples tag
- Resolve bug with incorrectly calculated context line after tag is removed from an example
- Resolve bug with an incorrectly reported context line for an example in catalog

resolves #26256

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

File: playground/backend/internal/db/mapper/precompiled_object_mapper_test.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ func TestPrecompiledObjectMapper_ToObjectInfo(t *testing.T) {
 		Categories:      []string{"MOCK_CAT_1", "MOCK_CAT_2", "MOCK_CAT_3"},
 		PipelineOptions: "MOCK_OPTIONS",
```
Comment (alexeyinkin) [inline playground/backend/internal/db/mapper/precompiled_object_mapper_test.go:41]: This will also help because the current value fails to be parsed and so the example is not runnable.
```suggestion
		PipelineOptions: "--name1 value1 --name2 value2",
```

Comment (TSultanov) [reply playground/backend/internal/db/mapper/precompiled_object_mapper_test.go:41]: This is internal data used only for test, the mock data used for local deployment is loaded form different place. I'm not if such change will be within the scope of this PR

**Review by alexeyinkin — APPROVED** [review]
LGTM (internal review).

**Review by rshamunov — APPROVED** [review]
LGTM

**Review by damccorm — APPROVED** [review]
