### PR TITLE
[Playground] Fix Test_getRunOrTestCmd on Go 1.20

### LINKED ISSUE #25380: [Bug]: Test_getRunOrTestCmd fails on Go 1.20
### What happened?

`Test_getRunOrTestCmd` in `code_processing_test.go` is failing when running with Go 1.20:

```
=== RUN   Test_getRunOrTestCmd/Get_run_cmd
    code_processing_test.go:632: getExecuteCmd() = runCommand arg1, want runCommand arg1
    --- FAIL: Test_getRunOrTestCmd/Get_run_cmd (0.00s)

=== RUN   Test_getRunOrTestCmd/Get_test_cmd
    code_processing_test.go:632: getExecuteCmd() = testCommand arg1 , want testCommand arg1 
    --- FAIL: Test_getRunOrTestCmd/Get_test_cmd (0.00s)
```

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [X] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by TSultanov**
`os.exec.Cmd` struct was changed in Go 1.20, a new field `Cancel func() error` [had been added](https://cs.opensource.google/go/go/+/refs/tags/go1.20:src/os/exec/exec.go;drc=ea4631cc0cf301c824bd665a7980c13289ab5c9d;l=259) to it.

The `Test_getRunOrTestCmd` test relies on comparing two instances of `exec.Cmd` using `reflect.DeepEqual()`. Deep equality of structs is performed by doing deep equality checks on all of their members. Deep equality of `Func` values is [defined](https://cs.opensource.google/go/go/+/refs/tags/go1.20:src/reflect/deepequal.go;drc=ee0e40aaef3dc5c6fb8612dd80622e02fc4b574f;l=153) as `false` for all non-`nil` values. Because of this the test is failing on Go 1.20, as even two equivalent instances of `exec.Cmd` struct are no longer deeply equal due to the new `Cancel` field of type `func()`, because, as defined above, two non-`nil` functions are always not deeply equal.

This PR replaces the deep comparison with string comparison of the generated command line, as it's the intention of the test.

resolves #25380

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/get-started-contributing/#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Review by olehborysevych — APPROVED** [review]

**Comment by olehborysevych** [comment]
LGTM

File: playground/backend/internal/code_processing/code_processing_test.go [hunk 1]
```diff
@@ -628,8 +628,8 @@ func Test_getRunOrTestCmd(t *testing.T) {
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
-			if got := getExecuteCmd(tt.args.isUnitTest, tt.args.executor, tt.args.ctxWithTimeout); !reflect.DeepEqual(got, tt.want) {
-				t.Errorf("getExecuteCmd() = %v, want %v", got, tt.want)
+			if got := getExecuteCmd(tt.args.isUnitTest, tt.args.executor, tt.args.ctxWithTimeout); got.String() != tt.want.String() {
```
Comment (damondouglas) [inline playground/backend/internal/code_processing/code_processing_test.go:631]: Could you try this? https://github.com/google/go-cmp
The problem with comparing strings is that the test becomes difficult to identify the exact reason for why it failed without drilling down further.

**Review by damondouglas — CHANGES_REQUESTED** [review]

**Review by damondouglas — APPROVED** [review]
@pabloem LGTM

**Comment by pabloem** [comment]
lgtm thanks
