### PR TITLE
[BigQueryIO] fetch updated schema for newly created Storage API stream writers

### LINKED ISSUE #33238: [Bug]: Newly created Storage API write streams do not recognize the previously updated table schema
### What happened?

#33231 added a test, showing the combination of these two feature do not work together.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [ ] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam YAML
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Infrastructure
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by ahmedabu98**
Fixes #33238

This problem happens whenever a StreamWriter is created after the table's schema is updated. The new StreamWriter [ignores the previously updated schema](https://github.com/googleapis/java-bigquerystorage/blob/main/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java#L576-L591) and ends up using the base schema, dropping the new columns. 
Such a case can happen when a pipeline decides to increase its parallelism (e.g. autosharding of threads or autoscaling of workers) **after** a schema update happens. The increased parallelism creates new stream writers that continue using the base schema, ignoring the updated schema. 

This PR fixes this by fetching the stream's schema whenever we create a new append client. Existing tests are modified to cover this case, and new tests are added for schema update with dynamic destinations.

### CODE REVIEW

**Comment by ahmedabu98** [comment]
R: @Abacn 
R: @reuvenlax

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java [hunk 1]
```diff
@@ -1419,7 +1421,11 @@ public WriteStream createWriteStream(String tableUrn, WriteStream.Type type)
 
     @Override
     public @Nullable WriteStream getWriteStream(String writeStream) {
-      return newWriteClient.getWriteStream(writeStream);
+      return newWriteClient.getWriteStream(
```
Comment (reuvenlax) [inline sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java:1424]: Let's add a boolean parameter to the method, so we only return schema if requested

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java [hunk 2]
```diff
@@ -531,6 +532,30 @@ public void process(
                       element.getKey().getKey(), dynamicDestinations, datasetService);
               tableSchema = converter.getTableSchema();
               descriptor = converter.getDescriptor(false);
+
+              if (autoUpdateSchema) {
```
Comment (reuvenlax) [inline sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:536]: I'm not sure this is the ideal place to put this. getAppendClientInfo is called whenever the static cache is populated, meaning that on any worker restart, range move, etc. we'll be forced to call this API again. However we have persistent state in this DoFn, so we know if it's a "new" key or not. Can we use that to gate calling this method instead?

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java (hunk 1 above)
Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java:1424]: FYI in our code base we always perform this call for the sole purpose of fetching the schema

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java (hunk 2 above)
Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:536]: We should always perform this check before creating a new StreamWriter , regardless of the reason for its creation. The only exception is if we already have an updated schema stored in state (see first `if` block above). If I'm following correctly, this method (`getAppendClientInfo`) will always [create a new stream writer](https://github.com/apache/beam/blob/d17f77a015d28b3008e80e647cf5e230310333c7/sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java#L535-L554).

Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:536]: Also note that the updated schema is ignored when the **StreamWriter object's** creation time is later than the updated schema's. 
i.e. it doesn't matter when the WriteStream itself was created

Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:536]: One optimization we can do is store a destination's schema in cache so that it's accessible to multiple StreamWriters writing to the same table on the same machine

**Comment by ahmedabu98** [comment]
@Abacn can you take a look? Reuven is OOO for some time

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkSchemaUpdateIT.java [hunk 3]
```diff
@@ -539,4 +560,151 @@ public void testAtLeastOnceWithIgnoreUnknownValues() throws Exception {
   public void testAtLeastOnceWithAutoSchemaUpdate() throws Exception {
     runStreamingPipelineWithSchemaChange(Write.Method.STORAGE_API_AT_LEAST_ONCE, true, true);
   }
+
+  public void runDynamicDestinationsWithAutoSchemaUpdate(boolean useAtLeastOnce) throws Exception {
```
Comment (Abacn) [inline sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkSchemaUpdateIT.java:564]: are these new tests intended to run on direct runner (GCP IO PreCommit) or also on Dataflow (Dataflow Runner v1/v2 PostCommit) suite? If the latter, please trigger a PostCommit job to check if the test setting works on a remote runner. If the former, add these tests in the exclusion test in https://github.com/apache/beam/blob/97c4134bfc311093e947abde68eddcd51fce375b/runners/google-cloud-dataflow-java/build.gradle#L631 and https://github.com/apache/beam/blob/97c4134bfc311093e947abde68eddcd51fce375b/runners/google-cloud-dataflow-java/build.gradle#L682

**Review by Abacn — COMMENTED** [review]
Thanks, I saw the existing comments mainly concerned on additional API calls. 

- how often will the additional call will be made. If it's not significant I think this LGTM

- does this PR introduces new API call if schema update feature isn't enabled (reading the change I believe no, but good to confirm)

File: sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkSchemaUpdateIT.java (hunk 3 above)
Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiSinkSchemaUpdateIT.java:564]: Yep this should add two test runs to the Dataflow runner. triggering postcommits now

**Comment by ahmedabu98** [comment]
> how often will the additional call will be made. If it's not significant I think this LGTM

There's a call made for every new StreamWriter, which normally would be every time a new stream is created. In other words, it's roughly equal to the number of concurrent connections created at a given time. I checked in with BigQuery folks and they aren't worried about this quota.

> does this PR introduces new API call if schema update feature isn't enabled 

No this is strictly for when autoUpdateSchema is enabled

**Comment by ahmedabu98** [comment]
The test passed on Dataflow V2 postcommits

**Review by Abacn — APPROVED** [review]
Thank you!

File: CHANGES.md [hunk 4]
```diff
@@ -79,6 +79,8 @@
 ## Bugfixes
 
 * Fixed X (Java/Python) ([#X](https://github.com/apache/beam/issues/X)).
+* Fixed EventTimeTimer ordering in Prism. ([#32222](https://github.com/apache/beam/issues/32222)).
```
Comment (reuvenlax) [inline CHANGES.md:82]: this doesn't seem to be in this PR

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java (hunk 1 above)
Comment (reuvenlax) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/BigQueryServicesImpl.java:1424]: Correct, but if that's the case we should replace it with a getSchema method. getWriteStream may be used in the future for other reasons, and if we always fetch the schema it may cause performance issues.

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java (hunk 2 above)
Comment (reuvenlax) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:536]: so this doesn't quite solve the following race condition:
   - schema S is updated to S' before creating stream writer, we detect it in this codepath and store it in state.
   -  StreamWriter is destroyed (either because it is idle and evicted from the cache, or because the worker crashes).
   - We later recreate the StreamWriter. Because we have an updated schema in cache, we don't execute this codepath.

In this case, I think we'll completely miss the new schema. IIUC the best way to address this race would be for BigQuery to provide us with a version of StreamWriter that returns schemas with new fields - i.e. not basing it off of creation time.

Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:536]: This `if` block would only be executed if we have not detected S' yet. If S' is detected and stored in state, we would execute the first `if` block and use that stored value.

Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:536]: Unless:
1. S is updated to S'
2. current writer recognizes it and stores S' in state
3. writer crashes for whatever reason
4. S' is updated to S''
5. new writer is created, using the schema stored in state: S'

This new writer would have no chance to recognize S'' because it was created after that update.

Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:536]: This is a much narrower edge-case though. It's a small subset of the bigger problem we currently have, which involves essentially **any** new StreamWriter.

Would we be okay with merging this solution and continue to pursue BigQuery to improve things on their side?

File: CHANGES.md (hunk 4 above)
Comment (ahmedabu98) [reply CHANGES.md:82]: Hmm must be from a HEAD sync. will remove, thanks

File: sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java (hunk 2 above)
Comment (reuvenlax) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:535]: Yes, that´s the race condition I had in mind. Is BigQuery planning on improving things on their side_

Comment (ahmedabu98) [reply sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/bigquery/StorageApiWritesShardedRecords.java:535]: Will follow up with them
