### PR TITLE
Fixes #22438. Ensure that WindmillStateReader completes all batched read futures on exceptions

### LINKED ISSUE #22438: [Bug]: Dataflow runner can become stuck with batched state fetches if rpc or coder exceptions are caught
### What happened?

WindmillStateReader consumes batched read requests for a key.  If there are exceptions processing some of the values/tags etc, an exception is thrown but other futures may be left unfulfilled. If the exception is caught by the user and other values are then read, they may block forever on the future.

A fix would be to process the remainder of the response before throwing the exception further, and to ensure that all futures that were not completed by the response are completed with an exception.

### Issue Priority

Priority: 2

### Issue Component

Component: runner-dataflow

### PR DESCRIPTION
**Pull request by scwhittle**
Previously it would throw an exception when processing the response, but leave some futures corresponding to the batch uncompleted.  This could result in hanging calls to get() if the thrown exception was caught and the batched state was then attempted to be read.

Also improve decoder exceptions to only affect the corresponding state not the rest of batched reads.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [ ] [**Choose reviewer(s)**](https://beam.apache.org/contribute/#make-your-change) and mention them in a comment (`R: @username`).
 - [ ] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://beam.apache.org/contribute/#make-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI.

### CODE REVIEW

**Comment by scwhittle** [comment]
R: @reuvenlax

File: runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillStateReader.java [hunk 1]
```diff
@@ -453,30 +453,40 @@ private <ResultT, ContinuationT> Future<Iterable<ResultT>> valuesToPagingIterabl
...
+        throw new RuntimeException("Windmill unexpectedly returned null for request " + request);
+      }
 
-    Windmill.KeyedGetDataRequest request = createRequest(toFetch);
-    Windmill.KeyedGetDataResponse response = server.getStateData(computation, request);
-    if (response == null) {
-      throw new RuntimeException("Windmill unexpectedly returned null for request " + request);
+      // Removes tags from toFetch as they are processed.
+      consumeResponse(response, toFetch);
+    } catch (RuntimeException e) {
```
Comment (reuvenlax) [inline runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillStateReader.java:482]: Why are you catching RuntimeException and not Exception?

Comment (scwhittle) [reply runners/google-cloud-dataflow-java/worker/src/main/java/org/apache/beam/runners/dataflow/worker/WindmillStateReader.java]: No good reason, changed :)
I was thinking that they would only be RuntimeException since this function wasn't otherwise marked as throwing an exception.  However using Exception is more future-proof if non-RuntimeExceptions are added down the road.

**Comment by aaltay** [comment]
@kileys - could we please include this in the release branch cut today?

**Comment by kileys** [comment]
> @kileys - could we please include this in the release branch cut today?

Sure, added the 2.41.0 milestone to the issue

**Comment by reuvenlax** [comment]
LGTM
