### PR TITLE
sdks/go: require type registrations in Native BigQuery IO

### LINKED ISSUE #26298: [Bug][Go SDK] Native BigQuery IO should require registrations for passed in types.
### What happened?

On distributed runners, the type must be registered to ensure it's serialized correctly. This can cause problems for BigQueryIO's "Null" type wrappers, which will lose their type identity going through beam serialization.

The user side solution is to register their type with beam.

```
func init() {
   beam.RegisterType(reflect.TypeOf((*BigQueryEntity)(nil)).Elem())
}
```

Or to use the `register` package on a downstream DoFn, which will register input and output types from the DoFn's ProcessElement method.

```
func init() {
   register.DoFn1x1[BigQueryEntity, Outut]((*myDoFn)(nil))
}
```

However it can be easy to forget to do this. So we can have the BigqueryIO do this at pipeline construction, to make the behavior clear and avoid user issues at pipeline execution time.

By adding to the internal [`mustInferSchema`](https://github.com/apache/beam/blob/sdks/v2.46.0/sdks/go/pkg/beam/io/bigqueryio/bigquery.go#L128) function, and have it get the key and look up the type with the beam runtime functions [`runtime.TypeKey` and `runtime.LookupType`. ](https://github.com/apache/beam/blob/sdks/v2.46.0/sdks/go/pkg/beam/core/runtime/types.go#L50

Note, that due to current limitations on looking up arbitrary types in Go, type registration *must* happen before `beam.Init` is called, so we can't simply register types there. We need to fail with a clear error message and instructions.

### Issue Priority

Priority: 2 (default / most bugs should be filed as P2)

### Issue Components

- [ ] Component: Python SDK
- [ ] Component: Java SDK
- [X] Component: Go SDK
- [ ] Component: Typescript SDK
- [ ] Component: IO connector
- [ ] Component: Beam examples
- [ ] Component: Beam playground
- [ ] Component: Beam katas
- [ ] Component: Website
- [ ] Component: Spark Runner
- [ ] Component: Flink Runner
- [ ] Component: Samza Runner
- [ ] Component: Twister2 Runner
- [ ] Component: Hazelcast Jet Runner
- [ ] Component: Google Cloud Dataflow Runner

### PR DESCRIPTION
**Pull request by mohamedawnallah**
## Description

Fixes #26298.

------------------------

Thank you for your contribution! Follow this checklist to help us incorporate your contribution quickly and easily:

 - [x] Mention the appropriate issue in your description (for example: `addresses #123`), if applicable. This will automatically add a link to the pull request in the issue. If you would like the issue to automatically close on merging the pull request, comment `fixes #<ISSUE NUMBER>` instead.
 - [ ] Update `CHANGES.md` with noteworthy changes.
 - [ ] If this contribution is large, please file an Apache [Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

See the [Contributor Guide](https://beam.apache.org/contribute) for more tips on [how to make review process smoother](https://github.com/apache/beam/blob/master/CONTRIBUTING.md#make-the-reviewers-job-easier).

To check the build health, please visit [https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md](https://github.com/apache/beam/blob/master/.test-infra/BUILD_STATUS.md)

GitHub Actions Tests Status (on master branch)
------------------------------------------------------------------------------------------------
[Build python source distribution and wheels](https://github.com/apache/beam/actions?query=workflow%3A%22Build+python+source+distribution+and+wheels%22+branch%3Amaster+event%3Aschedule)
[Python tests](https://github.com/apache/beam/actions?query=workflow%3A%22Python+Tests%22+branch%3Amaster+event%3Aschedule)
[Java tests](https://github.com/apache/beam/actions?query=workflow%3A%22Java+Tests%22+branch%3Amaster+event%3Aschedule)
[Go tests](https://github.com/apache/beam/actions?query=workflow%3A%22Go+tests%22+branch%3Amaster+event%3Aschedule)

See [CI.md](https://github.com/apache/beam/blob/master/CI.md) for more information about GitHub Actions CI or the [workflows README](https://github.com/apache/beam/blob/master/.github/workflows/README.md) to see a list of phrases to trigger workflows.

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
assign set of reviewers

**Comment by mohamedawnallah** [comment]
Run GoPortable PreCommit

File: sdks/go/pkg/beam/io/bigqueryio/bigquery.go [hunk 1]
```diff
@@ -190,13 +191,35 @@ func mustInferSchema(t reflect.Type) bigquery.Schema {
...
 
+func registerTypeIfNeeded(t reflect.Type) {
+	t = reflectx.SkipPtr(t)
+	key, ok := runtime.TypeKey(t)
+	if !ok {
+		panic(fmt.Sprintf("type %v must be a named type (not anonymous) for registration", t))
+	}
+
+	// Check if Beam has already been initialized.
+	if beam.Initialized() {
```
Comment (damccorm) [inline sdks/go/pkg/beam/io/bigqueryio/bigquery.go:212]: I think beam will always be initialized before this is called since this is part of pipeline construction (https://beam.apache.org/documentation/programming-guide/#creating-a-pipeline). This update also will break existing piupelines which do have types registered correctly already.

I think we can remove this block, and just panic instead of calling `runtime.RegisterType(t)` below (and probably we can rename this function to something like `checkTypeRegistered`

Comment (mohamedawnallah) [reply sdks/go/pkg/beam/io/bigqueryio/bigquery.go]: Thanks! I’ve updated it. Sorry for misinterpreting the previous feedback—I'm still wrapping my head around registering types before and after `beam.Init()`.

Comment (mohamedawnallah) [reply sdks/go/pkg/beam/io/bigqueryio/bigquery.go]: Thanks! I’ve updated it. Sorry for misinterpreting the previous feedback—I'm still wrapping my head around registering types before and after `beam.Init()` in Go SDK.

**Comment by mohamedawnallah** [comment]
Run GoPrism PreCommit

**Review by damccorm — APPROVED** [review]
Thanks!
